### ISSUE TITLE
BitGo docker image

### ISSUE THREAD

**Issue by AbdelkaderBah** [BitGo/BitGoJS#1004]
## Environment Details
* **OS:** Linux
* **Docker version:** 9.8.0

## Expected Behavior
Run environment on production

## Current Behavior
Environment is always: testing

## Possible Solution
Degraded the docker version to 9.7.8

**Comment by tylerlevine** [comment]
Thanks, I'm able to reproduce this. We'll get a fix out ASAP

**Comment by tylerlevine** [comment]
As a temporary workaround, you can set the `BITGO_ENV` environment variable to `prod` to use version `9.8.0` in production config.

**Comment by tylerlevine** [comment]
This should now be fixed in express version `9.8.1`. Thanks for reporting the issue.

**Comment by rakveli** [comment]
please i am having issues with my prod, the test is working fine and the prod is unable to connect to blockchain.
