### ISSUE TITLE
Needs Unlock | Error 400

### ISSUE THREAD

**Issue by bobozar** [BitGo/BitGoJS#102]
Now I run bitgojs-- node bitgo-express -e prod and when I tried sending coins, I got,

`error 400 - needs unlock.`

I changed my access token and put 300000 BTC as the lifetime spending limit, yet I'm getting the same error.

What am I missing?

**Comment by LeoKotschenreuther** [comment]
@bobozar Have a look at [these BitGo Express docs about API access tokens](https://www.bitgo.com/api/v2/#api-access-tokens). Call the `http://$BITGO_EXPRESS_HOST:3080/api/v2/user/session` endpoint as described on the right (for the shell example) and have a look at the response, specifically at the `unlock` value of the response. Do the `time` and `expires` fields make sense?

**Comment by LeoKotschenreuther** [comment]
If you haven't done yet, do [this BitGo Express tutorial](https://platform.bitgo.com/bitgo-express/), at the least the initial authentication part. I know it is for V1 but the authentication stuff is the same in V2, so just replace `v1` with `v2` in the routes.

**Comment by bobozar** [comment]
@LeoKotschenreuther do I need to call http://localhost:3080/api/v1 on production? or it should be https://www.bitgo.com/api/v1?

**Comment by bobozar** [comment]
@LeoKotschenreuther  @thomas4019 I guess it's a bug! It's working fine when I change -e test to -e prod on my PC in local server. But when I hit the production, I keep getting needs unlock!. Tired.

**Comment by bobozar** [comment]
I uninstalled and installed using this method:

# Using NPM
mkdir bitgo-express
cd bitgo-express
npm init
npm install bitgo
./node_modules/bitgo/bin/bitgo-express

Yet, I keep getting error 400: needs unclock!

**Comment by thomas4019** [comment]
I don't think it's an issue with bitgo-express, but rather with the access token you're using. Please email support@bitgo.com with your user and wallet id and they can take a look at your logs and see what's going wrong.

**Comment by bobozar** [comment]
Okay I will do that. But the thing is this token is working on production via local server. @thomas4019

**Comment by bobozar** [comment]
Damn.. lol.. I've fixed the issue and the issue is that I hide my token in bash script.. and bitgo couldn't get it.. but I explictly insert it in the wrapper I wrote. And it worked. But other details like walletID and walletphrase et al can be found in the script by bitgo. dunno why. I will look more into that.
