### ISSUE TITLE
TBTC wallets do not get shown on BitGo Test website after creation.

### ISSUE THREAD

**Issue by lovrobiljeskovic** [BitGo/BitGoJS#104]
Hi, so I'm running into this frustrating problem where I can generate a tbtc wallet through my code(I get a correct output in the terminal that the wallet has been created with its id, address etc) but when I go to the BitGo Test website, I cannot see my newly created wallets. I'm using SDK V2. To make things even more weird, when I do the same exact process but just switching parameters from tbtc to tltc, the wallets get displayed on Test website. I'm not sure what am I doing wrong and how is this possible, please help!

**Comment by LeoKotschenreuther** [comment]
The BitGo website only supports V1 (t)BTC wallets and hence doesn't display your V2 (t)BTC wallet. For all other coins, we only support them in V2 anyways and they are already supported by the website.
