### ISSUE TITLE
sub-dust-threshold amount

### ISSUE THREAD

**Issue by IsmaelMasharo** [BitGo/BitGoJS#106]
Hi, Im trying to make a withdrawal from my testbitgo tbtc wallet. I currently have 4.0985 TBTC and Im trying to withdraw 1 TBTC. Im getting the following error:
![rjson](https://user-images.githubusercontent.com/32596869/38204437-9777a3e2-3668-11e8-8add-dc0f08125a24.PNG)

Im running the BitGo Express REST API in debug mode. Is there a minimum withdraw amount or what Im I missing.

**Comment by LeoKotschenreuther** [comment]
It sounds like you are trying to send 1 satoshi to the address mentioned in the error message. The error message means that this is so little that the owner of the address couldn't spend it without paying more in fees than there are funds on the address.

When you build a transaction you have to specify the amounts you are sending in satoshi, not in (T)BTC. One (T)BTC is 10^8 satoshi. So if you wanted to send 1 TBTC you would have to pass 100000000 for the amount to the build transaction endpoint.

Please contact support@bitgo.com if you have more questions.

**Comment by zeari** [comment]
@LeoKotschenreuther whats the minimum amount you can transfer?

**Comment by Xekyo** [comment]
@zeari: We consider outputs of less than 2730 satoshi to be below dust threshold.

**Comment by bwo** [comment]
> @zeari: We consider outputs of less than 2730 satoshi to be below dust threshold for Bitcoin, Bitcoin Cash, Bitcoin Gold, Zcash and Dash.

Is this still the case? Is this threshold documented or queryable anywhere? It doesn't seem to be mentioned in the api docs, unless I've missed it.
