### ISSUE TITLE
Got error: {"message":"502\n502 Bad Gateway\n\n502 Bad Gateway\nnginx"}

### ISSUE THREAD

**Issue by drsaluml** [BitGo/BitGoJS#1063]
mainnet  
api is return error
Got error: {"message":"502\n502 Bad Gateway\n\n502 Bad Gateway\nnginx"}

**Comment by tylerlevine** [comment]
Thanks for opening the issue @drsaluml. We're aware of intermittent 5xx errors for some APIs. What was the request you were making that resulted in a 502?
