### ISSUE TITLE
Where can i create a enterprise account?

### ISSUE THREAD

**Issue by coffescript** [BitGo/BitGoJS#1086]
Hello, i found make a integration of bitgo, to the time of create wallets for ethereum, the sdk send me a error, i understand what i need create an account enterprise but i dont found the link or the website for get a account enterprise, it is more a request to the side administrative but maybe someone more have the same problem, maybe someone can help me with this part of the process, thanks!!

**Comment by tylerlevine** [comment]
Hello @coffescript, if you send an email to support@bitgo.com they should be able to help you get set up with an enterprise account.
