### ISSUE TITLE
Many withdrawals at a time create a single or multiple transaction?

### ISSUE THREAD

**Issue by IsmaelMasharo** [BitGo/BitGoJS#109]
Does every transaction in bitgo is beetween only two parties or it can involve more?
For example when If i use the Bitgo Express and a bunch of customers make a withdrawal at a time, will a transaction be created for every customer or is it posible to obtain a single transaction with all the customers included?

**Comment by LeoKotschenreuther** [comment]
You can batch transactions together, have a look here:
https://www.bitgo.com/api/v2/#send-transaction-to-many

However, you will have to implement the batching yourself.
This means that you have to decide when and how to batch transactions together.
