### ISSUE TITLE
Inconsistent user webhook coin value

### ISSUE THREAD

**Issue by ledzep2** [BitGo/BitGoJS#111]
The data looks like this. While the rest of the api uses 'btc', 'tbtc', `coin` in here is `bitcoin`, which is inconsistent.
 
    {"type":"block","hash":"000000002dd1e3669dc617bb95dca6e5a4e31bd83582dbc5c567de3b059919b4","coin":"bitcoin","height":1291361,"state":"add"}

**Comment by LeoKotschenreuther** [comment]
@ledzep2 This is because you are likely using a V1 webhook. We do this to distinguish between v1 and v2. Please reopen this Issue if this is not the case.
