### ISSUE TITLE
Block type webhook doesn't notify on ETH new blocks or anything else other than BTC

### ISSUE THREAD

**Issue by ledzep2** [BitGo/BitGoJS#112]
I have added a block type webhook in the web interface (user settings -> developer options).  No coin option available. And only btc blocks notifications can be seen.

**Comment by LeoKotschenreuther** [comment]
Hey @ledzep2 
You are right, our UI only allows you to create btc block notification webhooks. If you want those webhooks for other coins you can use the SDK or our API directly. Please let us know if you have more questions about this.
