### ISSUE TITLE
Same data received via webhook more than once

### ISSUE THREAD

**Issue by IsmaelMasharo** [BitGo/BitGoJS#114]
Im requesting a withdrawal via webhook. Im using flask for the POST webhook notifications. The first time I receive the data I get the transaction. After I process the data I make an http response 200.

![image](https://user-images.githubusercontent.com/32596869/38950294-9fd9410e-430a-11e8-9bd5-e93bff439ea3.png)

![image](https://user-images.githubusercontent.com/32596869/38950305-a51a1058-430a-11e8-94f5-4dc8998c1d21.png)

From console I get this:

![image](https://user-images.githubusercontent.com/32596869/38950311-a7d5eace-430a-11e8-9bf8-ef34ef2e97ed.png)

The problem is that after a while I receive the same webhook notification more than once which is causing an error in the balances updates. 

![image](https://user-images.githubusercontent.com/32596869/38950315-aa06e578-430a-11e8-960f-230cef7138d7.png)

Any thoughts why this could be happening?

**Comment by sebmor** [comment]
I have this issue as well. The wallet webhook is periodically calling for identical updates

**Comment by thomas4019** [comment]
By default a webhook will fire twice as explained in our documentation about the numConfirmations parameter. "Number of confirmations before triggering the webhook. If 0 or unspecified, requests will be sent to the callback endpoint when the transfer is first seen and when it is confirmed." If you only want 1 notification, set numConfirmations to a safe number higher than 0.

**Comment by LeoKotschenreuther** [comment]
@IsmaelMasharo Sounds like @thomas4019 was able to explain what is going on. Did this help you? Feel free to reopen this issue or to create a new one if you still have questions about this.
