### ISSUE TITLE
denied by policy

### ISSUE THREAD

**Issue by IsmaelMasharo** [BitGo/BitGoJS#115]
Hi, Im trying to request a withdrawal of 110,000,000 satoshis (1.1BTC). Ive set a Lifetime Spending Limit of 5 BTC but when I make the request via Bitgo SDK i get the following message:

![image](https://user-images.githubusercontent.com/32596869/39313059-a7dd2604-4936-11e8-87f0-fdbef7d7781b.png)

Im not sure the reason why. Even though, Im able to make withdrawals for amounts less than 1 BTC without problems.

**Comment by jstunich** [comment]
Hey Ismael, 

Can you please contact support@bitgo.com to address this issue? We will reply to you there about this matter as the communication thread could very well involve sensitive information. Thanks for your inquiry and Ill be on the lookout for your ticket. 

-Justin S
BitGo Customer Support

**Comment by LeoKotschenreuther** [comment]
Hey @IsmaelMasharo 
As @jstunich already said, we will be able to help you better if you contact our support directly and share some more infos with us like your walletId.
