### ISSUE TITLE
Local health check endpoint

### ISSUE THREAD

**Issue by icemilo** [BitGo/BitGoJS#116]
There is an endpoint for pinging Bitgo by `GET /api/v[1,2]/ping` but when we use this for healthcheck this gets throttled on Bitgo's side.
It would be good to have an endpoint which returns the health of the running BitgoJS server instead of forwarding the request to Bitgo.

**Comment by icemilo** [comment]
@LeoKotschenreuther I'm not sure the difference between BitGo Express server(legacy BitGoJS server?) and BitGoJS server. I meant the BitGoJS server which is running on a hosted environment.

**Comment by LeoKotschenreuther** [comment]
@icemilo We implemented a healthcheck endpoint for the BitGo Express server. If you update to the latest version of BitGo Express you should be able to call `/api/v1/pingexpress` or `/api/v2/pingexpress` to check whether your BitGo Express server is still running properly.
