### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by torkelrogstad** [BitGo/BitGoJS#117]
Is there any plans to implement TypeScript support for the BitGo JS SDK?

TS support in libraries has the potential to greatly reduce bugs, as many errors are caugt before any code is run. This is especially great for a library for interfacing with financial assets.

**Comment by kaiyzen** [comment]
i tried dts-gen on the library but got an error due to some bug when it was parsing the module and ran int o an issue with some buffer object

**Comment by Xekyo** [comment]
Hey @torkelrogstad,
Thanks for suggestion. We've been contemplating a switch to TypeScript for some time, but unfortunately it is not part of our short-term roadmap.

**Comment by workflow** [comment]
For posterity: The newer versions are now in Typescript!
