### ISSUE TITLE
Wallet Not Found Even After Creating Wallet

### ISSUE THREAD

**Issue by bobozar** [BitGo/BitGoJS#118]
I recently upgraded my wallet and now the first wallet receive address is what I use as the WALLET ID. I'm using the V1 api and when I input my wallet id to create a recieve address, I got this error, 

`u'{"error":"wallet not found","name":"WalletNotFound","requestId":"cjgyzau3o5njjv0la27sckjz1"}'`

I guess the upgraded wallet caused it. Is there a way to downgrade it back? or how can I get the correct wallet id?

I also created a new account with different email, and I used the id of the first wallet created by Bitgo, yet I'm getting wallet not found.

I tried to check for it via api

```
>>> plus_wall = bgo_main_base_url + '/wallet'
>>> rex = requests.get(plus_wall, headers=headers)
>>> rex.json()
{u'count': 0, u'start': 0, u'total': 0, u'limit': 25, u'wallets': []}
```

What's happening? On my test environment, everything is working fine. But on production I'm facing this issue.

**Comment by LeoKotschenreuther** [comment]
@bobozar Please contact support@bitgo.com, they should be able to help you out with this one. You might have to provide them with some confidential data (like wallet id).
