### ISSUE TITLE
BITGO Webhook too slow?

### ISSUE THREAD

**Issue by bobozar** [BitGo/BitGoJS#120]
Sent BTC to my address for the past 2 hrs and Bitgo is yet to notify my webhook about it. In my Bitgo wallet, the btc has been confirmed. I checked the webhook to see if it failed. According to the data below, it shows it didn't fail and Bitgo is yet to even send a notification.

`{u'webhooks': [{u'successiveFailedAttempts': 0, u'created': u'2018-05-10T21:58:55.868Z', u'walletId': u'5ffrrrfffffrrrfffffff', u'lastAttempt': u'2018-05-11T19:07:15.657Z', u'url': u'https://example.com/vc/btc_verify/', u'state': u'active', u'version': 2, u'failingSince': None, u'coin': u'btc', u'type': u'transfer', u'id': u'5af4c09f82b293c740ddffffffff', u'numConfirmations': 2}]}`

Why is that? How can I make it fast?

Also when I tried to simulate webhook via the API, I got 400 error due to transfer id and in the documentation, it stays transferid is not required. How can I get the transferid?

**Comment by LeoKotschenreuther** [comment]
@bobozar Please contact support@bitgo.com and share a couple of extra informations with them (e.g. wallet id, transaction id,...). They should be able to help you.

**Comment by thomas4019** [comment]
Yes, support@bitgo.com is the right place to ask. Fyi, regarding wallet transfer ids you can get them by listing all transfers in a wallet, https://www.bitgo.com/api/v2/#list-wallet-transfers.
