### ISSUE TITLE
Failed to sign input #0 error

### ISSUE THREAD

**Issue by cserb** [BitGo/BitGoJS#125]
I'm trying to create a transaction using bitgo-express.
The weird thing is that out of 30 tries 1 succeeds. 

I get this error:
```
BitGo-Express running
Environment: test
Base URI: http://0.0.0.0:9292
handle: /api/v2/tbtc/wallet/5b06b1e880bb15cd0740e146fe12cdb1/sendcoins
error 400: Failed to sign input #0
10.134.223.54 - local_express [25/May/2018:13:21:45 +0000] "POST /api/v2/tbtc/wallet/5b06b1e880bb15cd0740e146fe12cdb1/sendcoins HTTP/1.1" 400 71 "-" "Faraday v0.13.1"
```

Also looking at the code it's clearly coming from transactionBuilder.js but this line https://github.com/BitGo/BitGoJS/blob/0fb30845014f00473b3d4ec0e152e0941c51e58b/src/transactionBuilder.js#L910 is not executed, though it would be nice to know more about the error.

I also found issue #43 but I'm on node v9.7.1

**Comment by LeoKotschenreuther** [comment]
@cserb Have you tried using Node version 6.9.5 instead?

**Comment by cserb** [comment]
@LeoKotschenreuther yes

**Comment by LeoKotschenreuther** [comment]
I don't know why you can't see the trace. I'm assuming that there is something wrong with your input, please contact support@bitgo.com, they might ask you for some information you don't want to share in Github.

**Comment by thomas4019** [comment]
@cserb This error usually means you're running an older version of our SDK and can't sign a segwit input. Please try updating to the latest SDK version (at least 4.16.0 or later) and contact support@bitgo.com if that doesn't work.

**Comment by cserb** [comment]
Yes, updating the SDK solved the problem
