### ISSUE TITLE
Bug docker build bitgo-express

### ISSUE THREAD

**Issue by CryptoExchanger** [BitGo/BitGoJS#1250]
## Environment Details
**OS:** Ubuntu 20.04

i installed bitgosdk to alot of vps servers but currectly on this i try several times with different OS and some problem come again and again

PROBLEM:

root@easypay-wallet:~# git clone -b rel/latest https://github.com/bitgo/bitgojs
Cloning into 'bitgojs'...
remote: Enumerating objects: 47969, done.
remote: Counting objects: 100% (15100/15100), done.
remote: Compressing objects: 100% (4567/4567), done.
remote: Total 47969 (delta 10636), reused 14796 (delta 10431), pack-reused 32869
Receiving objects: 100% (47969/47969), 24.63 MiB | 10.95 MiB/s, done.
Resolving deltas: 100% (33119/33119), done.
root@easypay-wallet:~# cd bitgojs
root@easypay-wallet:~/bitgojs# docker build -t bitgo-express:latest .
Sending build context to Docker daemon  28.86MB
Step 1/15 : FROM node:10-alpine AS builder
 ---> aa67ba258e18
Step 2/15 : MAINTAINER Tyler Levine <tyler@bitgo.com>
 ---> Using cache
 ---> 931b828afdd1
Step 3/15 : RUN apk add --no-cache git python make g++
 ---> Using cache
 ---> 38300891a642
Step 4/15 : COPY --chown=node:node . /tmp/bitgo/
 ---> bc82a82f49f3
Step 5/15 : WORKDIR /tmp/bitgo/modules/express
 ---> Running in c944f22b1f03
Removing intermediate container c944f22b1f03
 ---> 7e274ab50513
Step 6/15 : RUN npm install npm@latest -g
 ---> Running in 8a0c09569bbf
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@7.19.1
added 63 packages from 25 contributors, removed 242 packages and updated 193 packages in 11.467s
Removing intermediate container 8a0c09569bbf
 ---> 6b87ce4ef14a
Step 7/15 : USER node
 ---> Running in 311c0dccf93a
Removing intermediate container 311c0dccf93a
 ---> a87d31f326d0
Step 8/15 : RUN npm ci && npm prune --production
 ---> Running in 86f83e10a56c
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated ethereumjs-tx@2.1.2: New package name format for new versions: @ethereumjs/tx. Please update.
npm WARN deprecated uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated ethereumjs-tx@1.3.7: New package name format for new versions: @ethereumjs/tx. Please update.
npm WARN deprecated @web3-js/scrypt-shim@0.1.0: This package is deprecated, for a pure JS implementation please use scrypt-js
npm WARN deprecated @types/bignumber.js@5.0.0: This is a stub types definition for bignumber.js (https://github.com/MikeMcl/bignumber.js/). bignumber.js provides its own type definitions, so you don't need @types/bignumber.js installed!
npm WARN deprecated @web3-js/websocket@1.0.30: The branch for this fork was merged upstream, please update your package to websocket@1.0.31
npm WARN deprecated ethereumjs-common@1.5.2: New package name format for new versions: @ethereumjs/common. Please update.
npm WARN deprecated core-js@1.2.7: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code ENOMEM
npm ERR! syscall spawn
npm ERR! errno ENOMEM
npm ERR! spawn ENOMEM

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2021-07-02T11_38_19_848Z-debug.log
The command '/bin/sh -c npm ci && npm prune --production' returned a non-zero code: 1
root@easypay-wallet:~/bitgojs#

**Comment by tylerlevine** [comment]
You are running out of memory in your build container, please try running `docker build` with more memory available using the `-m` flag.
