### ISSUE TITLE
When BitGo SDK used AuthVersion 3 returned Error

### ISSUE THREAD

**Issue by t10471** [BitGo/BitGoJS#1251]
## Environment Details
* **OS:** Mac OS 11.4
* **Node Version:**  v14.16.0
* **Yarn Version:** 1.22.10
* **BitGoJS Version:** 11.17.0-rc.2
* **BitGo Environment:** testnet

## Expected Behavior
retrun HMAC

## Current Behavior
When use auth version 3 returned `UnhandledPromiseRejectionWarning: Error: invalid response HMAC, possible man-in-the-middle-attack`.
That error is from [this logic](https://github.com/BitGo/BitGoJS/blob/2b26e8ded6282a8cde730d7bc9dcf1fac92bb701/modules/core/src/bitgo.ts#L732).
And when I used BitGoJS/11.16.0, returned `Error: unauthorized`.

I think that BitGo's default setting not use version 3.
https://github.com/BitGo/BitGoJS/blob/158b705818f6239e4044d7ea0fd3d46059fc2672/modules/core/src/bitgo.ts#L440
https://github.com/BitGo/BitGoJS/blob/158b705818f6239e4044d7ea0fd3d46059fc2672/modules/core/src/bitgo.ts#L492
https://github.com/BitGo/BitGoJS/blob/158b705818f6239e4044d7ea0fd3d46059fc2672/modules/core/src/bitgo.ts#L626

And test env need hmac verification.
https://github.com/BitGo/BitGoJS/blob/158b705818f6239e4044d7ea0fd3d46059fc2672/modules/core/src/bitgo.ts#L703
https://github.com/BitGo/BitGoJS/blob/3f33f95665f0eec64445aa5a50891297bfff3d26/modules/core/src/v2/environments.ts#L142

It's seems that version 3 verification logic Exists. 
https://github.com/BitGo/BitGoJS/blob/158b705818f6239e4044d7ea0fd3d46059fc2672/modules/core/src/bitgo.ts#L1285
https://github.com/BitGo/BitGoJS/blob/158b705818f6239e4044d7ea0fd3d46059fc2672/modules/core/src/bitgo.ts#L695

## Possible Solution
I think that server side bug or when used version 3 must skip verification logic.

## Steps to Reproduce
I wrote source code.
```js
const BitGoJS = require('bitgo');
const bitgo = new BitGoJS.BitGo({ env: 'test', authVersion: 3, accessToken: process.env.ACCESS_TOKEN });

(async function () {
    const wallets = await bitgo.coin('tbtc').wallets().list({});
    wallets.wallets.forEach(wallet => {
        console.log(`Wallet label: ${wallet.label()}`);
        console.log(`Wallet ID: ${wallet.id()}`);
    });
})();
```

**Comment by tylerlevine** [comment]
Thanks, I'll take a look at this issue. I've changed the `latest` dist tag back to `11.16.0` for now, as it was incorrectly updated to the release candidate version.
