### ISSUE TITLE
BitGo SDK works with node but returns 401 unauthorized on web

### ISSUE THREAD

**Issue by glabit** [BitGo/BitGoJS#126]
I am trying to use bitgo with my laravel app (with webpack by default) but looks like it doesn't work with web. (on test env)

Using the list-wallets.js example, and my access token, I get a successfull response with the coresponding details, but if I include the compiled js file in a html file to run it in browser, I always get {error: "unauthorized", name: "Unauthorized", requestId: "cjibyjl6o0ehpruruwse6os4z"}

I am sure that the access token is correct as long as it works using node.

I`ve also tried to edit the webpack config to switch it from 'web' default target to 'node' but after, i get other errors like 'required' is not defined.

I read, I tried everything I knew, but no success.

Steps to reproduce: 
Laravel 5.6 fresh installation 
npm install
npm install bitgo 
window.BitGoJS = require('bitgo'); //in bootstrap.js, so it's anywhere available
copy code from /examples/v2/list-wallets.js and replace with a valid access token from test.bitgo.com
compile assets using laravel-mix (webpack base)
Console Error: GET https://test.bitgo.com/api/v2/tbtc/wallet 401 (Unauthorized)

**Comment by thomas4019** [comment]
Hi glabit,
Please see the ["Usage in Browser"](https://github.com/BitGo/BitGoJS#usage-in-browser) section in the readme. Usually, for web we recommend making a browser build using “npm run compile”, and then including the bundled file with a script tag in the html.

**Comment by valarmathi555** [comment]
i trying use ti Bitgo SDk for Bitcoin address generate in nodejs but show in cmd 
like this

 UnhandledPromiseRejectionWarning: Error: unauthorized

**Comment by valarmathi555** [comment]
i trying use to Bitgo SDk for Bitcoin address generate in nodejs but show in cmd
like this

**Comment by valarmathi555** [comment]
i trying use to Bitgo SDk for Bitcoin address generate in nodejs but show in cmd
like this

UnhandledPromiseRejectionWarning: Error: unauthorized
