### ISSUE TITLE
bitgo recovery wizard

### ISSUE THREAD

**Issue by mastersly** [BitGo/BitGoJS#1270]
I recently received the following error message for a wallet:
No input to recover - aborting!
does anyone know this problem?
the entered data is correct and worked.
Many Thanks

**Comment by tylerlevine** [comment]
This means that the recovery wizard looked for recoverable funds on your wallet but wasn't able to find any. Would you mind reaching out to support@bitgo.com with you wallet information? They should be able to help you out
