### ISSUE TITLE
Webhook events do not stop.

### ISSUE THREAD

**Issue by nowapoca** [BitGo/BitGoJS#128]
I am trying to receive events from Webhooks. As I read, BitGo events are triggered when the specified event occurs. I do not know what is happening but events occurs all the time. 
For example in this photo, same two events are coming repeatly. Do you know what is happening?
![examples](https://user-images.githubusercontent.com/34867334/41485384-b6c98304-70b6-11e8-96d6-74665bbc0659.png)

**Comment by CapnMigraine** [comment]
Hi @nowapoca,

It looks like your webhook endpoint is not responding with a 200 OK status after receiving the notification request. So the webhook keeps retrying to deliver it.

Please see https://www.bitgo.com/api/v2/#webhook-notifications for more information.
