### ISSUE TITLE
Does Webhook response on ERC20 token transactions?

### ISSUE THREAD

**Issue by trung-ftt** [BitGo/BitGoJS#130]
Hi Bitgo team,

I am testing Webhook in the test-net environment and all the coin seems working great. 
However, when I sent TERC tokens to one of my TETH address (which is already setup with Webhook), there were no responses or notifications from Webhook. 
So, does Webhook returns any responses on ERC20 token transactions? Or do we need to set up Webhook for ERC20 tokens? Or other ways???

Thank you. Your help would be greatly appreciated,
Trung

**Comment by CapnMigraine** [comment]
Hi @trung-ftt,

You need to set up a token-specific webhook in order to get notified about TERC transfers (i.e. add a webhook with TERC as coin to your wallet)

**Comment by trung-ftt** [comment]
Hi @CapnMigraine,

Following your instructions, I have created a TERC webhook and I have got notified about TERC transfers.
Thanks a lot for your help.
