### ISSUE TITLE
Error installing via npm

### ISSUE THREAD

**Issue by almantasr** [BitGo/BitGoJS#132]
![error](https://user-images.githubusercontent.com/11739337/41855859-52ce0f80-789c-11e8-8932-a66a644ebe56.PNG)

Hello,
struggling to install package via npm. The latest version I was able to install is 2.4.2.
Node and npm versions meet the requirements

**Comment by LeoKotschenreuther** [comment]
@almantasr Are you still having that problem?

**Comment by almantasr** [comment]
Thanks, everything is ok
