### ISSUE TITLE
My wallets are not confirming

### ISSUE THREAD

**Issue by nowapoca** [BitGo/BitGoJS#133]
Hi, i am in troubles. I am creating wallets and I can see how these wallets are waiting to be confirmed. But, when I click to see the status button of the wallet, it shows me that the txHash does not exist. Of course, the wallet never get confirmed. Any ideas?
![txhashnotexist](https://user-images.githubusercontent.com/34867334/41930534-ae3dee84-7951-11e8-88d8-5d8b93af70e9.png)
![unconfirmedwallet](https://user-images.githubusercontent.com/34867334/41930542-b3a9a1ce-7951-11e8-8c1c-432f3068f9c5.png)

**Comment by LeoKotschenreuther** [comment]
@nowapoca Please contact [the BitGo Support](https://bitgo.freshdesk.com/support/solutions) and share your walletId with them! They should be able to help you with that information.
