### ISSUE TITLE
getting KeyError at /bitgo 

### ISSUE THREAD

**Issue by Rubitwallet** [BitGo/BitGoJS#135]
oin | 'btc'
-- | --
pp | 'GZMTENCKGZ3FKNKP'
request | <WSGIRequest: GET '/bitgo'>
res | {'error': 'You have called a BitGo Express endpoint but this is the BitGo '           'server. Please have a look at the BitGo Express documentation: '           'https://www.bitgo.com/api/v2/#bitgo-express-rest-api',  'name': 'ApiError',  'requestId': 'cjj8juqch1z1k8lla0hqb9a9r'}
username | 'mithlesh4257'

**Comment by LeoKotschenreuther** [comment]
@Rubitwallet You are probably confusing the difference between BitGo Express and the BitGo Server. The route you're trying to call should be handled by BitGo Express (which you run somewhere in your environment) but you called the BitGo Server (that BitGo is running) instead. This is especially important for routes where you are sending some sensitive information (like keys or passwords) in clear text to your BitGo Express instance. These should never be sent to the BitGo Server.

**Comment by LeoKotschenreuther** [comment]
@Rubitwallet Have a look at the [BitGo Express Docs](https://github.com/BitGo/BitGoJS#bitgo-express-local-signing-server-rest-api). You can also contact support@bitgo.com if you have further questions.

**Comment by Rubitwallet** [comment]
http://node-express-env.vi2kf6fhhd.ap-south-1.elasticbeanstalk.com/info/

when i clicked on login it's not opening
