### ISSUE TITLE
Bitgo Express Error : Cannot find Ripple-keypairs module

### ISSUE THREAD

**Issue by b3h3rkz** [BitGo/BitGoJS#137]
`node version` v9.8.0
`npm version` 5.6.0

I am using the Bitgo Express Rest API, I was able to successfully check the status of my access token.
But  any calls to check balance or sendin tBTC results in this error.

I installed the ripple-keypairs module on npm, same issue
`{"error":"Cannot find module 'ripple-keypairs'","message":"Cannot find module 'ripple-keypairs'"}`

**Comment by thomas4019** [comment]
Hi Bernard,
Can you post the result of running `npm list | grep ripple-keypairs`? Can you also try manually installing the library while in the BitGoJS folder, `npm install ripple-keypairs` and see if that resolves your issue?

**Comment by b3h3rkz** [comment]
Hi @thomas4019 I ran the command and got this

`npm ERR! extraneous: JSONStream@1.3.3
/Users/bernardparah/node_modules/npm/node_modules/JSONStream
npm ERR! extraneous: abbrev@1.1.1 /Users/bernardparah/node_modules/npm/node_modules/abbrev
npm ERR! extraneous: ansicolors@0.3.2 /Users/bernardparah/node_modules/npm/node_modules/ansicolors
npm ERR! extraneous: ansistyles@0.1.3 /Users/bernardparah/node_modules/npm/node_modules/ansistyles
npm ERR! extraneous: aproba@1.2.0 /Users/bernardparah/node_modules/npm/node_modules/aproba
npm ERR! extraneous: archy@1.0.0 /Users/bernardparah/node_modules/npm/node_modules/archy
npm ERR! extraneous: bin-links@1.1.2 /Users/bernardparah/node_modules/npm/node_modules/bin-links
npm ERR! extraneous: bluebird@3.5.1 /Users/bernardparah/node_modules/npm/node_modules/bluebird
npm ERR! extraneous: byte-size@4.0.3 /Users/bernardparah/node_modules/npm/node_modules/byte-size
npm ERR! extraneous: cacache@11.0.2 /Users/bernardparah/node_modules/npm/node_modules/cacache
npm ERR! extraneous: call-limit@1.1.0 /Users/bernardparah/node_modules/npm/node_modules/call-limit
npm ERR! extraneous: chownr@1.0.1 /Users/bernardparah/node_modules/npm/node_modules/chownr
npm ERR! extraneous: cli-columns@3.1.2 /Users/bernardparah/node_modules/npm/node_modules/cli-columns
npm ERR! extraneous: cli-table3@0.5.0 /Users/bernardparah/node_modules/npm/node_modules/cli-table3
npm ERR! extraneous: cmd-shim@2.0.2 /Users/bernardparah/node_modules/npm/node_modules/cmd-shim
npm ERR! extraneous: columnify@1.5.4 /Users/bernardparah/node_modules/npm/node_modules/columnify
npm ERR! extraneous: config-chain@1.1.11 /Users/bernardparah/node_modules/npm/node_modules/config-chain
npm ERR! extraneous: debuglog@1.0.1 /Users/bernardparah/node_modules/npm/node_modules/debuglog
npm ERR! extraneous: detect-indent@5.0.0 /Users/bernardparah/node_modules/npm/node_modules/detect-indent
npm ERR! extraneous: detect-newline@2.1.0 /Users/bernardparah/node_modules/npm/node_modules/detect-newline
npm ERR! extraneous: dezalgo@1.0.3 /Users/bernardparah/node_modules/npm/node_modules/dezalgo
npm ERR! extraneous: editor@1.0.0 /Users/bernardparah/node_modules/npm/node_modules/editor
npm ERR! extraneous: figgy-pudding@3.1.0 /Users/bernardparah/node_modules/npm/node_modules/figgy-pudding
npm ERR! extraneous: find-npm-prefix@1.0.2 /Users/bernardparah/node_modules/npm/node_modules/find-npm-prefix
npm ERR! extraneous: fs-vacuum@1.2.10 /Users/bernardparah/node_modules/npm/node_modules/fs-vacuum
npm ERR! extraneous: fs-write-stream-atomic@1.0.10 /Users/bernardparah/node_modules/npm/node_modules/fs-write-stream-atomic
npm ERR! extraneous: gentle-fs@2.0.1 /Users/bernardparah/node_modules/npm/node_modules/gentle-fs
npm ERR! extraneous: glob@7.1.2 /Users/bernardparah/node_modules/npm/node_modules/glob
npm ERR! extraneous: graceful-fs@4.1.11 /Users/bernardparah/node_modules/npm/node_modules/graceful-fs
npm ERR! extraneous: has-unicode@2.0.1 /Users/bernardparah/node_modules/npm/node_modules/has-unicode
npm ERR! extraneous: hosted-git-info@2.6.0 /Users/bernardparah/node_modules/npm/node_modules/hosted-git-info
npm ERR! extraneous: iferr@1.0.0 /Users/bernardparah/node_modules/npm/node_modules/iferr
npm ERR! extraneous: imurmurhash@0.1.4 /Users/bernardparah/node_modules/npm/node_modules/imurmurhash
npm ERR! extraneous: inflight@1.0.6 /Users/bernardparah/node_modules/npm/node_modules/inflight
npm ERR! extraneous: inherits@2.0.3 /Users/bernardparah/node_modules/npm/node_modules/inherits
npm ERR! extraneous: ini@1.3.5 /Users/bernardparah/node_modules/npm/node_modules/ini
npm ERR! extraneous: init-package-json@1.10.3 /Users/bernardparah/node_modules/npm/node_modules/init-package-json
npm ERR! extraneous: is-cidr@2.0.6 /Users/bernardparah/node_modules/npm/node_modules/is-cidr
npm ERR! extraneous: json-parse-better-errors@1.0.2 /Users/bernardparah/node_modules/npm/node_modules/json-parse-better-errors
npm ERR! extraneous: lazy-property@1.0.0 /Users/bernardparah/node_modules/npm/node_modules/lazy-property
npm ERR! extraneous: libcipm@2.0.0 /Users/bernardparah/node_modules/npm/node_modules/libcipm
npm ERR! extraneous: libnpmhook@4.0.1 /Users/bernardparah/node_modules/npm/node_modules/libnpmhook
npm ERR! extraneous: libnpx@10.2.0 /Users/bernardparah/node_modules/npm/node_modules/libnpx
npm ERR! extraneous: lock-verify@2.0.2 /Users/bernardparah/node_modules/npm/node_modules/lock-verify
npm ERR! extraneous: lockfile@1.0.4 /Users/bernardparah/node_modules/npm/node_modules/lockfile
npm ERR! extraneous: lodash._baseindexof@3.1.0 /Users/bernardparah/node_modules/npm/node_modules/lodash._baseindexof
npm ERR! extraneous: lodash._baseuniq@4.6.0 /Users/bernardparah/node_modules/npm/node_modules/lodash._baseuniq
npm ERR! extraneous: lodash._bindcallback@3.0.1 /Users/bernardparah/node_modules/npm/node_modules/lodash._bindcallback
npm ERR! extraneous: lodash._cacheindexof@3.0.2 /Users/bernardparah/node_modules/npm/node_modules/lodash._cacheindexof
npm ERR! extraneous: lodash._createcache@3.1.2 /Users/bernardparah/node_modules/npm/node_modules/lodash._createcache
npm ERR! extraneous: lodash._getnative@3.9.1 /Users/bernardparah/node_modules/npm/node_modules/lodash._getnative
npm ERR! extraneous: lodash.clonedeep@4.5.0 /Users/bernardparah/node_modules/npm/node_modules/lodash.clonedeep
npm ERR! extraneous: lodash.restparam@3.6.1 /Users/bernardparah/node_modules/npm/node_modules/lodash.restparam
npm ERR! extraneous: lodash.union@4.6.0 /Users/bernardparah/node_modules/npm/node_modules/lodash.union
npm ERR! extraneous: lodash.uniq@4.5.0 /Users/bernardparah/node_modules/npm/node_modules/lodash.uniq
npm ERR! extraneous: lodash.without@4.4.0 /Users/bernardparah/node_modules/npm/node_modules/lodash.without
npm ERR! extraneous: lru-cache@4.1.3 /Users/bernardparah/node_modules/npm/node_modules/lru-cache
npm ERR! extraneous: meant@1.0.1 /Users/bernardparah/node_modules/npm/node_modules/meant
npm ERR! extraneous: mississippi@3.0.0 /Users/bernardparah/node_modules/npm/node_modules/mississippi
npm ERR! extraneous: mkdirp@0.5.1 /Users/bernardparah/node_modules/npm/node_modules/mkdirp
npm ERR! extraneous: move-concurrently@1.0.1 /Users/bernardparah/node_modules/npm/node_modules/move-concurrently
npm ERR! extraneous: node-gyp@3.7.0 /Users/bernardparah/node_modules/npm/node_modules/node-gyp
npm ERR! extraneous: nopt@4.0.1 /Users/bernardparah/node_modules/npm/node_modules/nopt
npm ERR! extraneous: normalize-package-data@2.4.0 /Users/bernardparah/node_modules/npm/node_modules/normalize-package-data
npm ERR! extraneous: npm-audit-report@1.3.1 /Users/bernardparah/node_modules/npm/node_modules/npm-audit-report
npm ERR! extraneous: npm-cache-filename@1.0.2 /Users/bernardparah/node_modules/npm/node_modules/npm-cache-filename
npm ERR! extraneous: npm-install-checks@3.0.0 /Users/bernardparah/node_modules/npm/node_modules/npm-install-checks
npm ERR! extraneous: npm-lifecycle@2.0.3 /Users/bernardparah/node_modules/npm/node_modules/npm-lifecycle
npm ERR! extraneous: npm-package-arg@6.1.0 /Users/bernardparah/node_modules/npm/node_modules/npm-package-arg
npm ERR! extraneous: npm-packlist@1.1.10 /Users/bernardparah/node_modules/npm/node_modules/npm-packlist
npm ERR! extraneous: npm-pick-manifest@2.1.0 /Users/bernardparah/node_modules/npm/node_modules/npm-pick-manifest
npm ERR! extraneous: npm-profile@3.0.2 /Users/bernardparah/node_modules/npm/node_modules/npm-profile
npm ERR! extraneous: npm-registry-client@8.5.1 /Users/bernardparah/node_modules/npm/node_modules/npm-registry-client
npm ERR! extraneous: npm-registry-fetch@1.1.0 /Users/bernardparah/node_modules/npm/node_modules/npm-registry-fetch
npm ERR! extraneous: npm-user-validate@1.0.0 /Users/bernardparah/node_modules/npm/node_modules/npm-user-validate
npm ERR! extraneous: npmlog@4.1.2 /Users/bernardparah/node_modules/npm/node_modules/npmlog
npm ERR! extraneous: once@1.4.0 /Users/bernardparah/node_modules/npm/node_modules/once
npm ERR! extraneous: opener@1.4.3 /Users/bernardparah/node_modules/npm/node_modules/opener
npm ERR! extraneous: osenv@0.1.5 /Users/bernardparah/node_modules/npm/node_modules/osenv
npm ERR! extraneous: pacote@8.1.6 /Users/bernardparah/node_modules/npm/node_modules/pacote
npm ERR! extraneous: path-is-inside@1.0.2 /Users/bernardparah/node_modules/npm/node_modules/path-is-inside
npm ERR! extraneous: promise-inflight@1.0.1 /Users/bernardparah/node_modules/npm/node_modules/promise-inflight
npm ERR! extraneous: qrcode-terminal@0.12.0 /Users/bernardparah/node_modules/npm/node_modules/qrcode-terminal
npm ERR! extraneous: query-string@6.1.0 /Users/bernardparah/node_modules/npm/node_modules/query-string
npm ERR! extraneous: qw@1.0.1 /Users/bernardparah/node_modules/npm/node_modules/qw
npm ERR! extraneous: read@1.0.7 /Users/bernardparah/node_modules/npm/node_modules/read
npm ERR! extraneous: read-cmd-shim@1.0.1 /Users/bernardparah/node_modules/npm/node_modules/read-cmd-shim
npm ERR! extraneous: read-installed@4.0.3 /Users/bernardparah/node_modules/npm/node_modules/read-installed
npm ERR! extraneous: read-package-json@2.0.13 /Users/bernardparah/node_modules/npm/node_modules/read-package-json
npm ERR! extraneous: read-package-tree@5.2.1 /Users/bernardparah/node_modules/npm/node_modules/read-package-tree
npm ERR! extraneous: readable-stream@2.3.6 /Users/bernardparah/node_modules/npm/node_modules/readable-stream
npm ERR! extraneous: readdir-scoped-modules@1.0.2 /Users/bernardparah/node_modules/npm/node_modules/readdir-scoped-modules
npm ERR! extraneous: request@2.81.0 /Users/bernardparah/node_modules/npm/node_modules/request
npm ERR! extraneous: retry@0.12.0 /Users/bernardparah/node_modules/npm/node_modules/retry
npm ERR! extraneous: rimraf@2.6.2 /Users/bernardparah/node_modules/npm/node_modules/rimraf
npm ERR! extraneous: safe-buffer@5.1.2 /Users/bernardparah/node_modules/npm/node_modules/safe-buffer
npm ERR! extraneous: semver@5.5.0 /Users/bernardparah/node_modules/npm/node_modules/semver
npm ERR! extraneous: sha@2.0.1 /Users/bernardparah/node_modules/npm/node_modules/sha
npm ERR! extraneous: slide@1.1.6 /Users/bernardparah/node_modules/npm/node_modules/slide
npm ERR! extraneous: sorted-object@2.0.1 /Users/bernardparah/node_modules/npm/node_modules/sorted-object
npm ERR! extraneous: sorted-union-stream@2.1.3 /Users/bernardparah/node_modules/npm/node_modules/sorted-union-stream
npm ERR! extraneous: ssri@6.0.0 /Users/bernardparah/node_modules/npm/node_modules/ssri
npm ERR! extraneous: tar@4.4.4 /Users/bernardparah/node_modules/npm/node_modules/tar
npm ERR! extraneous: text-table@0.2.0 /Users/bernardparah/node_modules/npm/node_modules/text-table
npm ERR! extraneous: tiny-relative-date@1.3.0 /Users/bernardparah/node_modules/npm/node_modules/tiny-relative-date
npm ERR! extraneous: uid-number@0.0.6 /Users/bernardparah/node_modules/npm/node_modules/uid-number
npm ERR! extraneous: umask@1.1.0 /Users/bernardparah/node_modules/npm/node_modules/umask
npm ERR! extraneous: unique-filename@1.1.0 /Users/bernardparah/node_modules/npm/node_modules/unique-filename
npm ERR! extraneous: unpipe@1.0.0 /Users/bernardparah/node_modules/npm/node_modules/unpipe
npm ERR! extraneous: update-notifier@2.5.0 /Users/bernardparah/node_modules/npm/node_modules/update-notifier
npm ERR! extraneous: uuid@3.3.2 /Users/bernardparah/node_modules/npm/node_modules/uuid
npm ERR! extraneous: validate-npm-package-license@3.0.3 /Users/bernardparah/node_modules/npm/node_modules/validate-npm-package-license
npm ERR! extraneous: validate-npm-package-name@3.0.0 /Users/bernardparah/node_modules/npm/node_modules/validate-npm-package-name
npm ERR! extraneous: which@1.3.1 /Users/bernardparah/node_modules/npm/node_modules/which
npm ERR! extraneous: worker-farm@1.6.0 /Users/bernardparah/node_modules/npm/node_modules/worker-farm
npm ERR! extraneous: wrappy@1.0.2 /Users/bernardparah/node_modules/npm/node_modules/wrappy
npm ERR! extraneous: write-file-atomic@2.3.0 /Users/bernardparah/node_modules/npm/node_modules/write-file-atomic`

**Comment by b3h3rkz** [comment]
hi @thomas4019 I ran the command and a lot of npm errors were thrown, I tried installing it manually and it worked. 
Also, I had to manually install two other libs after installing the `keypairs` one.
1. `ripple-binary-codec`
2. `ripple-hashes`

shouldn't these all be installed when one runs `npm install` during setup?
BTW, thanks for the direction, issue resolved
