### ISSUE TITLE
Example is incorrect,  userKey should be backupKey

### ISSUE THREAD

**Issue by christsim** [BitGo/BitGoJS#138]
https://github.com/BitGo/BitGoJS/blob/115abb505a77a50fd8f95591d30f044d12d633e5/example/oauthCreateWalletInEnterprise.js#L81

```
            console.log('Backup keychain encrypted xPrv - WRITE IT DOWN: ' + bitgo.encrypt({ password: walletPassPhrase, input: userKey.xprv }));
```
should be 

```
            console.log('Backup keychain encrypted xPrv - WRITE IT DOWN: ' + bitgo.encrypt({ password: walletPassPhrase, input: backupKey.xprv }));

```

**Comment by LeoKotschenreuther** [comment]
Hi @christsim thanks for reporting. We should have it corrected with the next SDK release.

**Comment by LeoKotschenreuther** [comment]
Fixed with https://github.com/BitGo/BitGoJS/commit/f68627daaef7c87127026c9cd27c2fc060609924
