### ISSUE TITLE
Created wallet gives warning "This is an older BitGo wallet. Follow these instructions to upgrade to the newest, most feature-rich BitGo wallet."

### ISSUE THREAD

**Issue by bbc4468** [BitGo/BitGoJS#139]
Hi,
I am using version 4.27. I use bitgo.wallets().createWalletWithKeychains function to create wallet. When i login on bitgo dashboard and open the wallet, it gives me the following warning.

"This is an older BitGo wallet. Follow these instructions to upgrade to the newest, most feature-rich BitGo wallet."

What am I missing?

**Comment by LeoKotschenreuther** [comment]
Hi @bbc4468 you are creating a v1 wallet. If you want to create a v2 wallet you should follow [this example](https://github.com/BitGo/BitGoJS/blob/master/example/v2/create-wallet.js).

**Comment by bbc4468** [comment]
Got it. Thanks!
