### ISSUE TITLE
Return transaction id in approval callback

### ISSUE THREAD

**Issue by bbc4468** [BitGo/BitGoJS#140]
We have enabled approvals on transactions. We are listening to approval webhook and were expecting we will get the transaction id in the webhook data. Now, we do get another transaction callback, but how do we associate a transaction with the approval_id?

**Comment by CapnMigraine** [comment]
Hi @bbc4468,

When using pending approval webhooks, you will receive the pendingApprovalId in the payload of the request made to your webhook's URL. You can use this value to fetch the pending approval and get the transaction information from the `info.transactionRequest` property returned in the result. 
For more information about that API endpoint, please refer to https://www.bitgo.com/api/v2/#get-pending-approval

**Comment by bbc4468** [comment]
Got it. Thanks!
