### ISSUE TITLE
Is it a way to omit otp verification?

### ISSUE THREAD

**Issue by ukrit-himakoon** [BitGo/BitGoJS#142]
Since some of API calls such as sendTransaction required session unlock. Is it possible to omit these otp verifications?

**Comment by ukrit-himakoon** [comment]
One other question, is it available on production as well? I see that it's in the `Development` section on test.bitgo.com

**Comment by LeoKotschenreuther** [comment]
Yes, this is available on production as well.

**Comment by ukrit-himakoon** [comment]
Done, Thx u! @LeoKotschenreuther

**Comment by eusebiogit** [comment]
> 

Sorry, 
Is this still working?
I have an access token setup by web interface; whit all permissions, and whit the lifetime spending limits set, but I am getting the error: 
incorrect otp
needsOTP: true:
needsUnlock:true

when I try make send to many call. Thank you.
