### ISSUE TITLE
Cannot fund eth from kovan testnet faucet to eth wallet address

### ISSUE THREAD

**Issue by ukrit-himakoon** [BitGo/BitGoJS#143]
Hello guys,

I've tried to fund money from `https://faucet.kovan.network/` to eth wallet generated in test.bitgo.com

unfortunately. I cannot top-up this due to running out of gas as below:
![image](https://user-images.githubusercontent.com/3422247/44128125-5c754728-a06b-11e8-85a1-045b2ee5acf3.png)

. please noted that I can fund the money to fee address just fine. 
Is there any other source to make a funding? Thanks!

**Comment by LeoKotschenreuther** [comment]
Hi @ukrit-himakoon 
Our Eth wallets are smart contracts and it looks like the gas limit on your transaction is too low for sending to a smart contract. A gas limit of 21000 typically works fine for sending to a regular eth wallet but it's not enough to send to smart contracts. You could have the faucet fund a regular address first (Setting one up with Metamask is quite easy) where you have control over setting the gas limit for sending transactions and then you could forward the teth to your BitGo wallet. [This GitHub page](https://github.com/kovan-testnet/faucet) shows other sources of getting teth, the Gitter Channel has worked well for me in the past.
