### ISSUE TITLE
Zero balance on my wallet

### ISSUE THREAD

**Issue by dinya007** [BitGo/BitGoJS#146]
In test environment on last Saturday balance of my wallet suddenly reduced to 0. I tried to add new test coins to it but failed. I see new transaction in testnet but calling BitGo express API for wallet's transaction history returns empty array. Can someone please explain why this happened?

**Comment by LeoKotschenreuther** [comment]
Hi @dinya007 thanks for letting us know.
We are already aware of the problem and are working on a fix.

**Comment by LeoKotschenreuther** [comment]
@dinya007 Balances should be back to normal. If you encounter any more issues about this feel free to contact [our support](https://bitgo.freshdesk.com/support/solutions).
