### ISSUE TITLE
Missing data on getAddress

### ISSUE THREAD

**Issue by hfgbarrigas** [BitGo/BitGoJS#147]
Looks like /api/v2/:coin/wallet/:walletId/address/:addressOrId is missing the label field. Tested via SDK and the api directly.

**Comment by LeoKotschenreuther** [comment]
@hfgbarrigas Are you sure your address has a label set? I checked our server endpoint and it should return the label, I also just tried to reproduce this but was unsuccessful.

**Comment by LeoKotschenreuther** [comment]
@hfgbarrigas Please contact our support about the missing label, they will be able to further investigate this. Would be cool if you could create a separate ticket for your other question so that other people can find it easier.
