### ISSUE TITLE
getBlock and getTransaction on v2 api ? 

### ISSUE THREAD

**Issue by julesGoullee** [BitGo/BitGoJS#149]
How we can getBock(blockHeight) and getTransaction(txId) on v2 api ?

**Comment by tloriato** [comment]
From v1:

Blockchain Data

> BitGo provides a public API for getting blockchain data on addresses and transactions. **These APIs do not relate to the concept of BitGo users or wallets.** The purpose of this API endpoint is to allow API consumers to get data on non-BitGo addresses and transactions (similar to the concept of txindex and watchonly in the Satoshi client).

Given that they didn't implement those features in v2, it's safe to say that they are closing up their functions to maintain cohesion. You will have to find this information using the information from full nodes clients that you are maintaining.

**Comment by tylerlevine** [comment]
We are planning to support the v1 versions of these public data endpoints for the foreseeable future.

These routes are not authenticated, so you can continue getting blockchain data from them while using a v2 wallet.
