### ISSUE TITLE
BitGo Express cannot create wallet

### ISSUE THREAD

**Issue by RialtoEnigma** [BitGo/BitGoJS#150]
Hello,

I run the server with the command:
` ./bitgo-express --debug --port 3080 --env prod --bind localhost`

and I post the following: 

`"POST /api/v2/btc/wallet/generate?label=firstwallet&passphrase=mypassphrase HTTP/1.1" 500 73 "-" "python-requests/2.18.4"`

however I get the following error:

> bitgo:express handle: /api/v2/btc/wallet/generate +0ms
> error 500: Missing parameter: label
> Error: Missing parameter: label

I tried printing the arguments in src/v2/wallets.js in the function Wallets.prototype.generateWallet  (line 173) and indeed the object params is empty and no parameters are reaching this stage.

**Comment by tylerlevine** [comment]
You'll need to provide the arguments as body parameters in your POST request.

Here's an example using curl:

```
curl \
-H "Authorization: Bearer $ACCESS_TOKEN" \
-H "Content-Type: application/json" \
-d '{"label": "express wallet", "passphrase": "mywalletpassphrase"}' \
http://localhost:3080/api/v2/tbtc/wallet/generate
```
