### ISSUE TITLE
bitgo expres

### ISSUE THREAD

**Issue by fa-sa** [BitGo/BitGoJS#1531]
## Environment Details
* **OS:** win 10
* **Node Version:** v14.17.0
* **Yarn Version:** 6.14.13
* **BitGoJS Version:** 11.4.0
* **BitGo Environment:** bitgo expres

Hi 
I can not run bitgo expresI get this bug 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (D:\Program Files\nodejs\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:116:5
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:436:5
4 verbose stack     at checkBinReferences_ (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:391:45)
4 verbose stack     at final (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:434:3)
4 verbose stack     at then (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:161:5)
4 verbose stack     at ReadFileContext.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:350:20)
4 verbose stack     at ReadFileContext.callback (D:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:123:16)
4 verbose stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:282:13)
5 verbose cwd C:\
6 verbose Windows_NT 10.0.18363
7 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
8 verbose node v14.17.0
9 verbose npm  v6.14.13
10 error missing script: start
11 verbose exit [ 1, true ]

**Comment by mmcshinsky-bitgo** [comment]
Hi @fa-sa. Using node v14.17.0 and npm v6.14.13, I was unable to reproduce this error.

It looks like your error revolves around the line `4 verbose stack Error: missing script: start`. This most likely means that the command may have accidentally been run improperly. For example; npm: `npm run start`, and for yarn: `yarn start`.

In the case of the module `express`, the lock file is packge-lock.json so using npm commands would be most appropriate. If you comfortable using yarn, you can remove the package-lock.json and run yarn commands (e.g. `yarn install`).

I hope this helps!
