### ISSUE TITLE
Server recommendations

### ISSUE THREAD

**Issue by anandsemtech** [BitGo/BitGoJS#155]
I always start the bitgo-express as below, 
nohup ./bitgo-express --debug --port 3080 --env test --bind xxx.xxx.xx.xx &

But after sometime, the service goes down very often. i had to restart the service again and again.

May I know the best way to resolve this ( cronjob? making it as service in init.d?) or what else?

Moreover can anyone suggest the recommended server configuration for running this?

**Comment by tylerlevine** [comment]
Can you tell me a little more about why the service keeps needing to be restart? What conditions cause it to go down?

**Comment by opheus2** [comment]
create a bash file to run the operation then install pm2 and make then run your bash file with pm2 it would always bring it back up even if you restart your serve

**Comment by tylerlevine** [comment]
Since bitgo@6, bitgo express is now published as a docker container, so you get some nice options there for auto restarting the container using a restart policy. Doing something like pm2 inside the container is also a workable approach.
