### ISSUE TITLE
BITGO API V2. Sending funds (BTC, LTC, etc.) with a fixed commission

### ISSUE THREAD

**Issue by izhtrade** [BitGo/BitGoJS#156]
Hi

In version 1, the method "Send Coins to Address" has a parameter "fee" with which you can set the exact commission. The question is, how to do it in the second version in the "Send Transaction" method?

Thank.

**Comment by dango198** [comment]
2 bitcoin

**Comment by izhtrade** [comment]
Is that the price of the issue)?

**Comment by Xekyo** [comment]
@izhtrade: We have deliberately left out the option to set a fixed fee on V2 as it was a major headache on V1 with people setting fixed fees before knowing the size of transactions and thus over- or underpaying.

Could you tell me more about what you're trying to do? I might be able to suggest an alternative approach that achieves your goal.

**Comment by dango198** [comment]
Do you have Time to sta in contact maby

Met vriendelijke groeten,

Sergio Baptista 
Interphase global electricity

**Comment by Xekyo** [comment]
> The fact is that it would be easier for us to set a fixed commission * (for example, 0.0005 BTC), otherwise we have to calculate it by using the "Build Transaction" function and this is not always convenient and sometimes just not applicable.

I don't understand yet why you would want to do that. You'd be overpaying fees by a factor of 50x or more most of the time. However, you'd also be underpaying whenever you happen to create a transaction with unexpectedly many inputs at medium fees. What is the underlying problem that you want to solve? Do you want your customer to pay the fees for the withdrawal?

**Comment by dango198** [comment]
Please what is going on 

I’m  i’m 2 weeks on the platform and this is happend 

I cant project them i don’t know how

It was for my a finny game and know the are a lot of humans the get it help my please 

This was never my issu 

I whant gift it back and not a hole comuniti desteoy 

Please please please 

The coins flow away whe are scimd on the ip adres 

Met vriendelijke groete

Sergio Baptista 
Interphase global electricity

**Comment by tylerlevine** [comment]
We currently have no plans to implement a fixed fee, for the reasons @Xekyo mentioned above.

For other non-technical issues, please reach out to support@bitgo.com.
