### ISSUE TITLE
Zcash - Wallet creation error

### ISSUE THREAD

**Issue by darwinlagtapon** [BitGo/BitGoJS#157]
"""
Client error: `POST http://127.0.0.1:3080/api/v2/txlm/wallet/generate/` resulted in a `400 Bad Request` response:\n
{"error":"invalid pub key: e5b4b69d00a2d7dc142cdd71361373e421fe594749ab5243c3fd4fb38762bd77","name":"Invalid","requestId (truncated...)

**Comment by tylerlevine** [comment]
Can you please give a bit more information? Is this a zcash issue or stellar (your POST request is to create a stellar wallet)? Are you providing your own public key for the wallet?
