### ISSUE TITLE
500 when following /sendmany example from the docs

### ISSUE THREAD

**Issue by mhluongo** [BitGo/BitGoJS#16]
Following the example at https://bitgo.com/api/?shell#send-coins-to-multiple-addresses, I my local express server and got

```bash
> curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $ACCESS_TOKEN" -d '{"recipients": [{"address": "2N7Sms6BqZaQVp6Cv73qhJeDHmbSzAe7gV1", "amount": 1000}], "walletPassphrase": "passprhase" }' "http://localhost:3080/api/v1/wallet/$WALLETID/sendmany"

{"error":"invalid bitcoin address: 0"} # the server shows this is a 500
```

After fooling with it a bit, I tried the same tx using `/sendcoins`:

```bash
> curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $ACCESS_TOKEN" -d '{"address": "2N7Sms6BqZaQVp6Cv73qhJeDHmbSzAe7gV1", "amount": 1000, "walletPassphrase": "passphrase" }' "http://localhost:3080/api/v1/wallet/$WALLETID/sendcoins"

{"error":"output value is less than dust threshold"}
```

I increase the amount in the `/sendmany` example, and it works. I think both should respond with the same error message (and no 500s).

**Comment by mhluongo** [comment]
Correction- the dust threshold is irrelevant, I made a mistake in the console. So I guess the question is- is `sendmany` broken? Or does it expect different input?

**Comment by mhluongo** [comment]
Ah, it looks an issue with the docs + not properly distinguishing between an array and an object in the JS.

The docs say `/sendmany` takes a recipients argument like `[{address: '38BKDNZbPcLogvVbcx2ekJ9E6Vv94DqDqw’, amount: 1500}, ..]`, not `['38BKDNZbPcLogvVbcx2ekJ9E6Vv94DqDqw': 1500}`.

Editing the title and leaving this open as a docs issue.

**Comment by bencxr** [comment]
Hey there, can you clarify which network you were running Bitgo express on ? Your examples show both testnet and bitcoin addresses (if you use a testnet address on prod it will give the invalid address error).

**Comment by mhluongo** [comment]
@bencxr the original example is the code that I ran- on testnet. The other comments are about the docs, and thus use mainnet addresses.

It's a simple problem- the docs specify the wrong data structure to send, and `wallet.js` doesn't properly validate the data, instead throwing an inscrutable 500.

If there's a repo for the docs (or I just missed them) I'd be happy to provide a PR. I'm less confident in my JS or I'd patch that as well.

**Comment by mhluongo** [comment]
The first example was what I ran on testnet. The second is from the docs- it's using mainnet addresses because I copied it straight out.

**Comment by bencxr** [comment]
@mhluongo the docs specify the more recent version of the structure. If you look into transactionBuilder.js, you will see that we actually support both (backwards compatible). You can specify an array of address: amount object or dictionary of address keys with amounts (however you can't send more than one output to the same address this way). So I don't think that was the cause of a problem in this case.

**Comment by mhluongo** [comment]
Realized I'm running an odler version- `git pull`ing and trying it again
