### ISSUE TITLE
Problems when running scripts, module not found util.cjs

### ISSUE THREAD

**Issue by javierdeveloping** [BitGo/BitGoJS#1628]
Dear community,

I have installed bitgo dependencies using npm install --save bitgo 
andevery time I run a script like this one:

> const BitGoJS = require('bitgo');
> // Read the user authentication section to get your API access token
> const bitgo = new BitGoJS.BitGo({
>   env: 'test',
>   accessToken: "xxxx"
> });
> const coin = bitgo.coin('tbtc');

the error below is produced.

Could you tell me how to fix that? Thanks in advance.

Node version: 14.18.1
NPM: 6.14.15

> node create.js
internal/modules/cjs/loader.js:905
  throw err;

> Error: Cannot find module '../src/util.cjs'
> Require stack:
> - /home/javier/Desktop/sandgo/node_modules/@hashgraph/sdk/lib/EntityIdHelper.cjs
> - /home/javier/Desktop/sandgo/node_modules/@hashgraph/sdk/lib/account/AccountId.cjs
> - /home/javier/Desktop/sandgo/node_modules/@hashgraph/sdk/lib/query/Query.cjs
> - /home/javier/Desktop/sandgo/node_modules/@hashgraph/sdk/lib/account/AccountBalanceQuery.cjs
> - /home/javier/Desktop/sandgo/node_modules/@hashgraph/sdk/lib/exports.cjs
> - /home/javier/Desktop/sandgo/node_modules/@hashgraph/sdk/lib/index.cjs
> - /home/javier/Desktop/sandgo/node_modules/@bitgo/account-lib/dist/src/coin/hbar/utils.js
> - /home/javier/Desktop/sandgo/node_modules/@bitgo/account-lib/dist/src/utils/crypto.js
> - /home/javier/Desktop/sandgo/node_modules/@bitgo/account-lib/dist/src/index.js
> - /home/javier/Desktop/sandgo/node_modules/bitgo/dist/src/v2/coins/algo.js
> - /home/javier/Desktop/sandgo/node_modules/bitgo/dist/src/v2/coins/index.js
> - /home/javier/Desktop/sandgo/node_modules/bitgo/dist/src/v2/coinFactory.js
> - /home/javier/Desktop/sandgo/node_modules/bitgo/dist/src/bitgo.js
> - /home/javier/Desktop/sandgo/node_modules/bitgo/dist/src/index.js
> - /home/javier/Desktop/sandgo/create.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
>     at Module.require (internal/modules/cjs/loader.js:974:19)
>     at require (internal/modules/cjs/helpers.js:93:18)
>     at Object.<anonymous> (/home/javier/Desktop/sandgo/node_modules/@hashgraph/sdk/lib/EntityIdHelper.cjs:21:36)
>     at Module._compile (internal/modules/cjs/loader.js:1085:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
>     at Module.load (internal/modules/cjs/loader.js:950:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
>     at Module.require (internal/modules/cjs/loader.js:974:19)
>     at require (internal/modules/cjs/helpers.js:93:18)
>     at Object.<anonymous> (/home/javier/Desktop/sandgo/node_modules/@hashgraph/sdk/lib/account/AccountId.cjs:8:41)
>     at Module._compile (internal/modules/cjs/loader.js:1085:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
>     at Module.load (internal/modules/cjs/loader.js:950:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/javier/Desktop/sandgo/node_modules/@hashgraph/sdk/lib/EntityIdHelper.cjs',
>     '/home/javier/Desktop/sandgo/node_modules/@hashgraph/sdk/lib/account/AccountId.cjs',
>     '/home/javier/Desktop/sandgo/node_modules/@hashgraph/sdk/lib/query/Query.cjs',
>     '/home/javier/Desktop/sandgo/node_modules/@hashgraph/sdk/lib/account/AccountBalanceQuery.cjs',
>     '/home/javier/Desktop/sandgo/node_modules/@hashgraph/sdk/lib/exports.cjs',
>     '/home/javier/Desktop/sandgo/node_modules/@hashgraph/sdk/lib/index.cjs',
>     '/home/javier/Desktop/sandgo/node_modules/@bitgo/account-lib/dist/src/coin/hbar/utils.js',
>     '/home/javier/Desktop/sandgo/node_modules/@bitgo/account-lib/dist/src/utils/crypto.js',
>     '/home/javier/Desktop/sandgo/node_modules/@bitgo/account-lib/dist/src/index.js',
>     '/home/javier/Desktop/sandgo/node_modules/bitgo/dist/src/v2/coins/algo.js',
>     '/home/javier/Desktop/sandgo/node_modules/bitgo/dist/src/v2/coins/index.js',
>     '/home/javier/Desktop/sandgo/node_modules/bitgo/dist/src/v2/coinFactory.js',
>     '/home/javier/Desktop/sandgo/node_modules/bitgo/dist/src/bitgo.js',
>     '/home/javier/Desktop/sandgo/node_modules/bitgo/dist/src/index.js',
>     '/home/javier/Desktop/sandgo/create.js'
>   ]
> }
> ^
> 
>

**Comment by javierdeveloping** [comment]
Could this be related to the error? [https://www.npmjs.com/package/@hashgraph/sdk](https://www.npmjs.com/package/@hashgraph/sdk)

> Hedera™ Hashgraph JavaScript SDK
> The JavaScript SDK for interacting with Hedera Hashgraph: the official distributed consensus platform built using the hashgraph consensus algorithm for fast, fair and secure transactions. Hedera enables and empowers developers to build an entirely new class of decentralized applications.
> 
> Install
> NOTE: v1 of the SDK is deprecated and support will be discontinued after October 2021. Please install the latest version 2.x or migrate from v1 to the latest 2.x version. You can reference the migration documentation.

**Comment by neppinger** [comment]
Seeing exact same issue as well with latest version and several other versions of the published bitgo npm package

**Comment by javierdeveloping** [comment]
> Seeing exact same issue as well with latest version and several other versions of the published bitgo npm package

Thanks for your comment. Let's wait for official support.

I have considered using only API requests, but coding with SDK make things easier.
