### ISSUE TITLE
installation and dependencies issue

### ISSUE THREAD

**Issue by femithz** [BitGo/BitGoJS#1678]
## Environment Details
* **OS:** 
* **Node Version:** 
* **Yarn Version:** 
* **BitGoJS Version:** 
* **BitGo Environment:** 

## Expected Behavior

After going through the whole doc and reading through the official doc I proceed to install

## Current Behavior

 The installation went well but at the start of the application  
      am getting an error message which goes thus :
         Error: Cannot find module 'bcrypto.node'

**Comment by mmcshinsky-bitgo** [comment]
Hi @femithz. Are you able to add versions per the Environmental Details section above?

**Comment by mmcshinsky-bitgo** [comment]
Due to inactivity, this issue is marked as stale and closed. Please reach out if there are further questions.
