### ISSUE TITLE
Unexpected API response for insufficient funds

### ISSUE THREAD

**Issue by chris-martin** [BitGo/BitGoJS#17]
When the wallet balance is too low, the "Send Coins to Address" API returns a 500 HTTP status and something like this:

```json
{
  "available": 406245,
  "message": "Insufficient funds",
  "fee": 14160
}
```

This caught us by surprise and seems like a mistake, since the "Error Handling" section of the API docs says:

> All errors follow general REST principles. Included in the body of any error response (e.g. non-200 status code) will be an error object of the form:

> ```
> Parameter  Value
> status     The HTTP error status returned
> error      The detailed description of the error
> ```

The spec led me to expect an `error` attribute, but instead we got a `message` attribute.

If this is intentional, perhaps this behavior at least calls for a special mention in the documentation.

**Comment by bencxr** [comment]
thank you for your report, we fixed this:
https://github.com/BitGo/BitGoJS/commit/fca24d85e798ef713b4ee26c6391c4cff6125cee

**Comment by chris-martin** [comment]
Thanks! /cc @mhluongo
