### ISSUE TITLE
Broken unit tests

### ISSUE THREAD

**Issue by kytwb** [BitGo/BitGoJS#18]
The unit tests seems to be broken due to the hardcoded `tester@bitgo.com` test user being inexistant on the test platform. Please confirm that the test password for this account is `superhardseypassphrase` and make it obvious in the documentation or README once restored. If I'm wrong, please add more instructions to the README.

I tried with my personal account on the test platform and it went fine for a while, until it reaches the tests with the hardcoded wallets and such.

**Comment by bencxr** [comment]
this is unfortunately the way the tests are designed for now.
