### ISSUE TITLE
SDK installation giving error while installing using yarn

### ISSUE THREAD

**Issue by rahulaggarwal11** [BitGo/BitGoJS#1829]
## Environment Details
* **OS:** Linux
* **Node Version:** v16.13.1
* **Yarn Version:** 1.22.15
* **BitGoJS Version:** 13.1.0
* **BitGo Environment:** testnet

## Expected Behavior
No Error

## Current Behavior
Error in native-metrics, bcrypto, sodium-native packages while installing using yarn

## Steps to Reproduce

1. Installing Bitgo npm package using `yarn add bitgo`
2. Following error is thrown:
`[4/4] Building fresh packages...
[1/24] ⡀ @newrelic/native-metrics
[9/24] ⡀ bcrypto
[21/24] ⡀ sodium-native
[20/24] ⡀ secp256k1
error /home/rahul.aggarwal/Documents/Workspace/app/demo/node_modules/@newrelic/native-metrics: Command failed.
Exit code: 1
Command: node ./lib/pre-build.js install native_metrics
Arguments: 

error /home/rahul.aggarwal/Documents/Workspace/app/demo/node_modules/bcrypto: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/rahul.aggarwal/Documents/Workspace/app/demo/node_modules/bcrypto
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.0
gyp info using node@v16.13.1 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/rahul.aggarwal/Documents/Workspace/app/demo/node_modules/bcrypto/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/rahul.aggarwal/.cache/node-gyp/v16.13.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/rahul.aggarwal/.cache/node-gyp/v16.13.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/rahul.aggarwal/.cache/node-gyp/v16.13.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/rahul.aggarwal/Documents/Workspace/app/demo/node_modules/bcrypto',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/rahul.aggarwal/Documents/Workspace/app/demo/node_modules/bcrypto/build'
  CC(target) Release/obj.target/torsion/deps/torsion/src/aead.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/asn1.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/cipher.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/drbg.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/dsa.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/ecc.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/encoding.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/entropy/env.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/entropy/hw.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/entropy/sys.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/hash.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/ies.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/internal.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/kdf.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/mac.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/mpi.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/rand.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/rsa.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/stream.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/util.o
  AR(target) Release/obj.target/torsion.a
  COPY Release/torsion.a
  CC(target) Release/obj.target/secp256k1/deps/secp256k1/contrib/lax_der_parsing.o
  CC(target) Release/obj.target/secp256k1/deps/secp256k1/src/secp256k1.o
  AR(target) Release/obj.target/secp256k1.a
  COPY Release/secp256k1.a
  CC(target) Release/obj.target/bcrypto/src/bcrypto.o
  SOLINK_MODULE(target) Release/obj.target/bcrypto.node
make: g++: Command not found
make: *** [bcrypto.target.mk:154: Release/obj.target/bcrypto.node] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.11.0-43-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rahul.aggarwal/Documents/Workspace/app/demo/node_modules/bcrypto
gyp ERR! node -v v16.13.1
`

**Comment by 0xabrarhussain** [comment]
looking at the error, 
`make: g++: Command not found`

seems like might be missing some packages from your machine. 

`sudo apt install build-essential` should solve it?

**Comment by mmcshinsky-bitgo** [comment]
Due to inactivity, this issue is marked as stale and closed. Please reach out if there are further questions.

Note that issues such as this are usually related to a local computer update. Solutions may include reinstalling Python v2.7 or fixing Python v3 paths.
