### ISSUE TITLE
can't npm install the project

### ISSUE THREAD

**Issue by ELPoupa** [BitGo/BitGoJS#1835]
OS: Ubuntu Desktop and server / debian 9 and 10

When I clone the project and I try to npm install it show me this error : https://i.ibb.co/TMhb9P6/1.png

**Comment by 0xabrarhussain** [comment]
looks like you're trying to install with npm in the root package. should instead be

In the BitGoJS/ directory:
```
$ yarn install
```

**Comment by mmcshinsky-bitgo** [comment]
Due to inactivity, this issue is marked as stale and closed. Please reach out if there are further questions.
