### ISSUE TITLE
key count must equal 3 (what does it mean)

### ISSUE THREAD

**Issue by bigup401** [BitGo/BitGoJS#1870]
Anyone ever faced this, i don't know whats the problem, even the poor bitgo api documentation never mention it

{"error":"key count must equal 3","name":"Invalid","requestId":"ckyg2yaeq2i1l073c4rauc3q0","context":{}} Bad Request

this is the path /api/v2/{coin}/wallet

Request Body schema

label   => 'WallZZZ',
    m => 2,
    n => 3,

**Comment by mmcshinsky-bitgo** [comment]
Hi @bigup401 Does the documentation found at the following link help with the actions you are attempting to make? [v2.wallet.listbycoin](https://api.bitgo.com/docs/#operation/v2.wallet.listbycoin)
