### ISSUE TITLE
The developer docs Link in the repo seems to be out of reach

### ISSUE THREAD

**Issue by byhow** [BitGo/BitGoJS#1876]
We updated the link in the `DEVELOPER.md` a while ago to replace `platform.bitgo.com` but left out the ones in the About section. Updating this will need repository edit access from the owner.

![image](https://user-images.githubusercontent.com/25713361/150194420-8b86e6cd-a36c-4fdb-ba94-fdb6e82cdc55.png)

**Comment by tylerlevine** [comment]
thanks, fixed
