### ISSUE TITLE
404 Error when attempt to create ETH wallet on testnet

### ISSUE THREAD

**Issue by Ramenky27** [BitGo/BitGoJS#207]
I try to generate wallet with this example on testnet https://github.com/BitGo/BitGoJS/blob/master/example/eth/generatewalletWithAccessToken.js

But get 404 error. Is this works on testnet?

**Comment by tylerlevine** [comment]
You are trying to create a v1 eth wallet, which is no longer supported. To create a v2 eth wallet, please follow this example (except use teth instead of tltc): https://github.com/BitGo/BitGoJS/blob/master/example/v2/create-wallet.js
