### ISSUE TITLE
Rounding error in instant fee calculation

### ISSUE THREAD

**Issue by trapp** [BitGo/BitGoJS#21]
While creating an instant transaction the following error was thrown:

    AssertionError: value has a fractional component
        at verifuint (…/node_modules/bitgo/node_modules/bitcoinjs-lib/src/bufferutils.js:9:3)
        at Object.writeUInt64LE (…/node_modules/bitgo/node_modules/bitcoinjs-lib/src/bufferutils.js:124:3)
        at writeUInt64 (…/node_modules/bitgo/node_modules/bitcoinjs-lib/src/transaction.js:293:17)
        at …/node_modules/bitgo/node_modules/bitcoinjs-lib/src/transaction.js:316:5

One of the outputs, the instant fee output, had this value: `900000.0000000001`

I tried to round the value of the output manually to `900000` and `900001` but both times the BitGo api threw this error:

    Error: instant fee incorrect, expected 900000.0000000001

Satisfying the requirement of a fractional instant fee is not possible with Satoshis, they don't have fractions.

This looks like a rounding error to me.

**Comment by bpdavenport** [comment]
Thanks -- will get right on it.

**Comment by bpdavenport** [comment]
This was a server-side fix -- it is live now.

**Comment by trapp** [comment]
Thanks for the quick fix.
