### ISSUE TITLE
How use Bitgo sdk in window.

### ISSUE THREAD

**Issue by vnxz** [BitGo/BitGoJS#2209]
I want to use bitgo sdk in window ,
I make laravel project that integrate coin payment gateway.
Need to use bitgo.
how install bitgo into project.

**Comment by mmcshinsky-bitgo** [comment]
Thanks @vnxz for reaching out. Can you expand upon using the "sdk in window"? Are you looking to use the SDK on the frontend, backend, or both (reference to Laravel)?

If you are using it on the backend, Laravel being written in Node supports installing `bitgo` as an npm package. The installation docs if you are looking for the `bitgo` package directly can be found in `modules/bitgo/README.md`.
