### ISSUE TITLE
BitGoJS under heroku

### ISSUE THREAD

**Issue by cenkozan** [BitGo/BitGoJS#229]
Hi, 

I am trying to use your SDK for my application hosted on Heroku. In order to create an auth token, I need to give an IP address on the BitGo dashboard - but heroku doesn't give me one. I have checked static IP 3rd parties found on Heroku marketplace, and nearly all options seem highly costly. 
The cheapest option is letting me create an 'Inbound Proxy'.
My question is this: if I set this up, will my application hosted on heroku then be authorised to use BitGo SDK? Or even this wouldn't be enough?

Thank you in advance.

**Comment by tylerlevine** [comment]
As long as your last hop to bitgo is using the same IP all the time, it should work. It doesn't look like the inbound proxy feature is what you are looking for though (that will allow your app to be accessed via a static IP, but does not appear to make your outbound request use a static IP).

This looks more like what you would need: https://elements.heroku.com/addons/quotaguardstatic

**Comment by cenkozan** [comment]
Thank you very much for answering Tyler. I have tried outgoing proxy and SDK gave me this error:

Error: Attempt to use IP-restricted token from an unauthorized IP address

That was why I asked if I need an inbound proxy - do you think I am running into another issue here?

**Comment by tylerlevine** [comment]
Have you configured your access token with the egress IP of your outgoing proxy?

**Comment by cenkozan** [comment]
I don't know what you mean by that but I will check first thing Monday. Thank you and have a nice weekend.

**Comment by tylerlevine** [comment]
You may be better off contacting support@bitgo.com for this. They can look up your wallet and tell you what IPs you are accessing bitgo from, and what IPs are whitelisted on your token. I would rather not discuss these specifics in public. Have a great weekend!

**Comment by cenkozan** [comment]
Hi, 
I have seen that I need to make my requests to outside through that proxy for the above 3rd party solution to work. 

Can I use the SDK behind a proxy too, Tyler? Or am I limited to using the self-hosted Express REST API solution that BitGo offers? I have seen in the documentation that Express REST API will work behind a proxy - but I am not sure about the SDK.

Thank you for your answer in advance.

**Comment by cenkozan** [comment]
Couldn't run both the SDK and the Express REST API behind proxy. If anyone googles this, I would advise not to try and waste time like me :P

**Comment by tylerlevine** [comment]
For anyone else stumbling upon this: You can have the SDK use a HTTP, HTTPS, or SOCKS proxy by passing `proxy: <url>` in the params object when you construct a new bitgo object, or by setting the `BITGO_USE_PROXY` environment variable.

**Comment by wbobeirne** [comment]
Also to provide a little more help with those looking specifically for a Heroku fix for this, building off of @tylerlevine's advice, this can be taken care really easily of by adding the [Fixie addon](https://elements.heroku.com/addons/fixie), and changing your `BitGo` instantiation to:
```ts
new bitgo = new BitGo({
  // ...
  proxy: process.env.FIXIE_URL,
});
```
Just be wary of their request limits and pricing! I think [Proximo](https://elements.heroku.com/addons/proximo) and [QuotaGuard](https://elements.heroku.com/addons/quotaguardstatic) are also viable alternatives using the same technique.
