### ISSUE TITLE
BitGo Requires Additional Modules - NextJS

### ISSUE THREAD

**Issue by moza88** [BitGo/BitGoJS#2317]
When I use BitGo in NextJS projects I get an error that requires me to install multiple dependencies. I tried installing each dependency individually but when I got to fs it kept asking me to install the same fs dependency.

Below is the error produced:
```
error - ./node_modules/@grpc/grpc-js/build/src/tls-helpers.js:20:0
Module not found: Can't resolve 'fs'

Import trace for requested module:
./node_modules/@grpc/grpc-js/build/src/channel-credentials.js
./node_modules/@grpc/grpc-js/build/src/index.js
./node_modules/@hashgraph/sdk/lib/channel/NodeChannel.cjs
./node_modules/@hashgraph/sdk/lib/client/NodeClient.cjs
./node_modules/@hashgraph/sdk/lib/index.cjs
./node_modules/@bitgo/account-lib/dist/src/coin/hbar/utils.js
./node_modules/@bitgo/account-lib/dist/src/utils/crypto.js
./node_modules/@bitgo/account-lib/dist/src/coin/sol/utils.js
./node_modules/@bitgo/account-lib/dist/src/coin/sol/index.js
./node_modules/bitgo/dist/src/v2/coins/sol.js
./node_modules/bitgo/dist/src/v2/coins/index.js
./node_modules/bitgo/dist/src/v2/coinFactory.js
./node_modules/bitgo/dist/src/index.js
./pages/profile.js
```

## Environment Details
* **OS:** Mac Intel 11.5.1
* **Node Version:** v16.15.0
* **Yarn Version:** v1.22.17
* **BitGoJS Version:** ^14.1.0
* **BitGo Environment:** N/A

## Expected Behavior
NextJS project should build successfully

## Current Behavior
The project should build successful and all the dependencies should come in when I add in BitGo into my package.json file.

## Possible Solution
I am stuck

## Steps to Reproduce
1. Create a NextJS project `npx create-next-app testapp`
2. Install BitGo to the project `yarn install bitgo`
3.  Open up the index.js file and add the following lines above Home

```
const BitGo = require('bitgo');
const bitgo = new BitGo.BitGo({accessToken: b9.................81af4256797}); // defaults to testnet. add env: 'prod' if you want to go against mainnet
const result = await bitgo.session();
console.dir(result);

export default async function Home() {

  return (
           ....
```
<img width="570" alt="image" src="https://user-images.githubusercontent.com/5752954/170810959-43aece8c-b139-4b35-b5b6-4f59303bf68b.png">

**Comment by mmcshinsky-bitgo** [comment]
Hi @moza88. Go ahead and check out the usage of webpack for frontend [here](https://github.com/BitGo/BitGoJS/tree/master/modules/web-demo). You may also want to revoke your now exposed access token in the example above and generate a new one.

**Comment by moza88** [comment]
@mmcshinsky-bitgo Thank you, I can't believe I did that! It's revoked now.

**Comment by moza88** [comment]
It wasn't working because BitGo is not compatible with React 18. This can only be run on the server-side and is a common issue with many projects that running in the newer frameworks across the board.
[](https://maikelveen.com/blog/how-to-solve-module-not-found-cant-resolve-fs-in-nextjs
)

Web demo is alright but ideally it would be nice to see a simple boilerplate with react and express since these are the frameworks most people get.

**Comment by mmcshinsky-bitgo** [comment]
BitGoJS as an SDK is frontend framework agnostic. There are some coin libraries that it makes use of that use Node functionality. For this reason in the `web-demo` example, the webpack configurations are implemented to overcome the limitations between Node and Browser APIs.

We have in the pipeline some pull requests and release candidate versions that you can see publicly which will allow users to highly reduce both the package size and potential needs for webpack configurations depending on the coins you wish to make use of.

**Comment by moza88** [comment]
That's good to know, what webpack configuration do I have to do on my react js app to make BitGo SDK? The web-demo is good but I am not very familiar with Cypress.

**Comment by mmcshinsky-bitgo** [comment]
You should be able to refer to this [folder](https://github.com/BitGo/BitGoJS/tree/master/modules/web-demo/webpack) for all the webpack configuration options.

**Comment by moza88** [comment]
I was able to skip all of that by just creating app on nestJS, it handles a lot of that webpack config which is a pain.

**Comment by mmcshinsky-bitgo** [comment]
I've gone ahead and created a nextjs example based on the `web-demo`. Hopefully this helps! https://github.com/mmcshinsky-bitgo/bitgojs-example-nextjs
