### ISSUE TITLE
(node:34003) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'

### ISSUE THREAD

**Issue by olalonde** [BitGo/BitGoJS#25]
CLI commands give the following warning in Node v6:

```
(node:34003) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
```

**Comment by TungDiamond** [comment]
I'm very Sorry For lately comment

**Comment by jlopp** [comment]
I believe this has been fixed for a while, please re-open if you're still experiencing this issue.
