### ISSUE TITLE
How update address label ? 

### ISSUE THREAD

**Issue by mateuszk77** [BitGo/BitGoJS#256]
Hello. I have a problem with update label in receive address. I write app in nodeJS.
Here is example, but I can't see example in nodeJS. 
https://www.bitgo.com/api/v2/#operation/v2.wallet.singlewalletaddress

So, how can I upgrade address label in nodeJS ?

**Comment by tylerlevine** [comment]
Hello @mateuszk77,

You can upgrade the address like this:
```js
wallet.updateAddress({ address: 'youraddresshere', label: 'my new label' });
```
