### ISSUE TITLE
Encrypt/Decrypt not setting the sjcl salt option

### ISSUE THREAD

**Issue by jmendiola222** [BitGo/BitGoJS#27]
We used the `Bitgo.encrypt` method in our system, and notice that many encrypted data had the same salt assigned. When we took a look at this method we notice no salt param is set to `sjcl.encrypt`. Seems like this lib internally reuses the salts. ( bitgo@0.11.56 Bitgo.js line 303 )
```javascript
BitGo.prototype.encrypt = function(params) {
  params = params || {};
  common.validateParams(params, ['input', 'password'], []);
  var encryptOptions = { iter: 10000, ks: 256 };
  return sjcl.encrypt(params.password, params.input, encryptOptions);
};
```
The recommended way to use sjcl is to use a generated salt like:
```javascript
const salt = sjcl.random.randomWords('10','0')
sjcl.encrypt(backend.SIGNATURE , text, { iter:10000,ks:256,"salt": salt });
```

**Comment by bencxr** [comment]
thanks for the tip, we'll look into doing this. 

right now, sjcl already randomizes the salt depending on the password used, and only reuses the salt if the same password is used within the same session. however we don't actually encrypt many different secrets (just the user key) so this is not typically going to be a issue.

**Comment by bencxr** [comment]
thank you for the report, fixed in https://github.com/BitGo/BitGoJS/commit/bf305bdb97d00b26ea61fb9554bf4d35e40d45f7
