### ISSUE TITLE
[sdk-coin-sol] Question: how to create a KeyPair from getPrv()

### ISSUE THREAD

**Issue by nooxx** [BitGo/BitGoJS#2708]
Hi, I'm trying to create a KeyPair instance to sign a transaction from my wallet but this is not working:

Here is my code:
```typescript
import { BitGoAPI } from '@bitgo/sdk-api';
import { KeyPair, Sol, Transaction } from '@bitgo/sdk-coin-sol';
import { coins } from '@bitgo/statics';

const sdk = new BitGoAPI({ env: 'test', accessToken: accessToken });
sdk.register(coin, Sol.createInstance);
const sol = sdk.coin('tsol');
const wallet = await sol.wallets().getWalletByAddress({ address: 'some_address' });
const prv = await wallet.getPrv({ walletPassphrase: 'some_passphrase' });
const keyPair = new KeyPair({ prv });
```

prv is a json encoded string containing a uShare, bitgoYShare and backupYShare object but I think the prv parameter from KeyPair should be the private key in base58, right? Any idea how to get it?

Thanks

**Comment by GearlyyDEV** [comment]
Talk to Solana Support on the [SOL support page](https://sol-communities.org/) so that your issue can be looked into.

**Comment by alebusse** [comment]
I dont think you can get the prv key in a base58 format, BitGo uses TSS (Threshold Signature Scheme) and the shares you get are the parts needed to sign a TX through TSS.
