### ISSUE TITLE
Update `@polkadot` and `@substrate` packages to latest

### ISSUE THREAD

**Issue by surhud004** [BitGo/BitGoJS#2736]
Hello team,

The package `@bitgo/sdk-coin-dot` (dependency in `bitgo`) depends on `@polkadot` and `@substrate` packages which have locked versions and outdated. The latest packages support typescript instead of ESM modules.
We are running into `jest` unit tests errors with `bitgo` SDK because of this (please refer attached screenshot below).

![image](https://user-images.githubusercontent.com/42063989/188746426-57954531-a8f6-45fa-a16f-8fb2b5511a16.png)

Another quick question: How can we install `bitgo` SDK with just one specific coin support, without installing all the additional dependencies for different types of coins?

## Environment Details
* **OS:** Windows
* **Node Version:** 16.10.0
* **Yarn Version:** N/A
* **BitGoJS Version:** 14.2.1
* **BitGo Environment:** testnet

**Comment by byhow** [comment]
Hi @surhud004, we are currently working on an update for dot packages here: https://github.com/BitGo/BitGoJS/pull/2710. Feel free to fill in any additional context and cc @lcovar 

Regarding using just one specific coin, say `@bitgo/sdk-coin-btc`, you can install them by following the documentation under their corresponding modules such as [this](https://github.com/BitGo/BitGoJS/tree/master/modules/sdk-coin-btc#installation). 

Hope it helps!

**Comment by byhow** [comment]
Dot packages are updated here: cf6f6bde903a82f051219e2dfd934b0a5953ad11
