### ISSUE TITLE
Simulate webhook - txHash must not be empty

### ISSUE THREAD

**Issue by mateuszk77** [BitGo/BitGoJS#278]
Hello. I wanted simulate my created webhook. But I got error like this : 
 Unhandled rejection Error: txHash must not be empty
What I doing wrong ?

**Comment by tylerlevine** [comment]
You should be using a transfer webhook for this instead of a transaction webhook. Transaction webhooks are not generalized across all coins in our platform, and will be removed in the future.

**Comment by mateuszk77** [comment]
Ok. I used transfer webhook too. But I get empty array on the server side. 
I have my adress : http://mydomain.com/webhook.php and type : transfer. 
I simulate webhook : 
`wallet.simulateWebhook({
                webhookId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                transferId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx''
            })
                .then(function (result) {
                    console.dir(result);
                });`

But when I receive this on the server, I get empty array

**Comment by uncle-scooter** [comment]
Why don't you log the results of a successful webhook then use that as mock data for testing?
