### ISSUE TITLE
Vulnerabilities on BitGo Express latest docker image

### ISSUE THREAD

**Issue by lfojacintho** [BitGo/BitGoJS#2786]
After a static code analysis with Snyk, it was detected that the latest version of BitGo Express docker image contains 6 known vulnerabilities, all related to the base image of Node / Alpine 3.15.

Please check the attached report for details on the vulnerabilities.

[Snyk test report.pdf](https://github.com/BitGo/BitGoJS/files/9607694/Snyk.test.report.pdf)

## Possible Solution
Upgrade the base image of Node / Alpine to the latest version, where no vulnerabilities are known as of today.

**Comment by lfojacintho** [comment]
Thanks @mmcshinsky-bitgo 
The build is green, could you please approve and merge it?

**Comment by mmcshinsky-bitgo** [comment]
@lfojacintho You'll need to sign the commits before it can be merged. Then we'll be good to go.

**Comment by lfojacintho** [comment]
Hey @mmcshinsky-bitgo, thanks a lot.
I have rebased my branch with the latest version of master and signed the commit.

I think everything is good now, could you please run the pipeline again? If everything is good, could you please merge it? Or shall I merge it?

**Comment by mmcshinsky-bitgo** [comment]
Changes now merged. We will have `stable` releases coming up next for BitGoJS and Express Docker images.

**Comment by lfojacintho** [comment]
Thanks a lot @mmcshinsky-bitgo
