### ISSUE TITLE
built files for `cdnjs`

### ISSUE THREAD

**Issue by maruilian11** [BitGo/BitGoJS#28]
hi, recently we want to add your lib to https://cdnjs.com, could you please consider creating a build folder with built files so that we can grab the files with **git auto-update** or **npm auto-update**.
thank you very much!

https://github.com/cdnjs/cdnjs/pull/7145
https://github.com/cdnjs/cdnjs/issues/6109

**Comment by mbelshe** [comment]
Thanks for the consideration.  I'm concerned about serving crypto libraries from a CDN for security reasons and would generally vote that we not do this.

**Comment by maruilian11** [comment]
ok, thanks.

**Comment by PeterDaveHello** [comment]
@mbelshe what about serving on cdn with SRI(Subresource Integrity)[1](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)[2](https://www.w3.org/TR/SRI/)? CDNJS is going to support this feature.

**Comment by mbelshe** [comment]
Great suggestion.  Concerned about lack of IE and Safari support yet for Subresource Integrity tho.

**Comment by PeterDaveHello** [comment]
We still have DNSSEC and TLS to help defense the attects, isn't it valuable to host this lib?

**Comment by maruilian11** [comment]
ping @mbelshe thanks!

**Comment by PeterDaveHello** [comment]
The news is that we started to support that for a while.
