### ISSUE TITLE
v4.49.1 not published to npm

### ISSUE THREAD

**Issue by jaydenseric** [BitGo/BitGoJS#293]
[v4.49.1](https://github.com/BitGo/BitGoJS/releases/tag/4.49.1) has been released, but not published to npm:

```sh
$ npm view bitgo versions
```

<img width="84" alt="Screen Shot 2019-04-02 at 12 14 16 pm" src="https://user-images.githubusercontent.com/1754873/55369104-de752d80-5540-11e9-8ea8-bb0b13a99e7e.png">

**Comment by christiansaiki** [comment]
How can we release ASAP guys? 
Our CI flow is compromised due to the post install failures.

**Comment by tylerlevine** [comment]
We will be releasing 4.49.1 within the next few hours.

**Comment by tylerlevine** [comment]
4.49.1 has been released to npm: https://www.npmjs.com/package/bitgo

Please comment here if you are continuing to see build failures
