### ISSUE TITLE
connection pool support

### ISSUE THREAD

**Issue by zhangw** [BitGo/BitGoJS#2943]
I hopes the connection pool should be implemented and used  during requesting the bitgo apis.
Considering the underly tcp connection along with the TLS handshake been doing again and again per request, it should be optimized for the performance and latency.

**Comment by mmcshinsky-bitgo** [comment]
Hi @zhangw, thanks for the input. The SDK and the express module do not make use of database connections directly in order to create and manage pool connections. The SDK makes sure of the existing API layers in order to send and receive data from BitGo resources.

**Comment by mmcshinsky-bitgo** [comment]
This feature would be out of scope of this repository. Thanks for the input!
