### ISSUE TITLE
Importing @bitgo/utxo-lib causes React app jest unit tests to fail

### ISSUE THREAD

**Issue by BytesOfMan** [BitGo/BitGoJS#3148]
## Environment Details
* **OS:** Pop!_OS 22.04 LTS
* **Node Version:** v16.14.2
* **Yarn Version:** N/A, npm 8.5.0
* **BitGoJS Version:** @bitgo/utxo-lib 7.2.0
* **BitGo Environment:** mainnet

## Expected Behavior
I'm looking to implement `@bitgo/utxo-lib` in an eCash web wallet that has been running on `bitcoincashjs-lib`. Unit testing is done with the `jest` library. `npm test` should run and pass all unit tests. This happens in the latest version on the `master` branch at https://github.com/Bitcoin-ABC/bitcoin-abc/

## Current Behavior
`jest` throws an error and will not run test files that reference any files with `import * as utxolib from '@bitgo/utxo-lib';` in them. Here's the error:

```
● Test suite failed to run

    ecc library invalid

      10 | import bs58 from 'bs58';
      11 | import * as slpMdm from 'slp-mdm';
    > 12 | import * as utxolib from '@bitgo/utxo-lib';
```

## Possible Solution
It looks like the ECPairFactory ` testecc_1.testEcc` is being called on import in the jest environment and failing, potentially because there is some error with it running in the jest environment. It seems like the kind of thing that might have a known patch or shim, but I wasn't able to find one in past issues.

## Steps to Reproduce
The exact code that reproduces this bug is available here: https://reviews.bitcoinabc.org/D12939

The code at this diff can be pulled down by following the instructions here to clone the monorepo: https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/CONTRIBUTING.md

then, `arc patch D12939`
```
cd web/cashtab
npm ci
npm test
```
Will produce the above error

**Comment by Mustafa-Agha** [comment]
@BytesOfMan using utxo-lib on expo/react-native crashes application on ios devices only, but it works fine on android and web

For some reason when I used webpack 4 there are no crashes on ios, but once I upgraded the webpack to 5 the crash happens.

Can you help me solve this problem?
