### ISSUE TITLE
secp256k1 errors during npm installation

### ISSUE THREAD

**Issue by tomtruitt** [BitGo/BitGoJS#32]
going to remove from package as suggested but this is prevents the build from completing as is and also means i have to clone this repo which is a step currently in the installation guide

**Comment by tomtruitt** [comment]
![image](https://cloud.githubusercontent.com/assets/10718256/20246965/d8c39a16-a98f-11e6-9efe-95b60d311e03.png)
build still fails

**Comment by Melvillian** [comment]
@tomtruitt Can you please post/attach your npm-debug.log file?

**Comment by tomtruitt** [comment]
sure. do you want the whole thing or just this part?
![image](https://cloud.githubusercontent.com/assets/10718256/20247477/4d31bd82-a99b-11e6-9778-702bed6056d8.png)

**Comment by jlopp** [comment]
@tomtruitt Does it still fail if you take a fresh checkout of the code and build it with `npm install --no-optional` ?

**Comment by tomtruitt** [comment]
I should be able to check on this tomorrow thanks


Tom Truitt
Liberty Vending, LLC

 
This electronic mail message contains information that (a) is or may be LEGALLY PRIVILEGED, CONFIDENTIAL, PROPRIETARY IN NATURE, OR OTHERWISE PROTECTED BY LAW FROM DISCLOSURE, and (b) is intended only for the use of the Addressee(s) named herein. If you are not the intended recipient, addressee, or the person responsible for delivering this to an addressee, you are hereby notified that reading, using, copying, or distributing any part of this message is strictly prohibited. If you have received this electronic mail message in error, please contact us immediately and take the steps necessary to delete the message completely from your computer system.

-------- Original message --------From: Jameson Lopp <notifications@github.com> Date: 12/5/16  5:35 PM  (GMT-05:00) To: BitGo/BitGoJS <BitGoJS@noreply.github.com> Cc: Tom Truitt <tom@coinkit.io>, Mention <mention@noreply.github.com> Subject: Re: [BitGo/BitGoJS] secp256k1 errors during npm installation (#32) 
@tomtruitt Does it still fail if you take a fresh checkout of the code and build it with npm install --no-optional ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BitGo/BitGoJS","title":"BitGo/BitGoJS","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BitGo/BitGoJS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jlopp in #32: @tomtruitt Does it still fail if you take a fresh checkout of the code and build it with `npm install --no-optional` ?"}],"action":{"name":"View Issue","url":"https://github.com/BitGo/BitGoJS/issues/32#issuecomment-265000205"}}}

**Comment by fanatid** [comment]
@tomtruitt #33 should solve you problem
even if `secp256k1` will not be compiled, pure js implementation will be used, don't worry about it..

**Comment by tomtruitt** [comment]
Interesting I'll take a look I busted up my laptop can't get out of initramfs so I can't do much right now

**Comment by mrose17** [comment]
@Melvillian - may i request that `package.json` be updated to use version 3.2.5 of secp256k1? that may clear up the issues. thanks!

**Comment by fanatid** [comment]
just for info, secp256k1@3.2.5 has prebuild binaries

**Comment by jlopp** [comment]
Updated to 3.2.5; please report in and let us know if this resolves the problem.

**Comment by fanatid** [comment]
build issues also related with sha3 library, but this package is not used is this project
PR: https://github.com/BitGo/BitGoJS/pull/33

**Comment by mrose17** [comment]
will do, any thanks!

**Comment by LeoKotschenreuther** [comment]
It has been over 18 months since the last comment here. I will close the ticket for now assuming that this has been resolved.

Please reopen or create a new Issue if this is still a problem.

**Comment by CriptoGirl** [comment]
I am getting multiple errors when running following on Windows 10: 
 npm install secp256k1
