### ISSUE TITLE
Add changelog entries for recent releases

### ISSUE THREAD

**Issue by jaydenseric** [BitGo/BitGoJS#322]
None of the GitHub releases have descriptions:

https://github.com/BitGo/BitGoJS/releases

And the last 10 releases have not been documented in [`RELEASE_NOTES.md`](https://github.com/BitGo/BitGoJS/blob/master/RELEASE_NOTES.md).

**Comment by evancrose** [comment]
Echo the sentiment above. It is very difficult to understand when the SDK needs to be upgraded for what could possibly be breaking changes, or impact to production environments. It would be very helpful to see a changelog to run a proper cost/benefit on upgrading.

**Comment by tylerlevine** [comment]
Thanks for the heads up. We typically update the release notes within 48 hours of release, but are a little slower this time around.

I will create a PR to update the release notes for the following versions later today:
* `4.49.1`, `4.49.2`
* `5.0.1`, `5.0.2`, `5.0.3`, `5.0.4`

**Comment by tylerlevine** [comment]
I've opened https://github.com/BitGo/BitGoJS/pull/324 for the release notes update.

That will get merged to master soon, but it should give you the info you are looking for in the meantime. If you have any other questions, please let me know.

@jaydenseric Instead of adding descriptions to the releases page, I'd rather have all the release notes in the repo instead. I don't have access to edit the descriptions for the releases.

**Comment by tylerlevine** [comment]
#324 was just merged.

**Comment by jaydenseric** [comment]
Thanks for the update :)

> Instead of adding descriptions to the releases page, I'd rather have all the release notes in the repo instead.

The changelog definitely should be versioned, yes. Best practice is to also copy the changelog entries into the GitHub release descriptions:

1. It gets tiring having to try to hunt down release notes in different places in a lot of repos when updating dependencies, it is always a relief when the GitHub release has all the info.
2. When people watch the repo for releases, it is a much better experience when the release notification email has details about the release instead of being blank. Here is an example with Next.js:

   <img width="514" alt="Screen Shot 2019-04-18 at 9 29 53 am" src="https://user-images.githubusercontent.com/1754873/56327210-c21df580-61bc-11e9-985b-16d84c00b61e.png">
