### ISSUE TITLE
npm install reverts to 4.49.2

### ISSUE THREAD

**Issue by evancrose** [BitGo/BitGoJS#323]
Hello,

I've been having issues intermittently receiving 502 gateway errors on sendcoins calls resulting in coins being sent but without any txid being returned. I went to upgrade the SDK using npm install and I see now that it installed 4.49.2 instead of the v5 tip. Just trying to understand the background and if I should override npm and manually install v5. I checked npm and 4.49.2 is now listed as latest version as of 15 hours ago.

Thank you,

Evan

**Comment by tylerlevine** [comment]
Looks like 4.49.2 was published after 5.0.4, so it became `latest` instead of 5.0.4. We'll fix the tags shortly.

`bitgo@5.0.4` is currently the latest version.

**Comment by tylerlevine** [comment]
@evancrose The `latest` tag on npm has been reset to `5.0.4` now. Please let us know if you are still getting an old version when running with `npm install bitgo`.
