### ISSUE TITLE
Can't create a withdrawal request

### ISSUE THREAD

**Issue by anduonghien** [BitGo/BitGoJS#330]
Hi, I've created a new Wallet on Bitgo UI and I'm not able to create a Withdrawal request through Bitgo express 

Here is the response message

```
{"error":"wallet address 2N6xpce5humkZkXnBWta9KptFZrBdiwPotA not found","name":"NotFound","requestId":"b779c4dadd8c2949e31a-0007","message":"wallet address 2N6xpce5humkZkXnBWta9KptFZrBdiwPotA not found"}
```

I tried with my previous Wallet credentials (the old I created 6 months ago), it works normally.

I think there is something wrong with the new Wallet, even I tried to create another new Wallet it also doesn't work.

Is there anyone face this issue?

**Comment by Xekyo** [comment]
@anduonghien: Thanks for reaching out, we have a fix in review that should be deployed to the test infrastructure shortly.

**Comment by dannybitgo** [comment]
Yes, apologies for this. This was my fault. The root cause was a breaking change in our platform code that is being reverted right now. There won't be any changes necessary to BitGoJs. We're planning to get the platform change reverted asap and will notify you when its done

**Comment by tylerlevine** [comment]
@anduonghien, this issue should be resolved now. Please let us know if you're still having trouble sending transactions.

**Comment by anduonghien** [comment]
@Xekyo @dannybitgo @tylerlevine Confirmed it works now, thanks 👍 👍 👍
