### ISSUE TITLE
Cannot find module 'ethereumjs-util

### ISSUE THREAD

**Issue by jayrulez** [BitGo/BitGoJS#339]
Installing bitgo and trying to call some erc20 token endpoints results in the error:
http://localhost:3080/api/v2/tusdc/tx/fee
```
{
    "error": "Cannot find module 'ethereumjs-util'",
    "message": "Cannot find module 'ethereumjs-util'"
}
```

**Comment by jayrulez** [comment]
It seems it should be looking for 'ethjs-util' instead.

**Comment by tylerlevine** [comment]
How did you install bitgo-express? Did you get any errors on install?

[`ethereumjs-util`](https://www.npmjs.com/package/ethereumjs-util) is the correct name of the package.

**Comment by jayrulez** [comment]
I did ```npm install -g bitgo```

![image](https://user-images.githubusercontent.com/78807/57040702-d97dc980-6c25-11e9-89bf-59b8f379ea2a.png)

the name of the dir in the node_modules dir is ethjs-util

**Comment by tylerlevine** [comment]
Could you post the complete output from the `npm install -g bitgo` command?
