### ISSUE TITLE
Webhook notification should identify the payee

### ISSUE THREAD

**Issue by singhvijayy** [BitGo/BitGoJS#34]
This is a sample webhook notification on bitcoin sending confirmation - 
```
{ hash: 'some_random_hash',
  type: 'transaction',
  coin: 'bitcoin',
  walletId: 'some_wallet_id' }

```

Lets say I have 10 users on my website, sending me bitcoins at around the same time (at different addresses) in the same wallet, then there should be a way for me to figure which user's notification I have received on my webhook. Currently, I do not see any `address` field (related to the wallet, at which the user had sent his bitcoins) in the webhook notification json, which, if present, will solve the matter!

(a suggestion based on my preference - a callback will be much easier to implement (for developers choosing BitGo as their bitcoin API) than a webhook, as the question of payee identification will not arise in case of a callback. Besides, a webhook also requires ngrok or something similar to test on localhost, bitcoin APIs should not be so difficult to test and implement)

**Comment by bpdavenport** [comment]
Webhooks are not intended to contain all information about the transaction
(for one thing, that would be insecure, since anyone could discover your
URL and call you with a fake webhook). The pattern you should follow is to
look up the tx using the BitGo API once you get a webhook call.

**Comment by singhvijayy** [comment]
Ok, that was not clear in the docs. Thanks for your reply.
