### ISSUE TITLE
Issues with TRX wallet consolidation and transactions signing

### ISSUE THREAD

**Issue by cryptobulker** [BitGo/BitGoJS#3418]
I'm having trouble with TRX transactions; I can make consolidation for some addresses, which appears to be difficult, but I can't send the half-signed transaction to the Bitgo server for finalization.

:: I have sent mail severally for this and it's been more than a week without a solution and no solid assistance from the team

I keep getting these kinds of errors when trying to perform the /send as instructed [here](https://developers.bitgo.com/api/v2.wallet.tx.send):

**{"error":"Unable to parse transaction hex. Please ensure that all of your transaction inputs are correct.","name":"Invalid","requestId":"clfvqkszm50e0085kdi0r63af","context":{}}**
and 
**{"error":"server error requestId=clfvr6l4v51pp0745810kbr4d","name":"Error","requestId":"clfvr6l4v51pp0745810kbr4d","context":{}}**

Please don't mind my writeups and attitude, I am running a crypto wallet app and the funds are needed daily by my users which seem to be stuck in the process.

Thank you

**Comment by margueriteblair** [comment]
Hi, just writing to confirm that this issue can be closed after the following steps were taken to remedy:
Using the endpoint `/api/v2/:coin/wallet/:id/consolidateAccount`. 

And using the API similar to the following to do the consolidation:

```javascript
const request = require('superagent');
async function main() {
  const expressUrl = 'http://localhost:3080';
  const walletId = 'walletId';
  const accessToken = 'accessToken';
  const payload = {
    walletPassphrase: 'passphrase',
    opt: 'otp',
  };
  const res = await request
    .post(expressUrl + '/api/v2/trx/wallet/' + walletId + '/consolidateAccount')
    .set('Authorization', `Bearer ${accessToken}`)
    .send(payload);
  console.log(res.body);
}
main().catch((e) => console.error(e));
```

Please note that the user also had to update to the latest version of BitGoJS. Newest releases can be found here fo [BitGo express docker](https://hub.docker.com/r/bitgosdk/express/tags) and for [BitGoJS SDK](https://github.com/BitGo/BitGoJS/tags).
