### ISSUE TITLE
error UnsupportedCoinError: Coin or token type BTC not supported or not compiled. Please be sure that you are using the latest version of BitGoJS. If using @bitgo/sdk-api, please confirm you have registered BTC first.     at CoinFactory.getInstance (c:\Program Files\nodejs\Bitgo-Custodial-Wallet-API\node_modules\@bitgo\sdk-core\dist\src\bitgo\coinFactory.js:51:15)     at BitGo.coin (c:\Program Files\nodejs\Bitgo-Custodial-Wallet-API\node_modules\bitgo\dist\src\bitgo.js:35:38)

### ISSUE THREAD

**Issue by bherdeshamal** [BitGo/BitGoJS#3466]
## Environment Details
* **OS:** 
* **Node Version:** 
* **Yarn Version:** 
* **BitGoJS Version:** 
* **BitGo Environment:** 

## Steps to Reproduce

1.
2.
3.

**Comment by mmcshinsky-bitgo** [comment]
Are you able to share the code you have implemented. It looks like you haven't registered the coin you would like to use when using `@bitgo/sdk-api`.

See: [https://github.com/BitGo/BitGoJS/tree/master/modules/sdk-coin-btc](https://github.com/BitGo/BitGoJS/tree/master/modules/sdk-coin-btc)

**Comment by mmcshinsky-bitgo** [comment]
Hopefully the issue has been resolved. I'll go ahead and close this due to lack of activity.
