### ISSUE TITLE
Query total spending fee of a wallet

### ISSUE THREAD

**Issue by anduonghien** [BitGo/BitGoJS#347]
Hi there 👋 

Can we get the total spending fee of a Bitgo wallet through Bitgo REST API? 🤔 

If not is there any way to get the total spending fee for a Bitgo wallet or I have to store each transaction fee by myself (on my app) 🤔 

Thank you 👍 👍 👍

**Comment by tylerlevine** [comment]
Hi @anduonghien, thanks for opening an issue. However, this question is about a feature of the BitGo platform, and not an issue with the BitGo SDK itself. Please send an email to support@bitgo.com, and they will be happy to help you out :)
