### ISSUE TITLE
2FA with email link

### ISSUE THREAD

**Issue by singhvijayy** [BitGo/BitGoJS#35]
Currently, BitGo requires its users to either download Google Authenticator App or buy a Yubikey for 2FA, while creating an account. 

Why does BitGo not give an option for an email based 2FA?

(Email based 2FA - a link is sent to the email on every login, which when clicked, authorizes the login, like in case of blockchain.info wallets)

**Comment by bpdavenport** [comment]
We don't consider it to be sufficiently secure.
