### ISSUE TITLE
Wallets that were created using the generate Wallet method are not displayed in UI

### ISSUE THREAD

**Issue by arg2u** [BitGo/BitGoJS#3569]
Wallets that were created using the generate Wallet method are not displayed in UI

## Environment Details
* **OS:** MacOS
* **Node Version:** 16.20
* **Yarn Version:** 1.22.19
* **BitGoJS Version:** 18.3.0
* **BitGo Environment:** testnet/prod

## Expected Behavior
After calling "generateWallet," a new wallet will be created and displayed in the UI of my private area.

## Current Behavior
I've used JS SDK to create hot wallets via the generateWallet method. When I called it, a new wallet was created and displayed if I requested a list. But there is no such wallet in the UI.

## Steps to Reproduce

1. Call generateWallet method from the SDK
2. Go to the private area UI.

**Comment by margueriteblair** [comment]
Could you please share the params you passed into `generateWallet()` method?

**Comment by margueriteblair** [comment]
Can you try passing in an additional param for your enterprise id? Like:
```javascript
      label: "TBTC - TEST",
      enterprise: <YOUR_ENTERPRISE_ID>,
      passphrase: 'mypass',
```
and see if it populates properly in UI then?

**Comment by arg2u** [comment]
> Can you try passing in an additional param for your enterprise id? Like:
> 
> ```js
> params = {
>       label: "TBTC - TEST",
>       enterprise: <YOUR_ENTERPRISE_ID>,
>       passphrase: 'mypass',
> }
> ```
> 
> and see if it populates properly in UI then?

Works like a charm. You're the best. Thank you.

I think it will be great to add some words about this tip to the documentation.
