### ISSUE TITLE
Error depending 

### ISSUE THREAD

**Issue by d-lukutin** [BitGo/BitGoJS#3878]
## Environment Details

- **OS:** Ubuntu
- **Node Version:** 16.20.2
- **Yarn Version:** 1.22.19
- **BitGoJS Version:** 19.13.0
- **BitGo Environment:** -

## Expected Behavior

The library is working

## Current Behavior

The library is not working

## Possible Solution

Fix the dependency @bitgo/sdk-lib-mpc v8.8.0

## Steps to Reproduce

The file "node_modules/@bitgo/sdk-lib-mpc/dist/src/tss/ecdsa/index.js" can't find the dependencies "rangeproof" and "paillierproof". Due to a case mismatch. NPM currently only has rangeProof.js and paillierProof.js
![Снимок экрана от 2023-09-03 00-34-33](https://github.com/BitGo/BitGoJS/assets/101016650/e0f0620b-b2b0-4810-a097-a54d345d712f)
![Снимок экрана от 2023-09-03 01-05-24](https://github.com/BitGo/BitGoJS/assets/101016650/61c17a05-25d2-439c-b7c5-4361eb4ec008)

Version 8.7.0

![Снимок экрана от 2023-09-03 00-33-46](https://github.com/BitGo/BitGoJS/assets/101016650/ee95ece6-12d8-4e4d-8bc3-bf2a7c9db125)

**Comment by roopesh90** [comment]
Issue persists in old versions as well:
OS: Ubuntu
Node Version: 16.13.0
BitGoJS Versions: 13.1.0, 16.0.0, 19.13.0

@anji @dharanpdeepak

**Comment by d-lukutin** [comment]
fixed
