### ISSUE TITLE
Getting Error When I install

### ISSUE THREAD

**Issue by hitjariwala** [BitGo/BitGoJS#39]
Hi,

when i run npm install getting error.

64448 error Windows_NT 6.1.7601
64449 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
64450 error node v6.9.4
64451 error npm  v3.10.10
64452 error code ELIFECYCLE
64453 error sha3@1.2.0 install: `node-gyp rebuild`
64453 error Exit status 1
64454 error Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.
64454 error Make sure you have the latest version of node.js and npm installed.
64454 error If you do, this is most likely a problem with the sha3 package,
64454 error not with npm itself.
64454 error Tell the author that this fails on your system:
64454 error     node-gyp rebuild
64454 error You can get information on how to open an issue for this project with:
64454 error     npm bugs sha3
64454 error Or if that isn't available, you can get their info via:
64454 error     npm owner ls sha3
64454 error There is likely additional logging output above.
64455 verbose exit [ 1, true ]

**Comment by kuzcoh** [comment]
We released a new version today, 2.2.2, where the sha3 dependencies are optional. Running `npm install --no-optional` from the cloned SDK repo should fix the issue.
