### ISSUE TITLE
Bitgo production sendOTP/ unlock API not getting OTP code.

### ISSUE THREAD

**Issue by rihbyne** [BitGo/BitGoJS#40]
Hi team bitgo,
I am done with using the testnet env with bitgo. It works perfectly fine. Now, I have my env switched to 'prod' and I need the OTP code to unlock sendcoins API. I contacted bitgo support and got to know that sendOTP SMS option is deprecated and that you should use Authy to get the OTP via push notification. I have setup the 2FA using Authy and hitting the sendOTP API once again, but I am not receiving the OTP via push notification.

**Comment by thomas4019** [comment]
Hi Rihan,
Please let us know if you are still seeing an issue with this. Another possible option is to create an [API access token](https://www.bitgo.com/api/v2/#api-access-tokens) with a spending limit. As long as the total you have spent is less than the limit, you program won't need an OTP token.

**Comment by bobozar** [comment]
@thomas4019 is it a must for me to install bitgojs package before I can send coins on the production server? Why can't I interact via https://www.bitgo.com/api/v1 to send coins on the production server? The documentation didn't talk more on that.

**Comment by thomas4019** [comment]
Our server does not have the endpoints that require a wallet passphrase because our system is designed for us not to have unencrypted user keys. So you'll either need to run BitGo express or use our SDK. Also, this is not related to this specific issue so I'm closing it.
