### ISSUE TITLE
ETH. Create address

### ISSUE THREAD

**Issue by izhtrade** [BitGo/BitGoJS#406]
Hello

We look api in the direction of Ethereum and we wonder why we should use it if we cannot generate addresses on the fly (say, like Bitcoin.

Please clarify why this is done and how we should be, in terms of determining deposits from different customers.

Thank

**Comment by tylerlevine** [comment]
Hello @izhtrade,

It is certainly possible to generate Ethereum addresses on the fly, but unlike Bitcoin it costs gas to do so. We have a few different strategies we can recommend for how to distinguish deposits from different customers, but please reach out to support@bitgo.com for help with that.

**Comment by izhtrade** [comment]
You can show an example of one of the strategies, there is no desire to write to the support, and even here we will be more useful. All that we see is the creation of addresses as described in your api, but this approach does not suit us, due to the long wait for creating an address, about 5 minutes, if you look at the test.

#create address
curl -d "{}" -X POST https://test.bitgo.com/api/v2/teth/wallet/5d1ddb45e0e317700383ff4935e5a845/address -H "Content-Type: application/json" -H "Authorization: Bearer ACCESS_TOKEN"

{"id":"5d1f1edd77217fa403333b05c53a6f72","chain":0,"index":4,"coin":"teth","lastNonce":0,"wallet":"5d1ddb45e0e317700383ff4935e5a845","coinSpecific":{"nonce":-1,"updateTime":"2019-07-05T09:56:45.292Z","txCount":0,"pendingChainInitialization":true,"creationFailure":[]}}

more than 5 minutes have passed (even 10 seconds is a lot)

#get address
curl https://test.bitgo.com/api/v2/teth/wallet/5d1ddb45e0e317700383ff4935e5a845/address/5d1f1edd77217fa403333b05c53a6f72 -H "Content-Type: application/json" -H "Authorization: Bearer ACCESS_TOKEN"

{"error":"address pending on-chain initialization"}

no one will wait so much ... create them for the future, not some joy.

What other strategy, tell me, since I see nothing in your description?
