### ISSUE TITLE
wallets/simplecreate API returns error

### ISSUE THREAD

**Issue by kaifee2693** [BitGo/BitGoJS#41]
On calling the API " wallets/simplecreate " we get a response as 

{
  "error": "ethUtil.publicToAddress is not a function",
  "message": "ethUtil.publicToAddress is not a function"
}.

Even tried a nodeJs code to call wallets().createWalletWithKeychains which returns the same error.
 Please help us with this error.

**Comment by kuzcoh** [comment]
Hello Kaifee,

From the error you are receiving "ethUtil.publicToAddress is not a function", it appears that you are attempting to create an Ethereum wallet, is this correct? Ethereum is currently not supported yet. If this was an error and you were attempting to create a bitcoin wallet, we suggest using our [createwallet.js as an example template](https://github.com/BitGo/BitGoJS/blob/master/example/createwallet.js)

**Comment by kaifee2693** [comment]
Hi Omaid,
Extremely sorry for the delayed response. And thank you for your assistance.
I had the latest bitgo installed

**Comment by kaifee2693** [comment]
But working on it I realised something , that i was running bitgo on a windows machine.
I used the same codes while running bitgo on a linux machine and the error was gone. 
Thanks a lot for your help though. May be this thread will help others who start using bitgo APIs.

Regards,
Kaifee
