### ISSUE TITLE
ETH. Create address. #2

### ISSUE THREAD

**Issue by izhtrade** [BitGo/BitGoJS#415]
Hello

We look api in the direction of Ethereum and we wonder why we should use it if we cannot generate addresses on the fly (say, like Bitcoin.

Please clarify why this is done and how we should be, in terms of determining deposits from different customers.

Thank

**Answer from"Tyler Levine tylerlevine"**

> It is certainly possible to generate Ethereum addresses on the fly, but unlike Bitcoin it costs gas to do so. We have a few different strategies we can recommend for how to distinguish deposits from different customers, but please reach out to support@bitgo.com for help with that.

You can show an example of one of the strategies . All that we see is the creation of addresses as described in your api, but this approach does not suit us, due to the long wait for creating an address, about 5 minutes, if you look at the test.

#create address
curl -d "{}" -X POST https://test.bitgo.com/api/v2/teth/wallet/5d1ddb45e0e317700383ff4935e5a845/address -H "Content-Type: application/json" -H "Authorization: Bearer ACCESS_TOKEN"

{"id":"5d1f1edd77217fa403333b05c53a6f72","chain":0,"index":4,"coin":"teth","lastNonce":0,"wallet":"5d1ddb45e0e317700383ff4935e5a845","coinSpecific":{"nonce":-1,"updateTime":"2019-07-05T09:56:45.292Z","txCount":0,"pendingChainInitialization":true,"creationFailure":[]}}

more than 5 minutes have passed (even 10 seconds is a lot)

#get address
curl https://test.bitgo.com/api/v2/teth/wallet/5d1ddb45e0e317700383ff4935e5a845/address/5d1f1edd77217fa403333b05c53a6f72 -H "Content-Type: application/json" -H "Authorization: Bearer ACCESS_TOKEN"

{"error":"address pending on-chain initialization"}

no one will wait so much ... create them for the future, not some joy.

What other strategy, tell me, since I see nothing in your description?

**Comment by tylerlevine** [comment]
Some of our customers maintain a pool of pre-initialized addresses so they can hand them out to customers immediately upon request. Unfortunately, I'm not able to provide product support here on github, and you'll have to get in touch with support@bitgo.com if you're interested in discussing further.

**Comment by moza88** [comment]
I could get around this by going into the interface and adding money to the wallet from there. Then you'll be able to use the wallet using the API.
