### ISSUE TITLE
Error: Cannot find module '@brandonblack/musig/base_crypto'

### ISSUE THREAD

**Issue by HaykSahakyan** [BitGo/BitGoJS#4198]
Error: Cannot find module '@brandonblack/musig/base_crypto'
at Object. (/some path/node_modules/@bitgo/utxo-lib/dist/src/noble_ecc.js:11:20)
at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'some path/node_modules/@bitgo/utxo-lib/dist/src/noble_ecc.js',
'some path/node_modules/@bitgo/utxo-lib/dist/src/bitgo/keyutil.js',
'some path/node_modules/@bitgo/utxo-lib/dist/src/bitgo/index.js',
'some path/node_modules/@bitgo/utxo-lib/dist/src/index.js',
'some path/node_modules/@bitgo/sdk-core/dist/src/account-lib/util/crypto.js',
'some path/node_modules/@bitgo/sdk-core/dist/src/account-lib/baseCoin/ed25519KeyPair.js',
'some path/node_modules/@bitgo/sdk-core/dist/src/account-lib/baseCoin/index.js',
'some path/node_modules/@bitgo/sdk-core/dist/src/account-lib/index.js',
'some path/node_modules/@bitgo/sdk-core/dist/src/index.js',
'some path/node_modules/bitgo/dist/src/index.js',
...
]
}

Node.js v20.11.0
Ubuntu

**Comment by davidkaplanbitgo** [comment]
Hi, I am able to install `utxo-lib` locally with 
```bash
nvm use
yarn install
```
Can you please specify the commands you use to produce this?

**Comment by davidkaplanbitgo** [comment]
Closing this issue. Please re-open if you are still having issues
