### ISSUE TITLE
 SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by HaykSahakyan** [BitGo/BitGoJS#4199]
node_modules/@bitgo/sdk-coin-hbar/node_modules/sonic-boom/index.js:389
    cb?.()
       ^

SyntaxError: Invalid or unexpected token
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)

Node.js v18.19.0
SDK version 31.0.0

**Comment by margueriteblair** [comment]
Could you please provide more context about what command you're running when this error occurs? And what steps you took beforehand?

**Comment by mohammadalfaiyazbitgo** [comment]
Closing issue since no response was provided on the context of this error.
