### ISSUE TITLE
Super expression must either be null or a function in react-native

### ISSUE THREAD

**Issue by divyangkhatri** [BitGo/BitGoJS#4230]
## Environment Details

- **OS:** MAC
- **Node Version:** v18.19.0  
- **Yarn Version:** 1.22.21 
- **BitGoJS Version:**^9.26.0 
- **BitGo Environment:**  mainnet react-native 
- **React-Native Version:** 0.72.7  

## Expected Behavior

Should not throw error 

## Current Behavior

getting the error  "Super expression must either be null or a function"

**Comment by davidkaplanbitgo** [comment]
What was the script you were running? Can you reproduce this and post it here?

**Comment by davidkaplanbitgo** [comment]
If still an issue - reopen the bug, and please provide replication information
