### ISSUE TITLE
Signing Prebuilt PSBTs

### ISSUE THREAD

**Issue by Polybius93** [BitGo/BitGoJS#4483]
## Feature Description

Can BitGo accept a prebuilt PSBT transaction hex for signing, or does BitGo require the ``txPrebuild`` object provided by ``prebuildTransaction()`` for the signing process?

Is there a method to sign a PSBT using both the user's and BitGo's keys, and then receive a non-finalized PSBT for later addition of further signatures?

Another question is, why does the API return an "insufficient funds" error when I set the ``unspents`` value for the ``prebuildTransaction()`` function with a valid, existing, unspent output of a transaction?

## Motivation

It would make BitGo's signing flow more flexible and out of the box experience.

## Context

For instance, we aim to construct a PSBT involving a multisig configuration between the BitGo wallet and an external address. Our plan is to independently prepare the transaction, choose the specific inputs, and then initiate signatures from both the user and BitGo's keys. We would like the ability to retrieve the partially signed PSBT, which would then allow for additional signatures from another wallet, followed by the finalization and broadcasting of the transaction from the other end.

**Comment by davidkaplanbitgo** [comment]
> Can BitGo accept a prebuilt PSBT transaction hex for signing, or does BitGo require the txPrebuild object provided by prebuildTransaction() for the signing process?

Yes, you can provide the raw serialized PSBT hex in the `txHex` field without the extra stuff in there.

> Is there a method to sign a PSBT using both the user's and BitGo's keys, and then receive a non-finalized PSBT for later addition of further signatures?

Currently, no. There is an assumption that all of the inputs on the transaction belong to the wallet, so I think in this instance it would fail. We don't support BitGo cosigning "coinjoins". However, if you have a self-managed wallet, you can use the BitGoJS (mostly `utxo-lib`) to cosign the specific inputs with a user and backup signature. In this way you could sign that particular input and then not finalize the PSBT.

> Another question is, why does the API return an "insufficient funds" error when I set the unspents value for the prebuildTransaction() function with a valid, existing, unspent output of a transaction?

Do you have a `requestId` of an instance of this failure? This should not happen if you are providing a valid unspent ID that is tracked by the wallet.

**Comment by Polybius93** [comment]
Thank you @davidkaplanbitgo for your answers!

1. When I was trying to submit a txHex to sign (a PSBT which is working for example with Leather Wallet), I was receiving an error: 
``Error: sign errors at inputs: [Error: signing error at input 0: unspentId=c6b7bb1e81791741d95be26e39bebe8cea3dacd0b9bf75e2934c1ea5d660371a:0: Error: Need bip32Derivation to sign with HD], verify errors at inputs: [Error: signing error at input 0: unspentId=c6b7bb1e81791741d95be26e39bebe8cea3dacd0b9bf75e2934c1ea5d660371a:0: Error: No signatures to validate], see log for details``

Which I guess happens because some additional information is missing that is required by BitGo's signing function.

2. Okay, understood, so there is no option for that, only a workaround with the backup key.

3.This happened when we constructed a PSBT involving a multisig configuration between the BitGo wallet and an external address. Sent some Testnet Bitcoin to that address, and then tried to use that output as the input of a new transaction.
Is it possible that this UTXO is not tracked by BitGo and this is why it failed?

Thank you!

**Comment by davidkaplanbitgo** [comment]
> Which I guess happens because some additional information is missing that is required by BitGo's signing function.

Yes, exactly - in this case we need the derivation path from the root keys to the specific input.

> This happened when we constructed a taproot multisig configuration between the BitGo wallet and an external address. Sent some Testnet Bitcoin to that address, and then tried to use that output as the input of a new transaction.
Is it possible that this UTXO is not tracked by BitGo and this is why it failed?

Yes, you are right - for an unspent to be attributed to your wallet, the address needs to be tracked by our systems. The only way you can do this right now is to generate an address with our APIs. If you created an address on your side and not on our APIs, we wouldnt track that unspent as being attributed to your wallet. 

The `insufficient funds` is a wrapper error if we cannot find the specified unspent **on your wallet**.

**Comment by Polybius93** [comment]
Thank you! Could you tell me if it’s possible to generate a taproot multisig address with BitGo Wallet and an external public key using the API? Is it possible somehow to track this address and it's unspents? 
Specifically, we are looking to create two PSBTs:

- In the first PSBT, we aim to establish a taproot multisig address for the output using BitGo Wallet and an external public key.
- For the second PSBT, we intend to use the output from the first PSBT as the input. This would be partially signed by BitGo Wallet, then returned and forwarded to the external party for their signature.

**Comment by davidkaplanbitgo** [comment]
> Could you tell me if it’s possible to generate a taproot multisig address with BitGo Wallet and an external public key using the API? Is it possible somehow to track this address and it's unspents?

In our self-managed hot and cold wallets you are able to create a wallet with the `user` and `backup` keys being any key you want. Here is the documentation for how you would create these keys: https://developers.bitgo.com/guides/wallets/create/keys. Lastly you'll want to create a `bitgo` key, which is the key that we use to cosign.

Once you have created the three keys, you'll pass in those `keyIds` into creating a new wallet. More information about creating a wallet here: https://developers.bitgo.com/guides/wallets/create/wallets (general steps are given in the SDK (Manual) example).

Once you have the wallet, you'll want to create the address. Documentation for the API to create a new address: https://developers.bitgo.com/api/v2.wallet.newaddress For taproot musig addresses you are going to want to use the chain code `40`/`41`. More details on the different address types here: https://developers.bitgo.com/coins/address-types

> In the first PSBT, we aim to establish a taproot multisig address for the output using BitGo Wallet and an external public key.

Why do you need a PSBT to establish an address?

> For the second PSBT, we intend to use the output from the first PSBT as the input. This would be partially signed by BitGo Wallet, then returned and forwarded to the external party for their signature.

As a policy, BitGo does not cosign first for security reasons. If the input that the external party is different than the input that BitGo is cosigning, you could separate the PSBTs and combine them before finalizing. If they are signing the same input, they'd need to cosign first and then you'd submit the PSBT to us.

**Comment by davidkaplanbitgo** [comment]
@Polybius93 - it seems that the issue has been solved. I am going to mark as resolved in the meantime. If you have other concerns or questions, reach out to supprt@bitgo.com or raise another issue.
