### ISSUE TITLE
Can't build the Bitgo@6.2.0 image

### ISSUE THREAD

**Issue by anduonghien** [BitGo/BitGoJS#451]
Getting this error when building the Bitgo@6.2.0 image, I fixed that by adding the `RUN npm install` step to the `Dockerfile`

![image](https://user-images.githubusercontent.com/11751745/61788916-86d73680-ae3d-11e9-8d5f-785fbb151dc6.png)

**Comment by tylerlevine** [comment]
Thanks for the feedback @anduonghien, we will be updating the README for bitgo express in the next day or so to clarify the install instructions.
