### ISSUE TITLE
Cannot compile on Windows 10

### ISSUE THREAD

**Issue by ericgoro** [BitGo/BitGoJS#457]
1) I install nodejs
2) I install yarn
3) I run: npm install in the BitGoJS directory

Here is the error log (after 50)

50 silly postinstall root@
51 info lifecycle root@~postinstall: root@
52 verbose lifecycle root@~postinstall: unsafe-perm in lifecycle true
53 verbose lifecycle root@~postinstall: PATH: C:\Users\Administrator\scoop\apps\nodejs\12.7.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\http\p2p.ncpool.com\BitGoJS\node_modules\.bin;C:\Users\Administrator\scoop\apps\nodejs\current\bin;C:\Users\Administrator\scoop\apps\nodejs\current;C:\Users\Administrator\scoop\apps\yarn\current\Yarn\bin;C:\Users\Administrator\scoop\apps\yarn\current\global\node_modules\.bin;C:\Users\Administrator\scoop\shims;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files\smartmontools\bin;C:\Users\Administrator\AppData\Local\GitHubDesktop\bin;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\AppData\Local\Yarn\bin
54 verbose lifecycle root@~postinstall: CWD: D:\http\p2p.ncpool.com\BitGoJS
55 silly lifecycle root@~postinstall: Args: [ '/d /s /c', 'lerna run build --stream --parallel' ]
56 timing audit submit Completed in 788ms
57 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 788ms
58 timing audit body Completed in 2ms
59 silly lifecycle root@~postinstall: Returned: code: 1  signal: null
60 info lifecycle root@~postinstall: Failed to exec postinstall script
61 verbose stack Error: root@ postinstall: `lerna run build --stream --parallel`
61 verbose stack Exit status 1
61 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\scoop\apps\nodejs\12.7.0\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
61 verbose stack     at EventEmitter.emit (events.js:203:13)
61 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\scoop\apps\nodejs\12.7.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
61 verbose stack     at ChildProcess.emit (events.js:203:13)
61 verbose stack     at maybeClose (internal/child_process.js:1021:16)
61 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
62 verbose pkgid root@
63 verbose cwd D:\http\p2p.ncpool.com\BitGoJS
64 verbose Windows_NT 10.0.14393
65 verbose argv "C:\\Users\\Administrator\\scoop\\apps\\nodejs\\current\\node.exe" "C:\\Users\\Administrator\\scoop\\apps\\nodejs\\current\\node_modules\\npm\\bin\\npm-cli.js" "install"
66 verbose node v12.7.0
67 verbose npm  v6.10.0
68 error code ELIFECYCLE
69 error errno 1
70 error root@ postinstall: `lerna run build --stream --parallel`
70 error Exit status 1
71 error Failed at the root@ postinstall script.
71 error This is probably not a problem with npm. There is likely additional logging output above.
72 verbose exit [ 1, true ]

**Comment by tylerlevine** [comment]
Are you trying to run bitgo express, or do you want to use BitGoJS as a dependency in your project? If it's the first one, we recommend running via docker (you can find instructions in the express README). If it's the second, we recommend installing bitgo as a dependency in your project with `npm install --save bitgo`. I'm not quite sure why you're getting these errors on windows, but you should never really be mixing npm and yarn, so something is not correct here.
