### ISSUE TITLE
Missing release notes for bitgo v7

### ISSUE THREAD

**Issue by jaydenseric** [BitGo/BitGoJS#459]
There are no release notes for `bitgo@7`:

https://github.com/BitGo/BitGoJS/blob/bitgo%407.0.0/modules/core/RELEASE_NOTES.md

What were the breaking changes from v6? How do we migrate?

**Comment by jaydenseric** [comment]
Also, it would be very useful to populate the GitHub release descriptions with change notes:

https://github.com/BitGo/BitGoJS/releases/tag/bitgo%407.0.0

This makes watching releases and email notifications much more meaningful, and is generally a more convenient place to find and link to release notes than having to dig around the repo files.

**Comment by tylerlevine** [comment]
Apologies @jaydenseric, we will get the v7 release notes up as soon as possible. The breaking change was a signature change in the basecoin `explainTransaction` method. Will have more details in the release notes.

We'll also look at automating the creation of release notes and correctly populating the github releases in the near future.

**Comment by tylerlevine** [comment]
v7 release notes have been merged in https://github.com/BitGo/BitGoJS/pull/471
