### ISSUE TITLE
Redundant files published in bitgo

### ISSUE THREAD

**Issue by jaydenseric** [BitGo/BitGoJS#460]
There are redundant files such as `tsconfig.json` and `webpack.config.js` published in the `bitgo` package:

https://unpkg.com/browse/bitgo@7.0.0/

You are using a blacklist approach via a [`.npmignore`](https://github.com/BitGo/BitGoJS/blob/master/modules/core/.npmignore) file. It is much more elegant to switch to a whitelist approach instead, using the `package.json` `files` field, like this:

https://github.com/jaydenseric/graphql-upload/blob/v8.0.7/package.json#L26

This would pretty much eliminate the accidental publishing of redundant files.

**Comment by tylerlevine** [comment]
Thanks @jaydenseric, we'll start using `files` for the 7.2 release. We had originally decided to ship the webpack.config.js and tsconfig.json to avoid breaking some users who were running tsc or webpack themselves by running the commands inside their node modules. I'll check to see if we still need to support that use case.
