### ISSUE TITLE
I can't generate wallet in txrp 

### ISSUE THREAD

**Issue by greinnya** [BitGo/BitGoJS#48]
Hi team BitGo,
I have installled bitgo version v3.4.0

bitgo.coin('txrp).wallets().generateWallet({ label: "label", passphrase: "passphrase" })
  .then(function(wallet) {
    console.log(wallet);
    res.json({ wallet });
  },function(response){
     res.json({ response });

  });

When I try to generate my wallet in txrp the response is: 

{
    "response": {
        "status": 404,
        "result": {
            "error": "address balance not found"
        }
    }
}

**Comment by omaidf** [comment]
This behavior is occurring due to the resetting of Ripple's testnet. It should be fixed sometime in the future.
