### ISSUE TITLE
I can't generate wallet in teth

### ISSUE THREAD

**Issue by SeptiyanAndika** [BitGo/BitGoJS#49]
Hi team BitGo,
I have installled bitgo version v3.4.0

when i generate wallet with `teth`, i got a error ` Error: cannot access this route with coin type teth`,

this is my code
`this.bitgo.coin('teth').wallets()
    .generateWallet({ label: label, passphrase: passphrase })
    .then(function(wallet) {
      // print the new wallet
      console.dir(wallet);
    }).catch(function(err) {
      console.log(err);
    });`

thanks

**Comment by omaidf** [comment]
Hello,

Could you please let verify that you are running this in a testnet environment?

**Comment by omaidf** [comment]
Hello, @SeptiyanAndika ?

**Comment by SeptiyanAndika** [comment]
Hi @omaidf , yes i use testnet environtment.
` let bitgo = new BitGo.BitGo({ env: 'test',accessToken: 'v2x43630cb0ddb20004d1f7d295029xxxxxxxxxx' }); 
`
