### ISSUE TITLE
superagent removes headers and github blocks it

### ISSUE THREAD

**Issue by FaGuoMa** [BitGo/BitGoJS#493]
We plan to use BitgoExpress as a proxy for rest calls, and thus have no appetite or skills to deal with  npm packages monkey patching.

`npm install -g bitgo` fails with:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

```
C:\XXX>node -v
v10.16.3
C:\XXX>npm --version
6.9.0

C:\XXX>npm install -g bitgo
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent rem
oves User-Agent header by default, therefore you may need to add it yourself (e.
g. GitHub blocks requests without a User-Agent header).  This notice will go awa
y with v5.0.2+ once it is released.
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/BitGo/algosdk-bitgo
.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\XXX\npm-cache\_logs\2019-08-27T08_33_25_135
Z-debug.log

```

**Comment by tylerlevine** [comment]
I don't think this is a problem with superagent, it looks like you just need to install git on that machine to download the algosdk-bitgo package. I'll make a note to change that to a normal npm package or at least tarball so you won't need git installed going forward.

**Comment by FaGuoMa** [comment]
I reall don't know, I just inferred it from the console log:
> WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent rem
oves User-Agent header by default, therefore you may need to add it yourself (e.
g. GitHub blocks requests without a User-Agent header)

**Comment by tylerlevine** [comment]
That's a warning saying that future versions of superagent are changing their behavior. The actual error you're getting is from not having git installed.
