### ISSUE TITLE
Error: needs unlock

### ISSUE THREAD

**Issue by domgolonka** [BitGo/BitGoJS#50]
Currently I am getting an "Error: needs unlock" when spending coins via API. I have a setup an long access token and clicked on all the options. The website states that "Long-lived access tokens are suitable for use on servers/unattended devices. The tokens do not require an OTP for spending and must be locked down to IP addresses.". 

But I cannot spend the BTC without an OPT.

**Comment by bpdavenport** [comment]
It's likely your token has exceeded its lifetime spending limit you set
when you created it. Have you tried creating a new token?

Ben

**Comment by omaidf** [comment]
Hello, @domgolonka ?

**Comment by domgolonka** [comment]
Figured it out. It was because I have set "0" to the spending coins option in bitgo.

**Comment by PriyanshDwivedi** [comment]
Hi @domgolonka , I explicitly left the spending limit blank but when I view the created access token, it shows spending limit as 0 and there is no way to edit it.

How did you remove the 0 spending limit?

**Comment by CapnMigraine** [comment]
@PriyanshDwivedi, it's not possible to update the spending limits on a token. You should create a new one instead.

**Comment by Scott-S** [comment]
I ran into the same issue of leaving the spending limit blank on TBTC, and it defaulted to "0". This should be fixed

**Comment by imrahulprajapat** [comment]
You Just need to **create new token** and have to enter some amounts in **Lifetime spending limits** section.
![Screenshot from 2020-12-24 15-00-30](https://user-images.githubusercontent.com/28958100/103079005-11a2fe80-45f9-11eb-8405-ec840e1883c3.png)

**Comment by SergeyMell** [comment]
It seems that living spending limits as blank leads to zero spending limits. So, they are not optional in fact

**Comment by gndelia** [comment]
I created my spending limits but I still see this error 😢 

> ApiResponseError: needs unlock

**Comment by imrahulprajapat** [comment]
> I created my spending limits but I still see this error 😢
> 
> > ApiResponseError: needs unlock

did you changed replaced  token as well after updating/creating limits ?? ref: https://github.com/BitGo/BitGoJS/issues/50#issuecomment-750823456

**Comment by gndelia** [comment]
@imrahulprajapat  thanks for your response! I don't see that exact page (might it be out of date?) I did set limits in two places (in my case, I'm working with testing ETH - `gteth`)

This is on my general settings

<img width="968" alt="image" src="https://github.com/BitGo/BitGoJS/assets/352474/10482a25-fd87-4642-ab2c-bb1246add3da">

This is on the wallet settings

<img width="515" alt="image" src="https://github.com/BitGo/BitGoJS/assets/352474/4b02d607-2d83-46d8-9752-2a9f2c949548">

And just in case, this is my code. I'm just investigating on how to use it so it's just a bit of testing/snippet code, not production ready at all

```js
const accessToken =
  process.env.ACCESS_TOKEN
const walletPassphrase = process.env.PASSPHRASE

const { BitGoAPI } = require('@bitgo/sdk-api')
const { Gteth } = require('@bitgo/sdk-coin-eth')

const sdk = new BitGoAPI({
  accessToken,
  env: 'test'
})

sdk.register('gteth', Gteth.createInstance)

const targetAddress = '0xSomeAddressOutsideOfBitgo'

sdk
  .coin('gteth')
  .wallets()
  .getWallet({ id: 'walletId' })
  .then(function (wallet) {
    // console.log(wallet.spendableBalanceString()) => returns a string number > 10000000000
    return wallet.send({
      address: targetAddress,
      amount: '10000000000',
      walletPassphrase
    })
  })
  .then(console.log)
  .catch(console.error)

```

This gets me `ApiResponseError: needs unlock`
