### ISSUE TITLE
Bitgo Cryptic Api Error Responses

### ISSUE THREAD

**Issue by winni4eva** [BitGo/BitGoJS#509]
I have been trying to create wallet with the enpoint
```
POST
http://127.0.0.1:3080/api/v2/tbtc/wallet/generate
REQUEST DATA
{
  "label": "myLabel",
  "passphrase": "myPass"
}
```
It succeeded once and it fails now with error
```
{
    "error": "invalid key sources",
    "name": "Invalid",
    "requestId": "ck0cblkef0tvyrlrsvh3d92bi",
    "context": {},
    "message": "invalid key sources"
}
```
When I change the coin to tbch I get the response
```
{
    "error": "Coin type tbch not supported",
    "message": "Coin type tbch not supported"
}
```
Is there a central document that explains all errors from the api. Or kindly help me figure out what I am doing wrong

**Comment by winni4eva** [comment]
The issue was I was running the sdk using the public docker repository using the latest version. The api started returning the correct responses when I started serving the sdk from the Js sdk itself.

**Comment by tylerlevine** [comment]
Thanks for the update @winni4eva, we'll look into the issue with the BitGo Express docker container.
