### ISSUE TITLE
Error while sending coins

### ISSUE THREAD

**Issue by v8solution** [BitGo/BitGoJS#518]
Hello, 

I'm getting below error while sending coins to an address from bitgo.

`unsigned keys obtained online are being used for address verification`

Request is as below:
`api/v2/btc/wallet/:wallet_id/sendcoins`

Header contains valid bitgo token.

Body:
    {
	"address":"ABCD",
	"amount":"12345",
	"feeRate":null,
	"walletPassphrase":"passphrase"
    }

Can you please help me figure out the issue?

**Comment by jayd3e** [comment]
I am also getting this error in my logs.  It doesn't impede upon users sending keys, but I am curious about its origin as well.

**Comment by sarascahya** [comment]
Bitgo Support says "That's a warning, you can ignore it for now. If you want to remove this warning - you will need to update SDK."
