### ISSUE TITLE
Initiate Transaction - awaitingSignature

### ISSUE THREAD

**Issue by bog-h** [BitGo/BitGoJS#529]
Hello, I would like to initiate a transaction **in awaiting approval mode** with multiple operations (send coins too few addresses) to have a fee. 

I need this fee to look on what I need to do next, approve or reject transactions.

I'm calling API to initiate transaction, it is setting transaction to status **awaitingSignature**,  then I'm trying to call Resolve pending approval but it is returning an error, something about admin privileges are required.

 I'm trying to sign it via Sign Wallet Transaction but I cannot figure out how to get txPrebuild object, I'm trying to add response from initiate transaction request but getting an error around json_decode cannot parse the object.

Can I have an advice please?

**Comment by cooncesean** [comment]
Do these docs help: https://www.bitgo.com/api/v2/#operation/express.pendingapprovals ?

**Comment by bog-h** [comment]
Maybe I misunderstood something, I didn't succeed with the awaiting signature, but I resolved my case with the new flow. Build transaction to have a fee, then sign it and send it.

**Comment by PushHandle** [comment]
@bog-h I am having the same issue.  Can you detail how you signed the tx after building it? Did you use Express?
