### ISSUE TITLE
Send Transaction Failure

### ISSUE THREAD

**Issue by SeptiyanAndika** [BitGo/BitGoJS#53]
Hi Bitgo Team, 
I use testnet environment for send tarnsctaions i have put address in receptions parameter like a in documenation, get a message `Error: Missing parameter: address`, 
`let params = {
  recipients: [
    {
      amount: 0.01 * 1e8,
      address: '0x127be4f95f6e06d652c2cf30ad983d92a937b2ea',
    }
  ],
  walletPassphrase: 'BtTl1TIE7pqbzU3kFxkd6W7GT8ynMPtI'
};
wallet.send(params)
.then(function(transaction) {
  // print transaction details
  console.dir(transaction);
}).catch(function(error) {
              // print transaction details
              console.dir(error);
            });`

Please help. thanks

**Comment by Xekyo** [comment]
> `address: '0x127be4f95f6e06d652c2cf30ad983d92a937b2ea'`

What you've put as an address, is not properly formatted. Addresses are expected to be base58, but you provide a hex number. What you've copied could possibly a public key or yet another format.

**Comment by SeptiyanAndika** [comment]
i try send Ethereum, full erros is
`Error: Missing parameter: address
    at /Users/andika/Documents/Workspace/nodejs/tokocrypto-exchange-serverless/client/web/node_modules/bitgo/src/common.js:190:13
    at Array.forEach (native)
    at Object.exports.validateParams (/Users/andika/Documents/Workspace/nodejs/tokocrypto-exchange-serverless/client/web/node_modules/bitgo/src/common.js:188:18)
    at Wallet.send (/Users/andika/Documents/Workspace/nodejs/tokocrypto-exchange-serverless/client/web/node_modules/bitgo/src/v2/wallet.js:576:10)
    at /Users/andika/Documents/Workspace/nodejs/tokocrypto-exchange-serverless/client/web/helpers/BitgoWrapper.js:144:14
    at _fulfilled (/Users/andika/Documents/Workspace/nodejs/tokocrypto-exchange-serverless/client/web/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/Users/andika/Documents/Workspace/nodejs/tokocrypto-exchange-serverless/client/web/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/Users/andika/Documents/Workspace/nodejs/tokocrypto-exchange-serverless/client/web/node_modules/q/q.js:756:13)
    at /Users/andika/Documents/Workspace/nodejs/tokocrypto-exchange-serverless/client/web/node_modules/q/q.js:564:44
    at flush (/Users/andika/Documents/Workspace/nodejs/tokocrypto-exchange-serverless/client/web/node_modules/q/q.js:110:17)`

my full code is https://gist.github.com/SeptiyanAndika/fce41eec7f3cf0f9027b6902602f273c

thanks

**Comment by arik-so** [comment]
Hi, 

Try changing `wallet.send(params)` to `wallet.sendMany(params)`.

Arik

**Comment by SeptiyanAndika** [comment]
thanks @arik-so

**Comment by SeptiyanAndika** [comment]
@arik-so is working, but must change amount toString(), if not sting get a message `invalid amount for 0x127be4f95f6e06d652c2cf30ad983d92a937b2ea - should be a numerical string`
please update the docs, https://www.bitgo.com/api/v2/#send-transaction, so user can't confuse.
thanks

**Comment by arik-so** [comment]
Ok, thanks for your feedback.

**Comment by prajit21** [comment]
Hi Bitgo Team,
when i try to send eth coin to another address  getting response something like...

**My sample code..**

let params = {
        amount: 100000000000000000000,
        address: '0xc26fdb3781df2c409c82c97764ea00b95598bf8a',
        walletPassphrase: 'jUuVZc1C'
    };
    wallet.send(params)
        .then(function(transaction) {
            res.json(transaction);
            console.dir(transaction);
        });

**Response **

{
  "error": "invalid amount for 0xc26fdb3781df2c409c82c97764ea00b95598bf8a - should be a numerical string",
  "name": "Invalid",
  "requestId": "cjil8mpsd0mxiqjrzysc9602o",
  "message": "invalid amount for 0xc26fdb3781df2c409c82c97764ea00b95598bf8a - should be a numerical string"
}

Please help me.
