### ISSUE TITLE
Error: output value is less than dust threshold on test.bitgo.com

### ISSUE THREAD

**Issue by olalonde** [BitGo/BitGoJS#55]
I recently noticed this error in my tests (I wasn't getting it before) when sending an OP_RETURN transaction on testnet:

```
[Error: output value is less than dust threshold] status: 400, result: { error: 'output value is less than dust threshold' 
```

What does it mean? And what is the minimum threshold?

**Comment by omaidf** [comment]
Hello,
The current dust threshold is 2730 Satoshis. The dust threshold is the smallest amount of Bitcoin you can send for a transaction.

**Comment by olalonde** [comment]
This was fixed.
