### ISSUE TITLE
Attempt to use IP-restricted token from an unauthorized IP address

### ISSUE THREAD

**Issue by omkarsunku** [BitGo/BitGoJS#556]
I am just started(beginner) using Bitgo SDK for my project. I have cloned the Bitgo source code and then started  using

npm run start
**Started**
BitGo-Express running
Environment: test
Base URI: http://localhost:3080

**Tested using curl**
 curl localhost:3080/api/v2/ping
{"status":"service is ok!","environment":"BitGo Testnet","configEnv":"testnet","configVersion":80}
working fine.

But when I try to  test the wallet address it failing
 curl localhost:3080/api/v2/tbtc/wallet/address/2MzQwSSnBHWHqSAqtTVQ6v47XtaisrJa1Vc
{"error":"unauthorized","name":"Unauthorized","requestId":"ck1vqn44i07t3u6rsjd0alx9o","context":{},"message":"unauthorized"}
127.0.0.1 - local_express [18/Oct/2019:06:14:26 +0000] "GET /api/v2/tbtc/wallet/address/2MzQwSSnBHWHqSAqtTVQ6v47XtaisrJa1Vc HTTP/1.1" 401 124 "-" "curl/7.65.1"
error 401: Attempt to use IP-restricted token from an unauthorized IP address

Can anyone help me here?

**Comment by PolymathWhiz** [comment]
You're using an access token that has an IP whitelist
