### ISSUE TITLE
slack.bitgo.com is unreachable

### ISSUE THREAD

**Issue by Ollemesh** [BitGo/BitGoJS#57]
Hello,
I have few questions about BitGoJS and other BitGo tools.
I'm going to ask your community in your slack team, but don't know how to get the invite.
(https://slack.bitgo.com/ is unreachable)

**Comment by awaisraza308** [comment]
I am having trouble with it too? If you don't mind me asking what are you trying to do with bitgo integration?

**Comment by Ollemesh** [comment]
about my questions:
I have my own local Bitcoin Node (Bitcoin Core wallet) and work with it throw NodeJS server (using ["bitcoin-core" npm-module](https://www.npmjs.com/package/bitcoin-core)). 
I would like to send BitGo Instant transactions, how can I do it?
-Should I install the KRS to my Node (https://github.com/BitGo/key-recovery-service) ?
-Can I send BitGo Instant transactions by my Bitcoin Node or have to change it to your Bitcoin solutions:
 [BitGoD](https://github.com/BitGo/bitgod) or [bitcore-node](https://github.com/BitGo/bitcore-node)?
(or maybe I must use your online wallets by BitGo for Business).
-What's mean
> In order to send BitGo Instant transactions, you will need either a BitGo KRS wallet, or will need to arrange a collateral agreement with BitGo
 [here](link: https://bitgo.github.io/bitgo-docs/#bitgo-instant).
What address to communicate for this question?
-Should I install some other tools: [BitGo-CLI](https://github.com/BitGo/bitgo-cli) or [BitGoJS] (https://github.com/BitGo/BitGoJS) for sending BitGo Instant transactions?

**Comment by omaidf** [comment]
The correct Slack Channel is bitgodevs.slack.com.

**Comment by awaisraza308** [comment]
Thank you very much, but it's invite only.

**Comment by Ollemesh** [comment]
Yes, how can we get the invite? I think the link (https://slack.bitgo.com/) in your README.md isn't mistaken. The page should generate the invite.

**Comment by jlopp** [comment]
@Ollemesh The BitGo devs slack is not open to the public; it's not our intention to allow anyone to invite themselves. I've submitted a PR to fix the link at https://github.com/BitGo/BitGoJS/pull/59 and sent you an invitation to the slack.

**Comment by romainPellerin** [comment]
Hi all, your website https://slack.bitgo.com seems to be down, I would like to join BitGo devs slack and have some questions to ask your community. Could you invite me or fix your website asap? Thanks!

**Comment by jlopp** [comment]
The link was fixed a month ago on the README of this repository; it now links to https://bitgodevs.slack.com/

Are you building an application using the BitGo API? The slack team is basically for development support from BitGo engineers.

**Comment by romainPellerin** [comment]
I have a question on how we could manage users with Bitgo within our app actually. Would love to access your Slack to discuss further this feature.
