### ISSUE TITLE
Please increase my limit i keep on getting this message.  "needs unlock"

### ISSUE THREAD

**Issue by awaisraza308** [BitGo/BitGoJS#58]
I am keep on getting this error
 {"code"=>-10600, "message"=>"needs unlock"} it is error after sendtoaddress in bitcoin-cli

could you please unlock the hourly,daily,and limit per transaction.

![image](https://user-images.githubusercontent.com/20868864/29889755-ef3e6fac-8d8a-11e7-8369-5728e821a53c.png)

**Comment by omaidf** [comment]
We have resolved this issue over our Ticketing System.
