### ISSUE TITLE
Wrong env variable BITGO_DISABLESSL

### ISSUE THREAD

**Issue by godunko-v** [BitGo/BitGoJS#599]
Can you please update your Configuration Values table?
There no **BITGO_DISABLESSL** more, instead this uses **DISABLE_SSL** flag

**Comment by minherc** [comment]
как использовать DISABLE_SSL ?
export DISABLE_SSL 
не работает
у меня он вообще почему то не видит переменных окружения...

**Comment by minherc** [comment]
запуск с параметрами тоже не работает  https://github.com/BitGo/BitGoJS/issues/608#issue-527736213

**Comment by godunko-v** [comment]
> как использовать DISABLE_SSL ?
> export DISABLE_SSL
> не работает
> у меня он вообще почему то не видит переменных окружения...

**DISABLE_SSL** is binary type of variable. You should set it to 1
Just try to use:
`docker run -it  -p 4000:4000 bitgosdk/express:latest -p 4000 -e DISABLE_SSL="1"  -e prod`

**Comment by minherc** [comment]
> docker run -it -p 4000:4000 bitgosdk/express:latest -p 4000 -e DISABLE_SSL="1" -e prod

not worked for me:
```
docker run -it -p 4000:4000 bitgosdk/express:latest -p 4000 -e DISABLE_SSL="1" -e BITGO_BIND="localhost" -e BITGO_DISABLE_ENV_CHECK="1"  -e prod
Fatal error: Must enable TLS when running against prod and listening on external interfaces!
Error: Must enable TLS when running against prod and listening on external interfaces!

```

**Comment by godunko-v** [comment]
> > docker run -it -p 4000:4000 bitgosdk/express:latest -p 4000 -e DISABLE_SSL="1" -e prod
> 
> not worked for me:
> 
> ```
> docker run -it -p 4000:4000 bitgosdk/express:latest -p 4000 -e DISABLE_SSL="1" -e BITGO_BIND="localhost" -e BITGO_DISABLE_ENV_CHECK="1"  -e prod
> Fatal error: Must enable TLS when running against prod and listening on external interfaces!
> Error: Must enable TLS when running against prod and listening on external interfaces!
> ```

Try to pass `-e DISABLE_SSL="1"` before container name. Like this:

`docker run -it -p 4000:4000 -p 4000 -e DISABLE_SSL="1" bitgosdk/express:latest -e prod`

**Comment by minherc** [comment]
Заработало!
Спасибо Василий !
```
docker run -it -p 4000:4000 -e DISABLE_SSL="1" bitgosdk/express:latest -e prod -p4000
BitGo-Express running
Environment: prod
Base URI: http://0.0.0.0:4000
172.17.0.1 - local_express [25/Nov/2019:10:16:48 +0000] "GET /api/v2/ping HTTP/1.1" 200 97 "-" "curl/7.52.1"
```
ps только порт -p нужно в конце указывать
