### ISSUE TITLE
Blockr.io shutting down

### ISSUE THREAD

**Issue by vnistor** [BitGo/BitGoJS#60]
https://github.com/BitGo/BitGoJS/blob/c79f609a627277ff9395da1668499992816ebff6/src/v2/coins/ltc.js#L67

![litecoin block explorer blockr io litecoin blockchain market and price](https://user-images.githubusercontent.com/6135294/29958220-4c2df6b8-8efa-11e7-9db4-10a78e7092f4.png)

[blockr.io](https://ltc.blockr.io/)

**Comment by bencxr** [comment]
This is very unfortunate, we will have to work on a replacement.

**Comment by LeoKotschenreuther** [comment]
We don't use Blockr.io anymore so we can safely close this.
