### ISSUE TITLE
High severity vulnerability

### ISSUE THREAD

**Issue by devsi** [BitGo/BitGoJS#600]
One of your packages uses a vulnerable version of `https-proxy-agent`. Please can you update your dependencies to ensure this is no longer a threat. 

See attached screenshot for more info.

<img width="609" alt="Screen Shot 2019-11-15 at 5 15 02 PM" src="https://user-images.githubusercontent.com/7467531/68985485-9ce17c00-07cb-11ea-9e04-365ec5d764b0.png">

ripple-lib requires version 1.4.0 and is the first version that updates it's version of https-proxy-agent. If you can depend on ripple-lib 1.4.0 instead, this will solve the problem.

**Comment by devsi** [comment]
For ref:

bitgo uses: ripple-lib 0.22.0
ripple-lib uses: https-proxy-agent: 2.2.1.

**Comment by tylerlevine** [comment]
Thanks for the report. This should be fixed in master by #601, and will be released soon as version 9.0.0.
