### ISSUE TITLE
Hd wallet path for segwit addresses

### ISSUE THREAD

**Issue by ZebPayDhruvil** [BitGo/BitGoJS#61]
I can see segwit address of change are generated on chain 11,
Can you provide full path m/0/0/11 does not work
Also what will be path of receive addresses ?

**Comment by jlopp** [comment]
SegWit receive addresses are on chain 10 while change addresses are on chain 11 - you need to be using SDK version 4+ https://bitgo.github.io/bitgo-docs/#create-address
