### ISSUE TITLE
Always Return 'Already Login' from bitgo-express & 404 for link

### ISSUE THREAD

**Issue by Aradea08** [BitGo/BitGoJS#63]
Hi,

I'm trying to combine BitGo-Express with PHP.
As the tutorial says, BitGo may combine with any language as long as BitGo Express running.

Problem : 
1. When i login from browser (PHP Script) return always : 
 
stdClass Object
(
    [error] => already logged in
    [message] => already logged in
)

Test(s) i've done (from php script) before login from node js example : 

1. Try to access session (response) : 
stdClass Object
(
    [error] => unauthorized
    [message] => unauthorized
)

2. List Wallet (response) : 
stdClass Object
(
    [error] => unauthorized
    [message] => unauthorized
)

3. Create Wallet (response) : 
stdClass Object
(
    [error] => unauthorized
    [message] => unauthorized
)

**I assume that login is needed :** 

1. Try to login from node js in example (response) : 
=> List of login detail
=> Access Token of course

Then, i used access token given from login with node js and use it in php script.
I face no problem. Every access (above) run well, except several like (user/me) return 404.

Event logout method run well from php script.

The questions are : 
=> Why login (from php) always return "Already Login" (even not login yet) but success from node JS ? 
=> Why link like (user/me) return 404 ? 

Thx in advance

**Comment by LeoKotschenreuther** [comment]
@Aradea08 
I can actually answer your questions.

When you authenticate with an access token there is no need to call the Login route of the BitGo Express server. When it says "Already logged in", it's trying to tell you that you don't need to call that route at all. Secondly, certain routes are not useable with access tokens at all. The user/me route is one of them. You would have to use your login credentials and OTP to access those routes or use our website for that.
