### ISSUE TITLE
Wrong Documentation or Code regarding DISABLESSL 

### ISSUE THREAD

**Issue by arnoldsi** [BitGo/BitGoJS#635]
In express page documentation under Configuration Values the Node env name for disable SSL is:
![image](https://user-images.githubusercontent.com/18511197/71322616-53730380-24d2-11ea-9104-311760120d1e.png)

In modules/express/src/config.ts you use the wrong parameter:
disableSSL: process.env.**DISABLE_SSL** ? Boolean(process.env.DISABLE_SSL) : undefined,

Please update the documentation or fix the variable.
Thanks

**Comment by rqc** [comment]
Ran into the same issue today.

**Comment by cooncesean** [comment]
@tylerlevine does #657 fix this issue?

**Comment by tylerlevine** [comment]
Yes, this should now be fixed. Please open a new issue if this is still a problem.
