### ISSUE TITLE
Better release notes

### ISSUE THREAD

**Issue by vogelito** [BitGo/BitGoJS#669]
Better release notes are important for companies building on top of BitGo. The release notes for BitGo Express have not been updated in over 5 months.

## Feature Description
modules/express/RELEASE_NOTES.md should be updated regularly and at least with every release that is tagged in the release section of this github project. If no relevant updates to express are being made, then a simple release note explaining that there are no relevant changes would be great.

## Motivation
As a company that is building on top of BitGo, it’s important that we keep our tech stack up to date. BitGo seems to release new versions of express very frequently, but without release notes it becomes impossible to track what is changing.

## Context
We are subscribed to the RSS fees for GitHub updates. It sucks to get a notification in your feed where you then can’t get any additional feedback on what’s being released.

**Comment by tylerlevine** [comment]
Hi @vogelito, thanks for opening the issue. I'll ensure the release notes are updated in a timely manner upon each regular release of `bitgo` and `express` going forward. We do have a long term plan for automating the release notes generation, but until then, it's a bit of a manual process and sometimes we fall behind, as you have noticed.

Please expect a catch up on the release notes early next week, and approximately weekly updates after that when version numbers are changed.

I'll leave this issue open until the catch-up on the release notes is delivered.

**Comment by vogelito** [comment]
Thank you! Much appreciated!

**Comment by tylerlevine** [comment]
Hello @vogelito, we have just merged https://github.com/BitGo/BitGoJS/pull/672 which updates the express and core release notes through the latest versions of each. We'll be more timely with manual release notes updates until we can get a more automated solution in place.

Thanks again for opening the issue!

**Comment by vogelito** [comment]
Thank you!
