### ISSUE TITLE
sendMany() throws "error": "Cannot send to more than one address"

### ISSUE THREAD

**Issue by marcosaftertype** [BitGo/BitGoJS#67]
Hi there,

I'm using the `wallet.sendMany` method and with only one `recipients: [{address, amount}]` works fine, but if the recipients contain more than one (`[{address, amount}, {address, amount}, {address, amount}]`) it throws:

`"error": "Cannot send to more than one address"`

What could be the reason for that?

**Comment by bencxr** [comment]
As per our documentation, you will receive this error if sending eth or xrp. This is just the nature of XRP's blockchain (as per their design) and is also the default behavior in ETH.

**Comment by marcosaftertype** [comment]
Got it, thank you for the explanation bencxr
