### ISSUE TITLE
Replace BitcoinAverage API url for wallet recoveries

### ISSUE THREAD

**Issue by dannydeezy** [BitGo/BitGoJS#673]
# Overview
BitcoinAverage no longer supports free API access. When you try to do a wallet recovery with a Key-Recovery-Service provider, the SDK currently fails because of the broken BitcoinAverage link (which gets price data). The goal of this challenge is to replace bitcoinaverage with a new provider: CoinGecko

# Definition of Done
Replace all usages of BitcoinAverage with CoinGecko. This will involve some global searches across the repo, and some investigation into the [CoinGecko API ](https://www.coingecko.com/api/documentations/v3#/). BitcoinAverage gets used [here](https://github.com/BitGo/BitGoJS/blob/b3a14c1d52f6bc26d41d2c119b1bb5e03aa49d2d/modules/core/src/v2/coins/abstractUtxoCoin.ts#L1521). And the relevant line in the config file is [here](https://github.com/BitGo/BitGoJS/blob/b3a14c1d52f6bc26d41d2c119b1bb5e03aa49d2d/modules/core/src/config.ts#L173)
Also please update [this test file](https://github.com/BitGo/BitGoJS/blob/b3a14c1d52f6bc26d41d2c119b1bb5e03aa49d2d/modules/core/test/v2/lib/recovery-nocks.ts) properly (used for mocking in the test suite)

**Comment by antonina-cherednichenko** [comment]
@inprogress

**Comment by tylerlevine** [comment]
This is being tracked as BG-18654

**Comment by cooncesean** [comment]
Fixed with: https://github.com/BitGo/BitGoJS/pull/693
