### ISSUE TITLE
Extend EOS Expiration for Non-BitGo Recoveries

### ISSUE THREAD

**Issue by marktoda** [BitGo/BitGoJS#677]
EOS Transactions are built with a 1 hour expiration time by default, as the network generally does not propagate transactions whose expiration is more than 1 hour from the present time. However, when performing a recovery, the offline signing process often takes several hours. This issue is to change the non-BitGo recovery transaction building [logic](https://github.com/BitGo/BitGoJS/blob/29cc698bb3dc3700499cba3d7f69e88f88d0125f/modules/core/src/v2/coins/eos.ts#L823) to use a longer expiration time of 8 hours. You can see [here](https://github.com/BitGo/BitGoJS/blob/29cc698bb3dc3700499cba3d7f69e88f88d0125f/modules/core/src/v2/coins/eos.ts#L762) that the expiration date is always set to 1 hour from the present time. 

## Current Behavior

Transactions expire 1 hour after being built. This is not enough time to perform a multi-party recovery.

## Possible Solution

Extend the expiration farther, to 8 hours beyond the present time. 

## Steps to Reproduce

1. Create a TEOS wallet with Coincover as backup key provider
2. Fund TEOS wallet
3. Use [WRW](https://github.com/bitgo/wallet-recovery-wizard) and do Non-BitGo recovery on the wallet
4. Send half-signed recovery transaction to Coincover
5. They sign and send back
6. Try to broadcast

**Comment by tylerlevine** [comment]
This is being tracked as BG-19622
