### ISSUE TITLE
Recovery keycard generation

### ISSUE THREAD

**Issue by jpcapurro-atixlabs** [BitGo/BitGoJS#686]
## Feature Description
The ability to generate a keycard similar to BitGo's, so third-party applications can enable their users to back up their keys in a format that is compatible with bitgo's recovery password recovery and [recovery tool](https://bitgo.github.io/bitgo-recovery-tool/)

## Motivation
Prevent third-party applications from re-implementing the keycard generation, and avoiding mistakes/incompatibilities.
Perhaps making it clear in the keycard that the wallet was generated in a third-party application could make troubleshooting easier.

## Context
I'm developing an application which asks the user for their bitgo developer token and creates a BitGo wallet.
Our application doesn't save or use the keys, it must only show them to the user in some way in order for them to back them up.

The user is expected to operate said wallet via BitGo's frontend, and should ideally have the same security as if they created the wallet there.

In order to use BitGo's wallet password recovery and [recovery tool](https://bitgo.github.io/bitgo-recovery-tool/), the user needs to have a keycard with the same format as the one generated in BitGo's web wallet.

## What I've tried so far

I searched through the documentation for bitgo API [v1](https://bitgo.github.io/bitgo-docs/) and [v2](https://www.bitgo.com/api/v2/), and skimmed through the list of projects of BitGo's GitHub organization, and didn't find anything related to keycard generation.

Is this functionality available somewhere and I missed it?

Should I make this request in a different channel instead?

**Comment by tylerlevine** [comment]
We do have an example of keycard generation here: https://github.com/BitGo/BitGoJS/blob/master/modules/core/src/v2/internal/keycard.ts.

This is not the code we use on www.bitgo.com for keycard generation (that code is in our front end - I'll look into whether it's possible to open source this piece). For now though, you should be able to get something that looks pretty close using the code above.

**Comment by jpcapurro-atixlabs** [comment]
Thanks @tylerlevine , we were able to use the file you mentioned to create recovery keycards.
I'm closing the issue :sparkles:
