### ISSUE TITLE
You have called a BitGo Express endpoint but this is the BitGo server.

### ISSUE THREAD

**Issue by RudrikaFichadiya** [BitGo/BitGoJS#719]
Everytime try to call API:
**URL:**
https://test.bitgo.com/api/v2/tbtc/wallet/111walletID2222/sendcoins

**Getting this response:** 
{
    "error": "You have called a BitGo Express endpoint but this is the BitGo server. Please have a look at the BitGo Express documentation: https://www.bitgo.com/api/v2/#bitgo-express-rest-api",
    "name": "ApiError",
    "requestId": "fhgt6e645ty706vr4rt56yupe6",
    "context": {}
}

Is this route for BitGo Express available to make call or not?

**Comment by tylerlevine** [comment]
You'll need to run the bitgo-express proxy locally instead of trying to call the routes on test.bitgo.com directly. Please see https://github.com/BitGo/BitGoJS/tree/master/modules/express#running-bitgo-express

**Comment by RudrikaFichadiya** [comment]
Okay. Is it mandatory to run it locally?

**Comment by tylerlevine** [comment]
Yes. The idea behind bitgo express is that it runs on a server you control, and does transaction signing using your keys. BitGo never has your keys, so we cannot sign transactions on your behalf.
