### ISSUE TITLE
Testnet: Webhook Simulate API always returns "invalid webhook type"

### ISSUE THREAD

**Issue by cyberluke** [BitGo/BitGoJS#72]
Request: https://test.bitgo.com/api/v2/tbtc/webhooks/59ea27a40157391f08f8bff2d26c1f43/simulate

Response:
Invalid HTTP return code: 400
{"error":"invalid webhook type","requestId":"cj905686x0olflkrv7e9fpce2"}

I tried both types: transfer and transaction. Register webhook api works, returns 200 and webhook id.

**Comment by cyberluke** [comment]
Any updates?

**Comment by GeRikz** [comment]
i got same problem only with live network

**Comment by CapnMigraine** [comment]
Hi @cyberluke 

The API you can simulate user and wallet webhooks. The endpoint you are using is for simulating user webhooks.

Additionally, wallet webhooks need to be of have type _transfer_ or _pendingapproval_

Please use the endpoint below for simulating wallet webhooks: 
`/api/v2/:coin/wallet/:walletId/webhooks/:webhookId/simulate`

**Comment by CapnMigraine** [comment]
I'm closing this issue. If you have more questions about the BitGo Webhook notifications, feel free to browse our [API documentation](https://www.bitgo.com/api/v2/) or email support@bitgo.com with your user and wallet id.

**Comment by kak2z7702** [comment]
HI... I have same problem...
```
        $response = $client->request(
            'POST',
            'tbtc/webhooks/60657a8d8ced080006d002a9858f7ff6/simulate'
        );
```
i got 
```
Client error: `POST https://app.bitgo-test.com/api/v2/tbtc/webhooks/60657a8d8ced080006d002a9858f7ff6/simulate` resulted in a `400 Bad Request` response:
{"error":"invalid webhook type","name":"Invalid","requestId":"ckmypcaez044k062r5uy6vquw","context":{}}
```

if I use the link from the post above then I get ..
```
        $response = $client->request(
            'POST',
            'tbtc/wallet/60657a53acfe8e0006d3fce2789de395/webhooks/60657a8d8ced080006d002a9858f7ff6/simulate'
        );
```

```
Client error: `POST https://app.bitgo-test.com/api/v2/tbtc/wallet/60657a53acfe8e0006d3fce2789de395/webhooks/60657a8d8ced080006d002a9858f7ff6/simulate` resulted in a `400 Bad Request` response:
{"error":"invalid transferId: undefined","name":"Invalid","requestId":"ckmypgtnw00ty063qmsxn7vhx","context":{}}
```
