### ISSUE TITLE
i'm getting issue in npm install inside bitgojs folder on server

### ISSUE THREAD

**Issue by rahulyuva** [BitGo/BitGoJS#721]
> root@1.0.0 postinstall /home/ubuntu/BitGoJS
> lerna run build --stream

lerna notice cli v3.20.2
lerna info versioning independent
lerna info Executing command in 3 packages: "yarn run build"
@bitgo/statics: yarn run v1.22.4
@bitgo/statics: $ tsc
@bitgo/statics: /bin/sh: 1: tsc: not found
@bitgo/statics: error Command failed with exit code 127.
@bitgo/statics: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 127 in '@bitgo/statics'
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! root@1.0.0 postinstall: `lerna run build --stream`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the root@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-04-09T07_20_45_646Z-debug.log

**Comment by tylerlevine** [comment]
We use yarn and not npm. Please see https://github.com/BitGo/BitGoJS/blob/master/DEVELOPERS.md if you want to install BitGoJS yourself instead of using the npm package.
