### ISSUE TITLE
Send BTC amount problem

### ISSUE THREAD

**Issue by PolymathWhiz** [BitGo/BitGoJS#726]
When sending BTC or TBTC to an address in the same Wallet using the send method, the amount returned on the response does not correlate to the amount being sent. I do not know if this is normal behavior or a bug. 

For instance, when sending 0.001 TBTC, the response amount sent is 0.00000539 TBTC. 

If this is normal behavior, can you please tell me how to go around this in the case that wallet addresses are assigned to users and a user might want to funds to another address on the same 
 TBTC wallet.

The SDK works perfectly when the two address belongs to different wallets

cc @tylerlevine

**Comment by tylerlevine** [comment]
The transfer amount is the total amount leaving the wallet. If you transfer between two addresses on the same wallet, the only amount leaving the wallet is the mining fee, and the response amount seems to be about what the mining fee would be, so I think this is correct.

**Comment by PolymathWhiz** [comment]
Thanks for your response.

How will I handle cases in a pooled wallet setup (omnibus wallet)? I'd like to know the amount to credit the other wallet address and know when the transaction came from an address in the pooled wallet vs from an external wallet.

**Comment by tylerlevine** [comment]
Have you tried reaching out to support@bitgo.com with your question? Typically that is the way to go for general integration guidance.

**Comment by PolymathWhiz** [comment]
will do
