### ISSUE TITLE
memo in send coins for EOS wallet

### ISSUE THREAD

**Issue by ratul-srit** [BitGo/BitGoJS#729]
when I created address for EOS, the address have a memoId as query string. e.g. `a3cde4tvozni?memoId=85`
when goes to send coin I can send this whole address as parameter. e.g.
>{
    "amount": 1.94227376,
    "address": "a3cde4tvozni?memoId=85",
    "numBlocks": 12
}
 
however, when I fetch the transaction, I dont see the memoId in the transaction entries. e.g.

>{
        "walletId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "currency": "TEOS",
        "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "txId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "createdDate": "2020-04-28T11:01:42.000Z",
        "confirmations": 36,
        "type": "receive",
        "amount": 1.9423,
        "bitgoFee": 0,
        "state": "confirmed",
        "usd": 5.321902,
        "history": [
            {
                "date": "2020-04-28T11:01:42.000Z",
                "action": "confirmed",
                "comment": null
            },
            {
                "date": "2020-04-28T11:01:42.000Z",
                "action": "created",
                "comment": null
            }
        ],
        "entries": [
            {
                "address": "awoqvqbbvw1j",
                "value": -19423,
                "valueString": "-19423",
                "isPayGo": false
            },
            {
                "address": "a3cde4tvozni",
                "wallet": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "value": 19423,
                "valueString": "19423",
                "isPayGo": false,
                "label": "dev teos"
            }
        ]
    }`

why its strips from entries? is it possible have it in entries like `a3cde4tvozni?memoId=85`

**Comment by tylerlevine** [comment]
Hello,

Since this is a question about the BitGo API, and not about the BitGo SDK itself, could you reach out to support@bitgo.com with your question? Thanks!
