### ISSUE TITLE
Bitgo Sendcoins failed without insufficient balance

### ISSUE THREAD

**Issue by omkarsunku** [BitGo/BitGoJS#736]
Hello All,

Today I tried to send coins from bitgo wallet to another address even though I have sufficient balance in my account but bitgo response was 400 and insufficient balance error.
Response from bitgo Content":"{\"name\":\"InsufficientBalance\",\"error\":\"insufficient funds\",\"context\":{},\"status\":400,\"message\":\"insufficient funds\"}.
Can anyone help me here exactly why I am facing this issue?

Thanks

**Comment by tylerlevine** [comment]
Hello, this seems like an issue with our API and not the SDK itself. Could you reach out to support@bitgo.com with your question? Thanks!

**Comment by Adesubomi** [comment]
Please, were you able to fix this. I'm facing the exact same problem, and I have more than sufficient fund
