### ISSUE TITLE
Documentation update on keychain generation

### ISSUE THREAD

**Issue by jpcapurro-atixlabs** [BitGo/BitGoJS#745]
I found (what I think are) a few issues with the documentation for adding a keychain to bitgo with the sdk:
- [  ] when creating a keypair locally (without sending it to bitgo), the documentation mentions the 'store keychain api call' but doesn't link to it: https://www.bitgo.com/api/v2/#operation/express.keychain.local
- [  ] in the [section for persisting a keychain to bitgo](https://www.bitgo.com/api/v2/#operation/v2.key.add)
    - [  ] it's not clear if the `create` call creates a keychain locally only or sends it to bitgo (in the browser it seems to create it locally only)
    - [  ] the `add` method isn't documented, and its `originalPasscodeEncryptionCode` parameter isn't mentioned in the documentation, so it has been rather difficult to replicate what the SDK does with the `generateWallet` method.

## Feature Description
Update the documentation to include the addition of keychains and the `originalPasscodeEncryptionCode` parameter.

## Motivation
Make the creation of wallets via 'advanced' use of the API more accesible

## Context
I'm generating the keys in the frontend and sending:
- encryptedUserPrivkey
- originalPasscodeEncryptionCode
- userPubkey
- backupPubkey
- label

to the backend, where the keychains are registered and the wallet is created.

**Comment by tylerlevine** [comment]
Thanks for the feedback! I will clean up and expand the docs on this subject a bit more - we could definitely use more detail here.
