### ISSUE TITLE
Npm install  -> lerna ERR!

### ISSUE THREAD

**Issue by deathmorlock** [BitGo/BitGoJS#746]
Nodejs  v10.20.1

```
git clone https://github.com/BitGo/BitGoJS
cd BitGoJS
npm install
```

lerna notice cli v3.20.2
lerna info versioning independent
lerna info Executing command in 3 packages: "yarn run build"
lerna ERR! yarn run build exited 2 in '@bitgo/statics'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! root@ postinstall: `lerna run build --stream`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the root@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by tylerlevine** [comment]
Hello,

Have you tried installing from the npm package using `npm install --save bitgo` (see https://github.com/BitGo/BitGoJS/tree/master/modules/core#installation)?

Is there some other reason you want to install from the github repo directly (this is not normally recommended unless you are contributing back to the project)?

**Comment by deathmorlock** [comment]
But how can i get ./bitgo-express in bin folder ?
only if i use  git checkout tags/4.49.0  - i can install it without errors, but this version too old
