### ISSUE TITLE
Error : Sign Txn

### ISSUE THREAD

**Issue by sachin-lalaworld** [BitGo/BitGoJS#75]
I am getting issue, while sending transaction. Please help me out.

URL : http://localhost:3080/api/v2/tbtc/wallet/5a08519e7af0c0b607c44a267116b2da/signtx

Request : 

{"txPrebuild":{
    "txHex": "010000000120ea8cd54bf21603600e78053a46c8df7b8a37516e599e92052e17d885c9141d0000000000ffffffff028303bb070000000017a91464983ec77174ca427841d11e1d1ca2bc93a3f9ea87a08601000000000017a91471493bfe4d0074f68f4ffd320db088be98b6dd548700000000",
    "txInfo": {
        "nP2SHInputs": 1,
        "nSegwitInputs": 0,
        "nOutputs": 2,
        "unspents": [
            {
                "chain": 1,
                "index": 5,
                "redeemScript": "52210376791b03cd01c1c76d0ab0493ecb76f6f2e12dbbca9965b05c97acaea8c023912103502e15ae1865cf159dcdbb8a5f04eeee578e986cfa9118d5c8d9532949da04d721036d6617cf5b6370ea31427b76021d0c0ea5bf2c41416e0ef4d3d369daf94e1ac453ae",
                "id": "1d14c985d8172e05929e596e51378a7bdfc8463a05780e600316f24bd58cea20:0",
                "address": "2N5VLpqHHtNwsMEWMUgEWYSMuuXn1Sdq1fa",
                "value": 129797762
            }
        ],
        "changeAddresses": [
            "2N2R7weiUKiDZ4gdfUfmceDwyGRGBvngTPq"
        ]
    },
    "feeInfo": {
        "size": 373,
        "fee": 1119,
        "feeRate": 3000,
        "payGoFee": 0,
        "payGoFeeString": "0"
    }
}
}

Response : 

{
    "message": "404\nNot Found\nPage Not FoundPlatform APIWalletLog In   Page Not FoundSorry, we couldn't find the page you were looking for.Back to homepage"
}

Please help me out.

**Comment by thomas4019** [comment]
Hi Sachin,
It seems from this error that your wallet id is invalid. Can you check to make sure you're using the correct id and that it is a v2 btc wallet?

**Comment by sachin-lalaworld** [comment]
No, my wallet Id is correct.

Regards

Sachin Sharma

Software Developer

On Nov 22, 2017 10:43 PM, "Thomas Hansen" <notifications@github.com> wrote:

Hi Sachin,
It seems from this error that your wallet id is invalid. Can you check to
make sure you're using the correct id and that it is a v2 btc wallet?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BitGo/BitGoJS/issues/75#issuecomment-346416199>, or mute
the thread

**Comment by thomas4019** [comment]
Hi Sachin,
Actually the signtx endpoint doesn't take the wallet id. From our [docs](https://www.bitgo.com/api/v2/?shell#sign-transaction), it looks like you should use the path http://localhost:3080/api/v2/tbtc/signtx.

**Comment by dennisli92** [comment]
Bump on this. It seems like the docs now point towards `/api/v2/tbtc/wallet/<walletId>/signtx` but I got a 404. I ended up changing it to `/api/v2/tbtc/signtx` and it seems to work, although I still get a 500 error (keychain or private key error?).

I am running bitgo js 4.45.0 https://github.com/BitGo/BitGoJS/releases/tag/4.45.0
