### ISSUE TITLE
this.version is not a function

### ISSUE THREAD

**Issue by wascript3r** [BitGo/BitGoJS#79]
Hello, after installing bitgo and trying to run the script I get the following error: http://prntscr.com/hh9xtp
My script: https://pastebin.com/pKu4qZDA
I am running node.js **v8.9.1**

**Comment by thomas4019** [comment]
Hi, it looks like you're missing the new keyword before calling BitGoJS.BitGo(). Please see the example in our [api docs](https://www.bitgo.com/api/v2/#software-development-kit).

**Comment by wascript3r** [comment]
Oh, sorry, that's a stupid mistake. But after correcting my code I get this error: https://pastebin.com/wdtBfmUu

**Comment by wascript3r** [comment]
Solved this by creating a new account and API key at test.bitgo.com
