### ISSUE TITLE
Can't send transactions using the Bitgo API 

### ISSUE THREAD

**Issue by Rub3nC** [BitGo/BitGoJS#82]
Hi I am trying to use the bitgo API to send some funds using the api as it is described here:
https://bitgo.github.io/bitgo-docs/?shell#send-coins-to-address and  here: https://bitgo.github.io/bitgo-docs/?shell#send-coins-to-multiple-addresses 

These are the errors I am getting:
for a single address:
{"error":"Missing parameter: address","message":"Missing parameter: address"}

to multiple addresses:
{"error":"expecting recipients object","message":"expecting recipients object"}

I am using python and using the bitgo express server, I've been stuck for a while and started execute the curl commands shown in the documentation only to get the same errors. 

these are  the logs of the bitgo express server:
```
error 400: expecting recipients object
127.0.0.1 - local_express [13/Dec/2017:23:36:45 +0000] "POST /api/v1/wallet/2Mxx3mF5dFHZzgZfwRcCVZq71jTiQ2WQsLg/sendmany HTTP/1.1" 400 79 "-" "python-requests/2.18.4"
error 400: Missing parameter: address

127.0.0.1 - local_express [14/Dec/2017:01:03:12 +0000] "POST /api/v1/wallet/2Mxx3mF5dFHZzgZfwRcCVZq71jTiQ2WQs

127.0.0.1 - local_express [13/Dec/2017:23:36:45 +0000] "POST /api/v1/wallet/2Mxx3mF5dFHZzgZfwRcCVZq71jTiQ2WQsLg/sendmany HTTP/1.1" 400 79 "-" "python-requests/2.18.4"
error 400: Missing parameter: address

127.0.0.1 - local_express [14/Dec/2017:01:03:12 +0000] "POST /api/v1/wallet/2Mxx3mF5dFHZzgZfwRcCVZq71jTiQ2WQsLg/sendcoins HTTP/1.1" 400 77 "-" "curl/7.52.1"
```
the version of the bitgo express is 4.15.0

I don't know what am I doing wrong, hope you can point me in the right direction, thanks!

PD: I only wanted to send multiple transactions but started to test the single transaction option to see if it worked.

**Comment by Rub3nC** [comment]
If anyone stumble with this issue, the solution is that the _Content-Type: application/json_ header is mandatory.

**Comment by bburtin** [comment]
Thanks for reporting this.  The server should either handle a missing `Content-Type` header or return a more intuitive error message in this case.  I filed an internal bug for this issue and will fix it in an upcoming release.

**Comment by bobozar** [comment]
Has the bug been fixed yet. I'm facing similar problem and I'm using Python too!
