### ISSUE TITLE
BTC Wallets created via bitgo library won't display in website

### ISSUE THREAD

**Issue by taminhtien** [BitGo/BitGoJS#83]
Hi everybody,

I have an enterprise account in bitgo.com. I tried to create some BTC wallets in website. I created 5 wallets but I cannot get the wallet ID in the website. Then I use REST API to get list of wallets. Surprisingly, the API return me nothing. Then I use bitgo npm package to create BTC Wallet with my access token generated from production account, env set to `prod`. I can create wallet and get the wallet ID. After that I use REST API to get list wallets and the new wallet show up.

The problem is I cannot see my wallet in the website (https://www.bitgo.com). If I cannot see my wallet then how I see BTC that users transfer to me?

Also create wallet REST API won't work, it returns me "page not found", I have to create wallet via bitgo js library.

Thanks,
Tom

**Comment by bburtin** [comment]
If the API is returning 404, the most likely explanation is that your URL path is incorrect.  Please compare the URL that you're using in your HTTP client with the BitGo Express endpoints documented at https://bitgo.github.io/bitgo-docs/#bitgo-api-endpoints

**Comment by taminhtien** [comment]
I use api v2, generate wallet already documented at https://www.bitgo.com/api/v2/#generate-wallet. But it won't work.

Do you have any idea that why wallets in website are different with wallets get from API/bitgojs?

**Comment by thomas4019** [comment]
Hi Tom,
What email is the account you used to generate the 5 wallets? I don't see them on your account so it may be that you didn't finish the wallet creation process. 

Also note that our V1 and V2 BTC wallets use different databases and V2 BTC wallets are not shown in the UI yet for most users. So currently, you'll need to use our v1 API at https://bitgo.com/api if you want them to show up. Or we can enable V2 BTC in the UI for your account, but it's not feature complete yet.

Regarding wallet generation failing are using the shell or JavaScript commands? Could you please an example of the code you're using? If you're using the shell, you will need to be running bitgo-express on your machine or one of your servers.

**Comment by taminhtien** [comment]
Hi Thomas,

Thank for your reply,

I understand the problem already, in production site you hide the BTC V2 in the UI. The wallet generation failing because I use shell without running bitgo express, I made a POST request to `https://www.bitgo.com/api/v2/:coin/wallet/generate`. It's my bad, I not read the document clearly.

By the way, can you enable BTC V2 access to these accounts: maxym.saharov@gmail.com and su@agilelab.sg. In case I cannot make it work with BTC V1, I can use BTC V2.

Thanks,
Tom

**Comment by thomas4019** [comment]
Hi Tom,
I'm glad that it's working for you. I've added V2 BTC access to both those accounts, but please be aware that features are still being added and the documentation is still incomplete for it.

**Comment by StarNeit** [comment]
Hello Thomas,

I also have got same issue now.
I have created 4 new wallets using https://www.bitgo.com/api/v2/#generate-wallet yesterday.
(
'BTC wallet for PRE-ICO' 
'BCH wallet for PRE-ICO' 
'LTC wallet for PRE-ICO'
 'ETH wallet for PRE-ICO'
)
But, I am not able to see these wallets on my Bitgo account UI.

I am using enterprise account in bitgo.com.
My account is hariyono1000@gmail.com

Could you please enable BTC/BCH/LTC V2 access to my accounts as soon as possible?
We're in business now, and I hope you to solve my issue too.

Thank you.
