### ISSUE TITLE
Can't send coins- huge bug

### ISSUE THREAD

**Issue by bobozar** [BitGo/BitGoJS#84]
I read through the issues for a similar problem but the none fixed my issue. I'm on python, so I want to send coins to another address,

```
>>> headers = {
  'Authorization': 'Bearer v2x94df7d21a8'}
>>> values = {'address':'2MysNjdxmDi2grWExUzw86fgfgfgfgfgg', 'amount':AMOUNT, 'walletPassphrase':WALLETPASSPHRASE}
>>> uri = 'http://localhost:3080/api/v1/wallet/{}/sendcoins'.format(WALLETID)
>>> rex = requests.post(uri, data=values, headers=headers)
>>> rex.text
u'{"error":"Missing parameter: address","message":"Missing parameter: address"}'
```
Any solution?

**Comment by thomas4019** [comment]
Hi bobosar,
I think you need to use the json parameter instead of the data parameter for requests [(see this)](https://stackoverflow.com/a/26344315). The BitGo API expects data to be send in the message body in json format so I think that should make it work.

**Comment by bobozar** [comment]
@thomas4019 

Thanks for the reply.  I tried this,

>>> import json
>>> rex = requests.post(uri, data=json.dumps(values), headers=headers)
>>>u'{"error":"Missing parameter: address","message":"Missing parameter: address"}'

Then I did this,

>>> headers = {
  'Authorization': 'Bearer v2x94df7d21a805c9','Content-Type': 'application/json'}
>>> rex = requests.post(uri, data=json.dumps(values), headers=headers)
>>> rex.text
u'{"error":"getaddrinfo ENOTFOUND test.bitgo.com test.bitgo.com:443","message":"getaddrinfo ENOTFOUND test.bitgo.com test.bitgo.com:443"}'

Tried again due to network issue, I got the below message.

>>> rex = requests.post(uri, data=json.dumps(values), headers=headers)
>>> rex.text
u'{"error":"0 unspents available for transaction creation","message":"0 unspents available for transaction creation"}'

It seems it's working because I don't have any BTC in the wallet yet. What do you think?

**Comment by thomas4019** [comment]
Yeah, it looks like it's working for you now. Once you have btc in the wallet you'll be able to send. I'm going to mark this as closed for now.
