### ISSUE TITLE
Webhook Response Not Complete

### ISSUE THREAD

**Issue by bobozar** [BitGo/BitGoJS#86]
I want to create a 'transaction' webhook so that when a user receives BTC with an address, the webhook will trigger an event that will load a callback URL, and I will check for confirmation, get 'the address' in order to get the balance and do whatever I want to do.

In BitGo API docs, 'address' is not returned in the response.

Walletid, type of webhook are what are returned. How do I go about getting the address that receives BTC?

**Comment by thomas4019** [comment]
The webhook response should include the transaction hash which you can then lookup in our [API](https://bitgo.github.io/bitgo-docs/#get-wallet-transaction) for more details. Specifically, you can look at either the outputs field in the transaction info to find the address (find the one where isMine is true).

**Comment by bobozar** [comment]
@thomas4019 Thanks for the reply. I still have a few questions, but 1. isMine = True can only be true for a single address that just receives BTC? 2. Do I need to decode or do something to get the address from transaction hash?

**Comment by thomas4019** [comment]
1. Generally there will only be a single address where isMine is true, but someone might send bitcoins to you at several addresses you control in on transaction. Or they could even send multiple small payments to the same address in one transaction.
2. The transaction hash itself cannot be decoded for more info. Like I said in my last message you'll need to fetch the transaction details from our API or you could fetch the destination addresses from a public blockchain explorer API (but it will be hard to distinguish between your output address and the change address there).
