### ISSUE TITLE
How to add test bitcoin

### ISSUE THREAD

**Issue by ravi-poonia** [BitGo/BitGoJS#869]
Is there any example or article explaining : **How to add test bitcoin**

**Comment by tjgrist** [comment]
I'm looking for the same.

**Comment by tjgrist** [comment]
@ravi-poonia , I googled how to do this, and found this info: [https://support.bitpay.com/hc/en-us/articles/360015463612-How-to-Create-a-Testnet-Wallet#:~:text=Navigate%20to%20https%3A%2F%2Ftestnet,random%20amount%20of%20testnet%20cryptocurrency.](url)

Hope it helps you out.
