### ISSUE TITLE
More descriptive error messages

### ISSUE THREAD

**Issue by prateekm33** [BitGo/BitGoJS#88]
Could we implement more descriptive error messages so that developers can handle them better?

For example, a call to `wallet.sendCoins()` can error out with `Unable to decrypt user keychain` as a message, but the error object is not returned to the client. I would not have known that the issue had to do with a password mismatch had I not modified the BitGo client source code to return to me the error object with detailed descriptions.

**Comment by LeoKotschenreuther** [comment]
@prateekm33 Thanks for bringing that up! We will work on improving our error messages and to return the original error message as well.
