### ISSUE TITLE
multiple address, one wallet.

### ISSUE THREAD

**Issue by dostrct** [BitGo/BitGoJS#887]
## Feature Description

multiple address within a wallet.

## Motivation

if so, users can use feature more fast,

## Context

Managing a wallet with a multiple aderess is more efficient and good to handle users then managing multiple wallets with each address.

and more fast.

If you already have that feature, could you let me know reference please?

I read api docs but I can't find that feature.
(Hence It's my first time to use bitgo even onchain-data, I might have missed it.)
Thank you very much

**Comment by tylerlevine** [comment]
Sure, there is `wallet.createAddress()` to create additional addresses.
