### ISSUE TITLE
ETH. Error: invalid signature address

### ISSUE THREAD

**Issue by artjoma** [BitGo/BitGoJS#897]
## Environment Details
* **OS:** Linux
* **Node Version:** v11.15.0
* **Yarn Version:** no
* **BitGoJS Version:** 11.5.0
* **BitGo Environment:** testnet

## Expected Behavior
Ethereum transaction. Based on example: https://app.bitgo-test.com/docs/#operation/express.wallet.sendcoins

## Current Behavior
``` 
 (node:24388) UnhandledPromiseRejectionWarning: Error: invalid signature address 
    at errFromResponse (bitgo/dist/src/bitgo.js:109:15)
    at handleResponseError (bitgo/dist/src/bitgo.js:124:15)
```

## Steps to Reproduce
```
let wallet = await tethCoin.wallets().get({ id: walletId });
    let params = {
        amount: (10 * 1e16).toString(),
        address: recpAddr,
        prv: 'xprv....'
    };

    let txResult = await wallet.send(params);
    console.info("Deposit, tx result:", txResult);
```

**Comment by tylerlevine** [comment]
Thanks, we're investigating this issue

**Comment by tylerlevine** [comment]
Are you able to reproduce this issue on node 10?

**Comment by artjoma** [comment]
I tested on v10.22.1 same: `(node:3466) UnhandledPromiseRejectionWarning: Error: invalid signature address`

**Comment by artjoma** [comment]
Same issue, but using separately "create, sign, send" methods. https://github.com/BitGo/BitGoJS/issues/899

**Comment by tylerlevine** [comment]
Let's use #899 for this, since both tickets seem to report the same issue.
