### ISSUE TITLE
RFC6979 Deterministic Signatures

### ISSUE THREAD

**Issue by dabura667** [BitGo/BitGoJS#9]
bitcoinjs-lib supports RFC6979.

Are there any plans to support it as well?

Referring to:

https://github.com/BitGo/BitGoJS/blob/master/src/bitcoin/ecdsa.js#L208

**Comment by mbelshe** [comment]
Yup.  We are moving to it!

**Comment by dabura667** [comment]
Cool.

Any ETA on when it'll be implemented?

**Comment by bencxr** [comment]
Hey,

We just integrated with the new BitGoJS so signatures are deterministic now.

**Comment by dabura667** [comment]
Great job. Kudos.
