### ISSUE TITLE
Webhook Signal not active

### ISSUE THREAD

**Issue by bobozar** [BitGo/BitGoJS#92]
How are you doing @thomas4019?

Is Bitgo service down? I created a webhook for incoming transactions and I sent BTC to my address and for the past 5hrs, I'm yet to see any form of callback. The wallet balance in my app has not been updated. How often is this breakdown in service or does it has a limit? 2. Should I be running a cronjob that will be checking addresses for balance or incoming transactions?

**Comment by thomas4019** [comment]
Hi @bobozar, It's possible that your webhook has been disabled or maybe the bitcoin transaction just hasn't confirmed yet. I see you also filed a support ticket with this question, which is the right place. Let's resolve this there so I'm going to close this ticket. Thanks!
