### ISSUE TITLE
BitGo website Broken Priority Selection Tool for Transaction Fees

### ISSUE THREAD

**Issue by demetrios-koziris** [BitGo/BitGoJS#95]
Yesterday, I found that the Bitgo website was offering higher fees (for the same transaction) on the Low Priority options than on the High/Medium Priority options:

0.00188090 BTC fee for High Priority (est. 2 blocks)        
0.00146819 BTC fee for Medium Priority (est. 12 blocks)   
0.00805223 BTC fee for Low Priority (est. 60 blocks)        
0.00636303 BTC fee for Very Low Priority (est. 300 blocks)

I just tested again and it is still broken:

0.00895603 BTC fee for High Priority (est. 2 blocks)        
0.00086207 BTC fee for Medium Priority (est. 12 blocks)   
0.00805234 BTC fee for Low Priority (est. 60 blocks)        
0.00636720 BTC fee for Very Low Priority (est. 300 blocks)

**Comment by thomas4019** [comment]
Hi Demetrios,
Thanks for bringing this important issue to our attention. The issue was fixed last week.
