### ISSUE TITLE
SDK size is not deployable in AWS Lambdas

### ISSUE THREAD

**Issue by andreujuanc** [BitGo/BitGoJS#956]
![image](https://user-images.githubusercontent.com/360052/100523190-ce4aa100-31ae-11eb-960e-2eccd77776f9.png)

That's the top 20 dependencies of this library. This was done on a clean folder and just: `npm i bitgo`

I would like to know if it's possible to reduce the amount of unnecessary dependencies that are not explicit in the sdk's package.json. For example: 

- @umpirsky\country-list
- typescript 
- rxjs
- @types (14 types)

And I'm not even counting the amount of SDKs of other blockchains that I'm not using.

I guess that someone started to include sdks without even checking for this stuff. 

I noticed this issue: https://github.com/BitGo/BitGoJS/issues/302 by @jaydenseric and it looks like no body cared and it just got worse over time.

I'm physically constrained by this SDK, and I cannot use our current set of tools and architecture that we've been using for months now. 

UPDATE: I just confirmed that the celo sdk (@celo/contractkit) is one of the biggest problems here:
![image](https://user-images.githubusercontent.com/360052/100523746-166bc280-31b3-11eb-8ed6-7f698bc29d02.png)

UPDATE 2:
Even chai and mocha are included in the dependencies....

**Comment by uncle-scooter** [comment]
I've talked to Bitgo Support about this. They recommended as a last resort using an older version that excludes unnecessary blockchain support and pulling in security updates yourself.

**Comment by andreujuanc** [comment]
Thanks for your reply.
We are thinking on building an AWS lambda docker image, since this approach allows for more storage. I think this should do.  

PS: You should work with library authors to reduce size, since this has a big performance impact regardless of the deployment issue.

**Comment by uncle-scooter** [comment]
> Thanks for your reply.
> We are thinking on building an AWS lambda docker image, since this approach allows for more storage. I think this should do. This can be closed.
> 
> PS: You should work with library authors to reduce size, since this has a big performance impact regardless of the deployment issue.

Be sure to checkout [localstack]( http://localstack.com/) if you havent already.

**Comment by andreujuanc** [comment]
> 
> 
> > Thanks for your reply.
> > We are thinking on building an AWS lambda docker image, since this approach allows for more storage. I think this should do. This can be closed.
> > PS: You should work with library authors to reduce size, since this has a big performance impact regardless of the deployment issue.
> 
> Be sure to checkout [localstack](http://localstack.com/) if you havent already. I'm in talks with them but the engineer I was able to talk to said its on their backlog, but they're incredibly backed up. Hopefully within this quarter.

You probably meant localstack.cloud  😄 
We already use it to do some integration testing. :) 
BTW just for the record, our easiest route was to spin up the express server (docker container) to act as a proxy so the lambdas can be very light without the sdk. We developed a very handy JS client for it.

**Comment by Commoddity** [comment]
Having the same issue here. Was using an older version of BitGo in a Lambda but since AWS is dropping support for older node versions I was forced to upgrade BitGo and the package version is almost unbelievable (near 126MB). This is potentially going to cause a serious problem for our production systems in the near future as we can no longer use BitGo in a Lambda environment.

@andreujuanc I'm curious if this docker/express approach has been working well for you? I haven't got much experience in setting up such a thing and wondering if you can provide any info about your experience and/or resources for how to set up something like that before I commit to trying a similar approach?

**Comment by andreujuanc** [comment]
Hi @Commoddity  
We just lifted a fargate docker container with the express server image, then just http to it.
It has been working perfectly since then. The only issue is that we are not 100% serverless anymore :(  But hey now we've got some web3 listeners and started a couple of containers for that. In these cases we keep almost no logic and use them only as a "translation layer" between server instance and serverless using any kind of messaging system, in our case sns.

**Comment by jasan-s** [comment]
i was hoping to use it in google cloud functions to remain serverless, is this still an issue?

**Comment by Commoddity** [comment]
Hey @jasan-s, I think the Bitgo package itself is too large still for regular Lambda deployments. We were able to solve our specific problem and remain serverless using Lambda and a Docker Container Image (which gives a size limit of up to 10GB), mainly following these docs from AWS: https://docs.aws.amazon.com/lambda/latest/dg/images-create.html 

Essentially it's a Lambda using a container uploaded to Amazon ECR for only the Bitgo related logic that we are invoking use a REST API Gateway.

It was a decent amount of extra config but is working fine now for our use case. Not sure if that's helpful for your google cloud functions use case but thought it worth mentioning in case it gives you ideas for a workaround.

**Comment by frangeris** [comment]
Hi there, having the same issue, first deployment after installing `@bitgo` it's failing due to the size of the unzipped package, we can't migrate to another service, is there any workaround to reduce this size?

This is not ok
![image](https://user-images.githubusercontent.com/811381/235322944-5ed5d33f-4936-4561-a5c4-5a0c4556a5ed.png)
