### ISSUE TITLE
Wallets created via bitgo library won't display in website

### ISSUE THREAD

**Issue by StarNeit** [BitGo/BitGoJS#97]
Hello Thomas,

I have got urgent issue in Bitgo API now.
I have created 4 new wallets using https://www.bitgo.com/api/v2/#generate-wallet yesterday.
(
'BTC wallet for PRE-ICO' 
'BCH wallet for PRE-ICO' 
'LTC wallet for PRE-ICO'
 'ETH wallet for PRE-ICO'
)
But, I am not able to see these wallets on my Bitgo account UI.

I am using enterprise account in bitgo.com.
My account is hariyono1000@gmail.com

Could you please enable BTC/BCH/LTC V2 access to my wallets as soon as possible?
We're in business now, and I hope you to solve my issue too.

Thank you.

**Comment by thomas4019** [comment]
Hi StarNeit,
I think you didn't pass an enterprise id when you created the wallets so they're connected to your personal account. In the UI you can find the wallets by choosing the menu in the top right and selecting your email. If you want the wallets under your enterprise you can delete these ones and recreate wallets with the enterprise id.

**Comment by StarNeit** [comment]
Hi Thomas.

Thank you for your quick response.

I have checked all wallets under my personal account, I found all accounts except "Bitcoin wallet".

There isn't still 'BTC wallet for PRE-ICO'  under my personal account.

I attached my screenshot.
![img_02022018_144512_0](https://user-images.githubusercontent.com/16525001/35722337-2ad6beda-07f6-11e8-89ee-e5a58686d133.png)

FYI, my some customers sent some btc to that wallet. So I want to access that wallet via UI soon.

I look forward to hearing from you.

Regards.

**Comment by thomas4019** [comment]
Hi StarNeit,
I added BTC v2 to the UI in your account. Please logout and log back in and then you should see that option.

**Comment by StarNeit** [comment]
Ok, I have see BTC v2 under my personal account UI.
But, how can I remove these wallets under my personal account.
I want to recreate these under enterprise account.

**Comment by StarNeit** [comment]
Or is it possible to move those wallets from personal to enterprise?

**Comment by StarNeit** [comment]
They don't respond for several hours.
