### ISSUE TITLE
BitGo Express REST API for withdraw sometimes requires OTP

### ISSUE THREAD

**Issue by yivo** [BitGo/BitGoJS#98]
Hello BitGo team.

I have created an account at test.bitgo.com, deployed BitGo Express server and created access token with high spending limits and long lifespan however API requires OTP after 2-3 withdraws. What's wrong?

I run the following code:
```
curl -v -X POST \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $ACCESS_TOKEN" \
-d '{ "address": "$DESTINATION", "amount": "1000000000", "walletPassphrase": "$PASSWORD" }' \
http://$EXPRESS_API_HOST/api/v2/txrp/wallet/$WALLET_ID/sendcoins
```

I get the following response:
```
{"error":"needs unlock","needsOTP":true,"needsUnlock":true,"name":"Response","requestId":"cjd6dflt4b70sdjrscvgks22d","message":"needs unlock"}
```

I expect response to be success and contain TXID.

**Comment by yivo** [comment]
From docs:

```
Alternatively, custom access tokens can be created bound to specific scopes for expiration time, permission level, and spending amount.
```

**Comment by CapnMigraine** [comment]
Hi @yivo, I see you also filed a support ticket for this question. 
We encourage the use of our support portal, so let's troubleshoot your issue there. 
I'm going to close this ticket. 
Thanks!

**Comment by yivo** [comment]
Hello @CapnMigraine! Thank you for the feedback. I will reply you at the support portal.
