### ISSUE TITLE
yarn audit failure: axios (high severity)

### ISSUE THREAD

**Issue by diracdeltas** [BitGo/BitGoJS#982]
tested on master at 254a4663c83fcaa867dc0c514233adcdc90c0436

`yarn audit` is failing in my modules that include this module because it needs to update axios: https://github.com/advisories/GHSA-4w2v-q235-vp99

**Comment by tylerlevine** [comment]
Thanks @diracdeltas, we are looking into this. It looks like `tronweb` and `stellar-sdk` are the source of these, so we need to get some fixes made upstream and then update our dependency versions.

Tronweb issue: https://github.com/tronprotocol/tronweb/issues/127
Stellar SDK issue: https://github.com/stellar/js-stellar-sdk/issues/605

**Comment by diracdeltas** [comment]
thanks tyler, looks like it's fixed in tronweb now and will be fixed in stellar sdk soon: https://github.com/tronprotocol/tronweb/issues/127#issuecomment-776414303

**Comment by tylerlevine** [comment]
Thanks, we will update on our end once the fix is released.
