### ISSUE TITLE
BITGO Can't Start on Production

### ISSUE THREAD

**Issue by bobozar** [BitGo/BitGoJS#99]
On my development or testing server,  I can send bitcoins without no hassle. Because the bitgo-express is starting fine on my windows PC. Now. I want to test the same on test.bitgo.com via my VPS hosting (Ubuntu), I installed BITGOJS and when I run 'node bitgo-express' the server won't start. I'm geting the below error.

What am I missing?

```
n@example:/var/www/stage.example.com/bitgo/BitGoJS/bin$ node bitgo-express
module.js:328
    throw err;
    ^

Error: Cannot find module 'argparse'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/stage.example.com/bitgo/BitGoJS/bin/bitgo-express:2:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
```

**Comment by thomas4019** [comment]
Did you run "npm install" in the BitGoJS folder?

**Comment by bobozar** [comment]
@thomas4019 it's now working. The problem now is that I want to switch from - env test to -env production and also I want to keep it on with supervisord so when I logout from the server , it will still be on, like running as a daemon. Is there a tutorial on that?

**Comment by bobozar** [comment]
Due to the fact that I was geting this error stated here> https://github.com/BitGo/BitGoJS/issues/100

I decided to uninstall and install the new BitGoJS after cloning from repo. So when I tried to start the server I got this,

```
n@example:~/BitGoJS/bin$ node bitgo-express
/home/example/BitGoJS/src/expressApp.js:51
    let options = {};
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/beastman/BitGoJS/bin/bitgo-express:3:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

```

**Comment by thomas4019** [comment]
It sounds like you're using an old version of Node.js. Upgrading it or running the following command may work. node --use-strict bitgo-express

**Comment by bobozar** [comment]
@thomas4019 

I got this.  

```
args = getArgs();
     ^

ReferenceError: args is not defined
    at Object.<anonymous> (/home/example/BitGoJS/bin/bitgo-express:82:6)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

**Comment by bobozar** [comment]
@thomas4019 

You are right. I'm using an old version.

```
/BitGoJS/bin$ node -v
v4.2.6
```
Let me upgrade and run again!

**Comment by bobozar** [comment]
@thomas4019  It's now working! You rock! Now the problem is, how can I make it run as daemon on ubuntu 16.04? I know if I should close the terminal BITGO will stop running.

**Comment by thomas4019** [comment]
Hi bobozar, I'm glad that worked! You could use [forever](https://github.com/foreverjs/forever) to start bitgo-express which should keep it running at least until the server restarts. Tomorrow I can look into our documentation for setting up bitgo express in production.

**Comment by bobozar** [comment]
@thomas4019 

I tried installing the forever. Also it seems it didn't install correctly, but at the moment, I'm yet to close my terminal and BitGOJS is still running.

Look at what I did below.

I cd into the BitGoJS/bin folder and installed the forever monitor. 

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/ch                                                                             okidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                             1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                                                             )
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed                                                                             .
npm WARN bitgo@4.20.0 No license field.

```
I run the below code.

```
n@example:~/BitGoJS/bin$ forever start node bitgo-express
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up f                                                                             or at least 1000ms
info:    Forever processing file: node
error:   Cannot start forever
error:   script /home/example/BitGoJS/bin/node does not exist.
```

And I did this.

```
n@example:~/BitGoJS/bin$ forever start bitgo-express
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up f                                                                             or at least 1000ms
info:    Forever processing file: bitgo-express
```

What do you think?

**Comment by thomas4019** [comment]
This is the correct command to run `forever start bitgo-express`. The command won't work though if you have express running elsewhere though because it will try to use the same port and fail.

**Comment by bobozar** [comment]
@thomas4019 okay thanks. I have a question, is it a must for me to install BitGoJS before sending out coins? Why can't I send via URL like https://www.bitgo.com/api/v1 instead of http://localhost:3080/api/v1 on production?

**Comment by thomas4019** [comment]
Hi bobozar,
As I replied in [this comment](https://github.com/BitGo/BitGoJS/issues/40#issuecomment-368353645), we designed our system is designed to never receive your wallet passphrase. The BitGo SDK or BitGo Express decodes your user key using your passphrase and then signs transactions locally. For us to provide a /sendcoins endpoint on www.bitgo.com, we would need to have your user key on our server which would ruin part of the benefit of a multi-sig wallet.

**Comment by bobozar** [comment]
@thomas4019 okay, thanks for the clarification. Kindly inform me when you update the docs for running BitGoJS as a daemon on a production server.

**Comment by bobozar** [comment]
Hello @thomas4019 , sorry I'm back again!

I want to install BitGoJS on my main production server this time after testing on staging server. Now I'can't install the package. It got killed during installation.

```
mp@thost:~/BitGoJS/bin$ node bitgo-express -v
module.js:471
    throw err;
    ^

Error: Cannot find module 'argparse'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/example/BitGoJS/bin/bitgo-express:2:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
mp@thost:~/BitGoJS/bin$ cd
mp@thost:~$ ls
BitGoJS
mp@thost:~$ cd BitGoJS
mp@thost:~/BitGoJS$ npm install
```
npm ERR! Linux 4.4.0-116-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! Array buffer allocation failed
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
Killed
```
What am I missing?

**Comment by bobozar** [comment]
@thomas4019  I managed to get it to work by npm install [each package] one by one. Now I run bitgojs-- node bitgo-express -e prod and when I tried sending coins, I got, 

`error 400 - needs unlock.`

What am I missing?

**Comment by LeoKotschenreuther** [comment]
You need to call the unlock function. If you use the SDK you should call `bitgo.unlock(...)`. The BitGo Express call should be similar.

**Comment by bobozar** [comment]
@LeoKotschenreuther  I'm not using the sdk. I'm using the bitgo-express. My language is Python. Can't I make it work via the Token spending limit ?

**Comment by LeoKotschenreuther** [comment]
Closing this because we're handling the unlock issue in #102.
